namespace Jroc.Test262.Tests.built_ins.Array.prototype.concat;

public partial class ExecutionTests
{
    [Fact(DisplayName = "arg-length-exceeding-integer-limit")]
    public Task arg_length_exceeding_integer_limit() => ExecutionTestFromFile("arg-length-exceeding-integer-limit");
    [Fact(DisplayName = "arg-length-near-integer-limit")]
    public Task arg_length_near_integer_limit() => ExecutionTestFromFile("arg-length-near-integer-limit");
    [Fact(DisplayName = "Array.prototype.concat_array-like-length-to-string-throws")]
    public Task Array_prototype_concat_array_like_length_to_string_throws() => ExecutionTestFromFile("Array.prototype.concat_array-like-length-to-string-throws");
    [Fact(DisplayName = "Array.prototype.concat_array-like-length-value-of-throws")]
    public Task Array_prototype_concat_array_like_length_value_of_throws() => ExecutionTestFromFile("Array.prototype.concat_array-like-length-value-of-throws");
    [Fact(DisplayName = "Array.prototype.concat_array-like-negative-length")]
    public Task Array_prototype_concat_array_like_negative_length() => ExecutionTestFromFile("Array.prototype.concat_array-like-negative-length");
    [Fact(DisplayName = "Array.prototype.concat_array-like-primitive-non-number-length")]
    public Task Array_prototype_concat_array_like_primitive_non_number_length() => ExecutionTestFromFile("Array.prototype.concat_array-like-primitive-non-number-length");
    [Fact(DisplayName = "Array.prototype.concat_array-like-to-length-throws")]
    public Task Array_prototype_concat_array_like_to_length_throws() => ExecutionTestFromFile("Array.prototype.concat_array-like-to-length-throws");
    [Fact(DisplayName = "Array.prototype.concat_holey-sloppy-arguments")]
    public Task Array_prototype_concat_holey_sloppy_arguments() => ExecutionTestFromFile("Array.prototype.concat_holey-sloppy-arguments");
    [Fact(DisplayName = "Array.prototype.concat_large-typed-array")]
    public Task Array_prototype_concat_large_typed_array() => ExecutionTestFromFile("Array.prototype.concat_large-typed-array");
    [Fact(DisplayName = "Array.prototype.concat_sloppy-arguments")]
    public Task Array_prototype_concat_sloppy_arguments() => ExecutionTestFromFile("Array.prototype.concat_sloppy-arguments");
    [Fact(DisplayName = "Array.prototype.concat_sloppy-arguments-with-dupes")]
    public Task Array_prototype_concat_sloppy_arguments_with_dupes() => ExecutionTestFromFile("Array.prototype.concat_sloppy-arguments-with-dupes");
    [Fact(DisplayName = "Array.prototype.concat_small-typed-array")]
    public Task Array_prototype_concat_small_typed_array() => ExecutionTestFromFile("Array.prototype.concat_small-typed-array");
    [Fact(DisplayName = "Array.prototype.concat_spreadable-boolean-wrapper")]
    public Task Array_prototype_concat_spreadable_boolean_wrapper() => ExecutionTestFromFile("Array.prototype.concat_spreadable-boolean-wrapper");
    [Fact(DisplayName = "Array.prototype.concat_spreadable-function")]
    public Task Array_prototype_concat_spreadable_function() => ExecutionTestFromFile("Array.prototype.concat_spreadable-function");
    [Fact(DisplayName = "Array.prototype.concat_spreadable-number-wrapper")]
    public Task Array_prototype_concat_spreadable_number_wrapper() => ExecutionTestFromFile("Array.prototype.concat_spreadable-number-wrapper");
    [Fact(DisplayName = "Array.prototype.concat_spreadable-reg-exp")]
    public Task Array_prototype_concat_spreadable_reg_exp() => ExecutionTestFromFile("Array.prototype.concat_spreadable-reg-exp");
    [Fact(DisplayName = "Array.prototype.concat_spreadable-sparse-object")]
    public Task Array_prototype_concat_spreadable_sparse_object() => ExecutionTestFromFile("Array.prototype.concat_spreadable-sparse-object");
    [Fact(DisplayName = "Array.prototype.concat_spreadable-string-wrapper")]
    public Task Array_prototype_concat_spreadable_string_wrapper() => ExecutionTestFromFile("Array.prototype.concat_spreadable-string-wrapper");
    [Fact(DisplayName = "Array.prototype.concat_strict-arguments")]
    public Task Array_prototype_concat_strict_arguments() => ExecutionTestFromFile("Array.prototype.concat_strict-arguments");
    [Fact(DisplayName = "create-proxy")]
    public Task create_proxy() => ExecutionTestFromFile("create-proxy");
    [Fact(DisplayName = "create-revoked-proxy")]
    public Task create_revoked_proxy() => ExecutionTestFromFile("create-revoked-proxy");
    [Fact(DisplayName = "create-species")]
    public Task create_species() => ExecutionTestFromFile("create-species");
    [Fact(DisplayName = "create-species-null")]
    public Task create_species_null() => ExecutionTestFromFile("create-species-null");
    [Fact(DisplayName = "create-species-poisoned")]
    public Task create_species_poisoned() => ExecutionTestFromFile("create-species-poisoned");
    [Fact(DisplayName = "create-species-undef")]
    public Task create_species_undef() => ExecutionTestFromFile("create-species-undef");
    [Fact(DisplayName = "create-species-with-non-configurable-property")]
    public Task create_species_with_non_configurable_property() => ExecutionTestFromFile("create-species-with-non-configurable-property");
    [Fact(DisplayName = "create-species-with-non-configurable-property-spreadable")]
    public Task create_species_with_non_configurable_property_spreadable() => ExecutionTestFromFile("create-species-with-non-configurable-property-spreadable");
    [Fact(DisplayName = "create-species-with-non-writable-property")]
    public Task create_species_with_non_writable_property() => ExecutionTestFromFile("create-species-with-non-writable-property");
    [Fact(DisplayName = "create-species-with-non-writable-property-spreadable")]
    public Task create_species_with_non_writable_property_spreadable() => ExecutionTestFromFile("create-species-with-non-writable-property-spreadable");
    [Fact(DisplayName = "is-concat-spreadable-get-err")]
    public Task is_concat_spreadable_get_err() => ExecutionTestFromFile("is-concat-spreadable-get-err");
    [Fact(DisplayName = "is-concat-spreadable-get-order")]
    public Task is_concat_spreadable_get_order() => ExecutionTestFromFile("is-concat-spreadable-get-order");
    [Fact(DisplayName = "is-concat-spreadable-proxy")]
    public Task is_concat_spreadable_proxy() => ExecutionTestFromFile("is-concat-spreadable-proxy");
    [Fact(DisplayName = "is-concat-spreadable-proxy-revoked")]
    public Task is_concat_spreadable_proxy_revoked() => ExecutionTestFromFile("is-concat-spreadable-proxy-revoked");
    [Fact(DisplayName = "is-concat-spreadable-val-falsey")]
    public Task is_concat_spreadable_val_falsey() => ExecutionTestFromFile("is-concat-spreadable-val-falsey");
    [Fact(DisplayName = "is-concat-spreadable-val-truthy")]
    public Task is_concat_spreadable_val_truthy() => ExecutionTestFromFile("is-concat-spreadable-val-truthy");
    [Fact(DisplayName = "is-concat-spreadable-val-undefined")]
    public Task is_concat_spreadable_val_undefined() => ExecutionTestFromFile("is-concat-spreadable-val-undefined");
    [Fact(DisplayName = "length")]
    public Task length() => ExecutionTestFromFile("length");
    [Fact(DisplayName = "name")]
    public Task name() => ExecutionTestFromFile("name");
    [Fact(DisplayName = "not-a-constructor")]
    public Task not_a_constructor() => ExecutionTestFromFile("not-a-constructor");
    [Fact(DisplayName = "prop-desc")]
    public Task prop_desc() => ExecutionTestFromFile("prop-desc");
    [Fact(DisplayName = "S15.4.4.4_A1_T1")]
    public Task S15_4_4_4_A1_T1() => ExecutionTestFromFile("S15.4.4.4_A1_T1");
    [Fact(DisplayName = "S15.4.4.4_A1_T2")]
    public Task S15_4_4_4_A1_T2() => ExecutionTestFromFile("S15.4.4.4_A1_T2");
    [Fact(DisplayName = "S15.4.4.4_A1_T3")]
    public Task S15_4_4_4_A1_T3() => ExecutionTestFromFile("S15.4.4.4_A1_T3");
    [Fact(DisplayName = "S15.4.4.4_A1_T4")]
    public Task S15_4_4_4_A1_T4() => ExecutionTestFromFile("S15.4.4.4_A1_T4");
}
