namespace Js2IL.IR;

/// <summary>
/// Information about an async state machine, populated during HIR->LIR lowering.
/// Contains await points and variables that must survive suspension.
/// </summary>
public sealed class AsyncStateMachineInfo
{
    /// <summary>
    /// List of await points in order of appearance.
    /// Each await point has a unique state ID (1, 2, 3, ...).
    /// State 0 is the initial entry state; state -1 is completion.
    /// </summary>
    public List<AwaitPointInfo> AwaitPoints { get; } = new();

    /// <summary>
    /// Names of variables that must be stored on the scope instance because
    /// they are live across at least one await point.
    /// </summary>
    public HashSet<string> SuspendedVariables { get; } = new();

    /// <summary>
    /// Names of temporary values (generated by the compiler) that must survive
    /// across await points. These become fields on the scope instance.
    /// </summary>
    public List<string> SuspendedTemps { get; } = new();

    /// <summary>
    /// The next state ID to assign to an await point.
    /// </summary>
    private int _nextStateId = 1;

    /// <summary>
    /// Allocates a new state ID for an await point.
    /// </summary>
    public int AllocateStateId() => _nextStateId++;

    /// <summary>
    /// Gets the number of await points in this async function.
    /// </summary>
    public int AwaitPointCount => AwaitPoints.Count;
}

/// <summary>
/// Information about a single await point in an async function.
/// </summary>
public sealed class AwaitPointInfo
{
    /// <summary>
    /// The state ID for resuming after this await (1, 2, 3, ...).
    /// </summary>
    public required int ResumeStateId { get; init; }

    /// <summary>
    /// The LIR label ID to jump to when resuming from this await point.
    /// </summary>
    public required int ResumeLabelId { get; init; }

    /// <summary>
    /// The temp variable that will hold the awaited result value after resumption.
    /// </summary>
    public required TempVariable ResultTemp { get; init; }

    /// <summary>
    /// Optional name for the field that stores the awaited result on the scope instance.
    /// Generated as "_awaited{StateId}" by default.
    /// </summary>
    public string ResultFieldName => $"_awaited{ResumeStateId}";
}
