namespace Js2IL.IR;

/// <summary>
/// Information about an async state machine, populated during HIR->LIR lowering.
/// Contains await points and variables that must survive suspension.
/// </summary>
public sealed class AsyncStateMachineInfo
{
    /// <summary>
    /// List of await points in order of appearance.
    /// Each await point has a unique state ID (1, 2, 3, ...).
    /// State 0 is the initial entry state; state -1 is completion.
    /// </summary>
    public List<AwaitPointInfo> AwaitPoints { get; } = new();

    /// <summary>
    /// Mapping from async state IDs to their resume label IDs.
    /// Includes await resume points and other synthetic resume points (e.g., async try/catch).
    /// </summary>
    public Dictionary<int, int> ResumeLabels { get; } = new();

    /// <summary>
    /// Names of variables that must be stored on the scope instance because
    /// they are live across at least one await point.
    /// </summary>
    public HashSet<string> SuspendedVariables { get; } = new();

    /// <summary>
    /// Names of temporary values (generated by the compiler) that must survive
    /// across await points. These become fields on the scope instance.
    /// </summary>
    public List<string> SuspendedTemps { get; } = new();

    /// <summary>
    /// Whether this async function has await expressions that require full state machine support.
    /// When false, the async function just wraps its return value in Promise.resolve().
    /// </summary>
    public bool HasAwaits { get; set; }

    /// <summary>
    /// The next state ID to assign to an await point.
    /// </summary>
    private int _nextResumeStateId = 1;

    /// <summary>
    /// The next await ID to assign to an await point.
    /// Await IDs are used only for awaited-result storage (e.g., _awaited1, _awaited2, ...).
    /// </summary>
    private int _nextAwaitId = 1;

    /// <summary>
    /// Maximum state ID allocated so far.
    /// </summary>
    public int MaxResumeStateId => _nextResumeStateId - 1;

    /// <summary>
    /// Allocates a new resume state ID.
    /// Resume state IDs are used for dispatch in the async state switch.
    /// </summary>
    public int AllocateResumeStateId() => _nextResumeStateId++;

    /// <summary>
    /// Allocates a new await ID.
    /// Await IDs are used only to select the awaited-result storage slot.
    /// </summary>
    public int AllocateAwaitId() => _nextAwaitId++;

    /// <summary>
    /// Registers a resume label for a given async state ID.
    /// </summary>
    public void RegisterResumeLabel(int stateId, int labelId)
    {
        ResumeLabels[stateId] = labelId;
    }

    /// <summary>
    /// Gets the number of await points in this async function.
    /// </summary>
    public int AwaitPointCount => AwaitPoints.Count;
}

/// <summary>
/// Information about a single await point in an async function.
/// </summary>
public sealed class AwaitPointInfo
{
    /// <summary>
    /// The await ID for this await point (1, 2, 3, ...).
    /// This is used to choose which field stores the awaited result (e.g., _awaited1).
    /// </summary>
    public required int AwaitId { get; init; }

    /// <summary>
    /// The state ID for resuming after this await (1, 2, 3, ...).
    /// </summary>
    public required int ResumeStateId { get; init; }

    /// <summary>
    /// The LIR label ID to jump to when resuming from this await point.
    /// </summary>
    public required int ResumeLabelId { get; init; }

    /// <summary>
    /// The temp variable that will hold the awaited result value after resumption.
    /// </summary>
    public required TempVariable ResultTemp { get; init; }

    /// <summary>
    /// Optional name for the field that stores the awaited result on the scope instance.
    /// Generated as "_awaited{StateId}" by default.
    /// </summary>
    public string ResultFieldName => $"_awaited{AwaitId}";
}
