// <auto-generated />
// Generated from the official Node.js 24.18.1 assert API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/assert.json
// SHA-256: 1b59b341d08850bb477c8d705f2993114825623089b470a1714c4caf4cc33193

#nullable enable
#pragma warning disable CS0618

using AssertContract = Jroc.Runtime.Node.Contracts.IAssertModule;

namespace JavaScriptRuntime.Node;

public sealed partial class AssertModule : AssertContract
{
    object? AssertContract.AssertionError
        => AssertionError;

    object? AssertContract.Assert
        => throw CreateNotImplementedException("Assert");

    object? AssertContract.CallTracker
        => throw CreateNotImplementedException("CallTracker");

    object? AssertContract.strict
        => strict;

    object? AssertContract.assert(object? value)
        => ok(value!);

    object? AssertContract.assert(object? value, object? message)
        => ok(value!, message!);

    object? AssertContract.deepEqual(object? actual, object? expected)
        => throw CreateNotImplementedException("deepEqual");

    object? AssertContract.deepEqual(object? actual, object? expected, object? message)
        => throw CreateNotImplementedException("deepEqual");

    object? AssertContract.deepStrictEqual(object? actual, object? expected)
        => throw CreateNotImplementedException("deepStrictEqual");

    object? AssertContract.deepStrictEqual(object? actual, object? expected, object? message)
        => throw CreateNotImplementedException("deepStrictEqual");

    object? AssertContract.doesNotMatch(string @string, global::JavaScriptRuntime.RegExp regexp)
        => doesNotMatch(@string!, regexp!);

    object? AssertContract.doesNotMatch(string @string, global::JavaScriptRuntime.RegExp regexp, object? message)
        => doesNotMatch(@string!, regexp!, message!);

    global::JavaScriptRuntime.IJavaScriptPromise AssertContract.doesNotReject(object? asyncFn)
        => throw CreateNotImplementedException("doesNotReject");

    global::JavaScriptRuntime.IJavaScriptPromise AssertContract.doesNotReject(object? asyncFn, object? error)
        => throw CreateNotImplementedException("doesNotReject");

    global::JavaScriptRuntime.IJavaScriptPromise AssertContract.doesNotReject(object? asyncFn, object? error, string message)
        => throw CreateNotImplementedException("doesNotReject");

    object? AssertContract.doesNotThrow(global::System.Delegate fn)
        => doesNotThrow(fn!);

    object? AssertContract.doesNotThrow(global::System.Delegate fn, object? error)
        => doesNotThrow(fn!, error!);

    object? AssertContract.doesNotThrow(global::System.Delegate fn, object? error, string message)
        => doesNotThrow(fn!, error!, message!);

    object? AssertContract.equal(object? actual, object? expected)
        => equal(actual!, expected!);

    object? AssertContract.equal(object? actual, object? expected, object? message)
        => equal(actual!, expected!, message!);

    object? AssertContract.fail()
        => fail();

    object? AssertContract.fail(object? message)
        => fail(message!);

    object? AssertContract.fail(object? actual, object? expected)
        => fail(actual!, expected!);

    object? AssertContract.fail(object? actual, object? expected, object? message)
        => fail(actual!, expected!, message!);

    object? AssertContract.fail(object? actual, object? expected, object? message, string @operator)
        => fail(actual!, expected!, message!, @operator!);

    object? AssertContract.fail(object? actual, object? expected, object? message, string @operator, global::System.Delegate stackStartFn)
        => fail(actual!, expected!, message!, @operator!, stackStartFn!);

    object? AssertContract.ifError(object? value)
        => ifError(value!);

    object? AssertContract.match(string @string, global::JavaScriptRuntime.RegExp regexp)
        => match(@string!, regexp!);

    object? AssertContract.match(string @string, global::JavaScriptRuntime.RegExp regexp, object? message)
        => match(@string!, regexp!, message!);

    object? AssertContract.notDeepEqual(object? actual, object? expected)
        => throw CreateNotImplementedException("notDeepEqual");

    object? AssertContract.notDeepEqual(object? actual, object? expected, object? message)
        => throw CreateNotImplementedException("notDeepEqual");

    object? AssertContract.notDeepStrictEqual(object? actual, object? expected)
        => throw CreateNotImplementedException("notDeepStrictEqual");

    object? AssertContract.notDeepStrictEqual(object? actual, object? expected, object? message)
        => throw CreateNotImplementedException("notDeepStrictEqual");

    object? AssertContract.notEqual(object? actual, object? expected)
        => notEqual(actual!, expected!);

    object? AssertContract.notEqual(object? actual, object? expected, object? message)
        => notEqual(actual!, expected!, message!);

    object? AssertContract.notStrictEqual(object? actual, object? expected)
        => notStrictEqual(actual!, expected!);

    object? AssertContract.notStrictEqual(object? actual, object? expected, object? message)
        => notStrictEqual(actual!, expected!, message!);

    object? AssertContract.ok(object? value)
        => ok(value!);

    object? AssertContract.ok(object? value, object? message)
        => ok(value!, message!);

    global::JavaScriptRuntime.IJavaScriptPromise AssertContract.rejects(object? asyncFn)
        => throw CreateNotImplementedException("rejects");

    global::JavaScriptRuntime.IJavaScriptPromise AssertContract.rejects(object? asyncFn, object? error)
        => throw CreateNotImplementedException("rejects");

    global::JavaScriptRuntime.IJavaScriptPromise AssertContract.rejects(object? asyncFn, object? error, string message)
        => throw CreateNotImplementedException("rejects");

    object? AssertContract.strictEqual(object? actual, object? expected)
        => strictEqual(actual!, expected!);

    object? AssertContract.strictEqual(object? actual, object? expected, object? message)
        => strictEqual(actual!, expected!, message!);

    object? AssertContract.throws(global::System.Delegate fn)
        => throws(fn!);

    object? AssertContract.throws(global::System.Delegate fn, object? error)
        => throws(fn!, error!);

    object? AssertContract.throws(global::System.Delegate fn, object? error, string message)
        => throws(fn!, error!, message!);

    object? AssertContract.partialDeepStrictEqual(object? actual, object? expected)
        => throw CreateNotImplementedException("partialDeepStrictEqual");

    object? AssertContract.partialDeepStrictEqual(object? actual, object? expected, object? message)
        => throw CreateNotImplementedException("partialDeepStrictEqual");

    private static global::System.NotImplementedException CreateNotImplementedException(string memberName)
        => new($"The intrinsic node:assert module does not implement 'assert.{memberName}'.");
}
