// <auto-generated />
// Generated from the official Node.js 24.18.1 async_hooks API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/async_hooks.json
// SHA-256: d5bd9fd8a8feef7a6a666cfdb96b7b4094a062f6b0a594141f485095cf834dd3

#nullable enable
#pragma warning disable CS0618

using NestedContract = Jroc.Runtime.Node.Contracts.IAsyncResource;

namespace JavaScriptRuntime.Node;

public sealed partial class AsyncResourceObject : NestedContract
{
    global::System.Delegate NestedContract.bind(global::System.Delegate fn)
        => (global::System.Delegate)bind(fn!)!;
    global::System.Delegate NestedContract.bind(global::System.Delegate fn, object? thisArg)
        => (global::System.Delegate)bind(fn!, thisArg!)!;
    object? NestedContract.runInAsyncScope(global::System.Delegate fn)
        => runInAsyncScope(fn!);
    object? NestedContract.runInAsyncScope(global::System.Delegate fn, object? thisArg, params object?[] args)
        => runInAsyncScope(fn!, thisArg!, args!);
    object? NestedContract.emitDestroy()
        => emitDestroy();
    double NestedContract.asyncId()
        => global::JavaScriptRuntime.TypeUtilities.ToNumber(asyncId());
    double NestedContract.triggerAsyncId()
        => global::JavaScriptRuntime.TypeUtilities.ToNumber(triggerAsyncId());

    private static global::System.NotImplementedException CreateNotImplementedException(string memberName)
        => new($"The intrinsic node:async_hooks.AsyncResource contract does not implement 'asyncResource.{memberName}'.");
}
