// <auto-generated />
// Generated from the official Node.js 24.18.1 async_hooks API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/async_hooks.json
// SHA-256: d5bd9fd8a8feef7a6a666cfdb96b7b4094a062f6b0a594141f485095cf834dd3

#nullable enable
#pragma warning disable CS0618

using NestedContract = Jroc.Runtime.Node.Contracts.IAsyncHook;

namespace JavaScriptRuntime.Node;

public sealed partial class AsyncHookObject : NestedContract
{
    object? NestedContract.enable()
        => enable();
    object? NestedContract.disable()
        => disable();

    private static global::System.NotImplementedException CreateNotImplementedException(string memberName)
        => new($"The intrinsic node:async_hooks.AsyncHook contract does not implement 'asyncHook.{memberName}'.");
}
