// <auto-generated />
// Generated from the official Node.js 24.18.1 buffer API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/buffer.json
// SHA-256: 3ad0db0620e96f0e06fc666a787a7d19cbb99f3e47fd4b17d9725df12ccd361a

#nullable enable
#pragma warning disable CS0618

using BufferContract = Jroc.Runtime.Node.Contracts.IBufferModule;

namespace JavaScriptRuntime.Node;

public sealed partial class BufferModule : BufferContract
{
    double BufferContract.INSPECT_MAX_BYTES
    {
        get => throw CreateNotImplementedException("INSPECT_MAX_BYTES");
        set => throw CreateNotImplementedException("INSPECT_MAX_BYTES");
    }

    double BufferContract.kMaxLength
        => throw CreateNotImplementedException("kMaxLength");

    double BufferContract.kStringMaxLength
        => throw CreateNotImplementedException("kStringMaxLength");

    object? BufferContract.Buffer
        => Buffer;

    object? BufferContract.SlowBuffer
        => throw CreateNotImplementedException("SlowBuffer");

    object? BufferContract.Blob
        => throw CreateNotImplementedException("Blob");

    object? BufferContract.File
        => throw CreateNotImplementedException("File");

    object? BufferContract.constants
        => throw CreateNotImplementedException("constants");

    string BufferContract.atob(object? data)
        => throw CreateNotImplementedException("atob");

    string BufferContract.btoa(object? data)
        => throw CreateNotImplementedException("btoa");

    bool BufferContract.isAscii(object? input)
        => throw CreateNotImplementedException("isAscii");

    bool BufferContract.isUtf8(object? input)
        => global::JavaScriptRuntime.TypeUtilities.ToBoolean(ContractIsUtf8(input!));

    object? BufferContract.resolveObjectURL(string id)
        => ContractResolveObjectURL(id!);

    global::JavaScriptRuntime.Node.Buffer BufferContract.transcode(object? source, string fromEnc, string toEnc)
        => throw CreateNotImplementedException("transcode");

    private static global::System.NotImplementedException CreateNotImplementedException(string memberName)
        => new($"The intrinsic node:buffer module does not implement 'buffer.{memberName}'.");
}
