// <auto-generated />
// Generated from the official Node.js 24.18.1 child_process API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/child_process.json
// SHA-256: 4fbc1a6b0bf6aefe078a8da5afba001de7ca0264a5abb475585559e3f5e62b4e

#nullable enable
#pragma warning disable CS0618

using ChildProcessContract = Jroc.Runtime.Node.Contracts.IChildProcessModule;

namespace JavaScriptRuntime.Node;

public sealed partial class ChildProcess : ChildProcessContract
{
    object? ChildProcessContract.ChildProcess
        => throw CreateNotImplementedException("ChildProcess");

    object? ChildProcessContract.exec(string command)
        => exec(new object[] { command! });

    object? ChildProcessContract.exec(string command, object? callback)
        => exec(new object[] { command!, callback! });

    object? ChildProcessContract.exec(string command, object? options, object? callback)
        => exec(new object[] { command!, options!, callback! });

    object? ChildProcessContract.execFile(string file)
        => execFile(new object[] { file! });

    object? ChildProcessContract.execFile(string file, object? callback)
        => execFile(new object[] { file!, callback! });

    object? ChildProcessContract.execFile(string file, object? options, object? callback)
        => execFile(new object[] { file!, options!, callback! });

    object? ChildProcessContract.execFile(string file, object? args, object? options, object? callback)
        => execFile(new object[] { file!, args!, options!, callback! });

    object? ChildProcessContract.fork(object? modulePath)
        => fork(new object[] { modulePath! });

    object? ChildProcessContract.fork(object? modulePath, object? options)
        => fork(new object[] { modulePath!, options! });

    object? ChildProcessContract.fork(object? modulePath, object? args, object? options)
        => fork(new object[] { modulePath!, args!, options! });

    object? ChildProcessContract.spawn(string command)
        => spawn(new object[] { command! });

    object? ChildProcessContract.spawn(string command, object? options)
        => spawn(new object[] { command!, options! });

    object? ChildProcessContract.spawn(string command, object? args, object? options)
        => spawn(new object[] { command!, args!, options! });

    object? ChildProcessContract.execFileSync(string file)
        => execFileSync(new object[] { file! });

    object? ChildProcessContract.execFileSync(string file, object? options)
        => execFileSync(new object[] { file!, options! });

    object? ChildProcessContract.execFileSync(string file, object? args, object? options)
        => execFileSync(new object[] { file!, args!, options! });

    object? ChildProcessContract.execSync(string command)
        => execSync(new object[] { command! });

    object? ChildProcessContract.execSync(string command, object? options)
        => execSync(new object[] { command!, options! });

    object? ChildProcessContract.spawnSync(string command)
        => spawnSync(new object[] { command! });

    object? ChildProcessContract.spawnSync(string command, object? options)
        => spawnSync(new object[] { command!, options! });

    object? ChildProcessContract.spawnSync(string command, object? args, object? options)
        => spawnSync(new object[] { command!, args!, options! });

    private static global::System.NotImplementedException CreateNotImplementedException(string memberName)
        => new($"The intrinsic node:child_process module does not implement 'child_process.{memberName}'.");
}
