// <auto-generated />
// Generated from the official Node.js 24.18.1 console API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/console.json
// SHA-256: 619993e88c114c5de020998886d6046d130ba36f31ed49d63d873000daaea69c

#nullable enable
#pragma warning disable CS0618

using ConsoleContract = Jroc.Runtime.Node.Contracts.IConsoleModule;

namespace JavaScriptRuntime.Node;

public sealed partial class ConsoleModule : ConsoleContract
{
    object? ConsoleContract.Console
        => Console;

    void ConsoleContract.assert(object? value, params object?[] message)
        => throw CreateNotImplementedException("assert");

    void ConsoleContract.clear()
        => throw CreateNotImplementedException("clear");

    void ConsoleContract.count()
        => throw CreateNotImplementedException("count");

    void ConsoleContract.count(object? label)
        => throw CreateNotImplementedException("count");

    void ConsoleContract.countReset()
        => throw CreateNotImplementedException("countReset");

    void ConsoleContract.countReset(object? label)
        => throw CreateNotImplementedException("countReset");

    void ConsoleContract.debug(object? data, params object?[] args)
        => _ = InvokeContractDebug(data!, args!);

    void ConsoleContract.dir(object? obj)
        => throw CreateNotImplementedException("dir");

    void ConsoleContract.dir(object? obj, object? options)
        => throw CreateNotImplementedException("dir");

    void ConsoleContract.dirxml(params object?[] data)
        => throw CreateNotImplementedException("dirxml");

    void ConsoleContract.error()
        => _ = InvokeContractError();

    void ConsoleContract.error(object? data, params object?[] args)
        => _ = InvokeContractError(data!, args!);

    void ConsoleContract.group(params object?[] label)
        => throw CreateNotImplementedException("group");

    void ConsoleContract.groupCollapsed()
        => throw CreateNotImplementedException("groupCollapsed");

    void ConsoleContract.groupEnd()
        => throw CreateNotImplementedException("groupEnd");

    void ConsoleContract.info()
        => _ = InvokeContractInfo();

    void ConsoleContract.info(object? data, params object?[] args)
        => _ = InvokeContractInfo(data!, args!);

    void ConsoleContract.log()
        => _ = InvokeContractLog();

    void ConsoleContract.log(object? data, params object?[] args)
        => _ = InvokeContractLog(data!, args!);

    void ConsoleContract.table(object? tabularData)
        => _ = table(tabularData!);

    void ConsoleContract.table(object? tabularData, object? properties)
        => throw CreateNotImplementedException("table");

    void ConsoleContract.time()
        => throw CreateNotImplementedException("time");

    void ConsoleContract.time(object? label)
        => throw CreateNotImplementedException("time");

    void ConsoleContract.timeEnd()
        => throw CreateNotImplementedException("timeEnd");

    void ConsoleContract.timeEnd(object? label)
        => throw CreateNotImplementedException("timeEnd");

    void ConsoleContract.timeLog()
        => throw CreateNotImplementedException("timeLog");

    void ConsoleContract.timeLog(object? label, params object?[] data)
        => throw CreateNotImplementedException("timeLog");

    void ConsoleContract.trace()
        => throw CreateNotImplementedException("trace");

    void ConsoleContract.trace(object? message, params object?[] args)
        => throw CreateNotImplementedException("trace");

    void ConsoleContract.warn()
        => _ = InvokeContractWarn();

    void ConsoleContract.warn(object? data, params object?[] args)
        => _ = InvokeContractWarn(data!, args!);

    void ConsoleContract.profile()
        => throw CreateNotImplementedException("profile");

    void ConsoleContract.profile(object? label)
        => throw CreateNotImplementedException("profile");

    void ConsoleContract.profileEnd()
        => throw CreateNotImplementedException("profileEnd");

    void ConsoleContract.profileEnd(object? label)
        => throw CreateNotImplementedException("profileEnd");

    void ConsoleContract.timeStamp()
        => throw CreateNotImplementedException("timeStamp");

    void ConsoleContract.timeStamp(object? label)
        => throw CreateNotImplementedException("timeStamp");

    private static global::System.NotImplementedException CreateNotImplementedException(string memberName)
        => new($"The intrinsic node:console module does not implement 'console.{memberName}'.");
}
