// <auto-generated />
// Generated from the official Node.js 24.18.1 crypto API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/crypto.json
// SHA-256: 34d332169d5a3915ce9f8ad3becd4a1fba34fac7dd487bb7b5a4fc99a01d207c

#nullable enable
#pragma warning disable CS0618

using CryptoContract = Jroc.Runtime.Node.Contracts.ICryptoModule;

namespace JavaScriptRuntime.Node;

public sealed partial class Crypto : CryptoContract
{
    object? CryptoContract.constants
        => throw CreateNotImplementedException("constants");

    object? CryptoContract.subtle
        => subtle;

    object? CryptoContract.webcrypto
        => webcrypto;

    double CryptoContract.fips
    {
        get => throw CreateNotImplementedException("fips");
        set => throw CreateNotImplementedException("fips");
    }

    object? CryptoContract.Certificate
        => throw CreateNotImplementedException("Certificate");

    object? CryptoContract.Cipheriv
        => throw CreateNotImplementedException("Cipheriv");

    object? CryptoContract.Decipheriv
        => throw CreateNotImplementedException("Decipheriv");

    object? CryptoContract.DiffieHellman
        => throw CreateNotImplementedException("DiffieHellman");

    object? CryptoContract.DiffieHellmanGroup
        => throw CreateNotImplementedException("DiffieHellmanGroup");

    object? CryptoContract.ECDH
        => throw CreateNotImplementedException("ECDH");

    object? CryptoContract.Hash
        => throw CreateNotImplementedException("Hash");

    object? CryptoContract.Hmac
        => throw CreateNotImplementedException("Hmac");

    object? CryptoContract.KeyObject
        => throw CreateNotImplementedException("KeyObject");

    object? CryptoContract.Sign
        => throw CreateNotImplementedException("Sign");

    object? CryptoContract.Verify
        => throw CreateNotImplementedException("Verify");

    object? CryptoContract.X509Certificate
        => throw CreateNotImplementedException("X509Certificate");

    void CryptoContract.argon2(string algorithm, object? parameters, global::System.Delegate callback)
        => throw CreateNotImplementedException("argon2");

    global::JavaScriptRuntime.Node.Buffer CryptoContract.argon2Sync(string algorithm, object? parameters)
        => throw CreateNotImplementedException("argon2Sync");

    void CryptoContract.checkPrime(object? candidate, global::System.Delegate callback)
        => throw CreateNotImplementedException("checkPrime");

    void CryptoContract.checkPrime(object? candidate, object? options, global::System.Delegate callback)
        => throw CreateNotImplementedException("checkPrime");

    bool CryptoContract.checkPrimeSync(object? candidate)
        => throw CreateNotImplementedException("checkPrimeSync");

    bool CryptoContract.checkPrimeSync(object? candidate, object? options)
        => throw CreateNotImplementedException("checkPrimeSync");

    object? CryptoContract.createCipheriv(string algorithm, object? key, object? iv)
        => throw CreateNotImplementedException("createCipheriv");

    object? CryptoContract.createCipheriv(string algorithm, object? key, object? iv, object? options)
        => throw CreateNotImplementedException("createCipheriv");

    object? CryptoContract.createDecipheriv(string algorithm, object? key, object? iv)
        => throw CreateNotImplementedException("createDecipheriv");

    object? CryptoContract.createDecipheriv(string algorithm, object? key, object? iv, object? options)
        => throw CreateNotImplementedException("createDecipheriv");

    object? CryptoContract.createDiffieHellman(object? prime)
        => throw CreateNotImplementedException("createDiffieHellman");

    object? CryptoContract.createDiffieHellman(object? prime, object? generatorEncoding)
        => throw CreateNotImplementedException("createDiffieHellman");

    object? CryptoContract.createDiffieHellman(object? prime, object? generator, object? generatorEncoding)
        => throw CreateNotImplementedException("createDiffieHellman");

    object? CryptoContract.createDiffieHellman(object? prime, object? primeEncoding, object? generator, object? generatorEncoding)
        => throw CreateNotImplementedException("createDiffieHellman");

    object? CryptoContract.createDiffieHellman(double primeLength)
        => throw CreateNotImplementedException("createDiffieHellman");

    object? CryptoContract.createDiffieHellman(double primeLength, object? generator)
        => throw CreateNotImplementedException("createDiffieHellman");

    object? CryptoContract.createDiffieHellmanGroup(string name)
        => throw CreateNotImplementedException("createDiffieHellmanGroup");

    object? CryptoContract.createECDH(string curveName)
        => throw CreateNotImplementedException("createECDH");

    object? CryptoContract.createHash(string algorithm)
        => createHash(algorithm!);

    object? CryptoContract.createHash(string algorithm, object? options)
        => createHash(algorithm!);

    object? CryptoContract.createHmac(string algorithm, object? key)
        => createHmac(algorithm!, key!);

    object? CryptoContract.createHmac(string algorithm, object? key, object? options)
        => createHmac(algorithm!, key!);

    object? CryptoContract.createPrivateKey(object? key)
        => throw CreateNotImplementedException("createPrivateKey");

    object? CryptoContract.createPublicKey(object? key)
        => throw CreateNotImplementedException("createPublicKey");

    object? CryptoContract.createSecretKey(object? key)
        => throw CreateNotImplementedException("createSecretKey");

    object? CryptoContract.createSecretKey(object? key, object? encoding)
        => throw CreateNotImplementedException("createSecretKey");

    object? CryptoContract.createSign(string algorithm)
        => throw CreateNotImplementedException("createSign");

    object? CryptoContract.createSign(string algorithm, object? options)
        => throw CreateNotImplementedException("createSign");

    object? CryptoContract.createVerify(string algorithm)
        => throw CreateNotImplementedException("createVerify");

    object? CryptoContract.createVerify(string algorithm, object? options)
        => throw CreateNotImplementedException("createVerify");

    void CryptoContract.generateKey(string type, object? options, global::System.Delegate callback)
        => throw CreateNotImplementedException("generateKey");

    void CryptoContract.generateKeyPair(string type, object? options, global::System.Delegate callback)
        => throw CreateNotImplementedException("generateKeyPair");

    object? CryptoContract.generateKeyPairSync(string type, object? options)
        => throw CreateNotImplementedException("generateKeyPairSync");

    object? CryptoContract.generateKeySync(string type, object? options)
        => throw CreateNotImplementedException("generateKeySync");

    void CryptoContract.generatePrime(double size, global::System.Delegate callback)
        => throw CreateNotImplementedException("generatePrime");

    void CryptoContract.generatePrime(double size, object? options, global::System.Delegate callback)
        => throw CreateNotImplementedException("generatePrime");

    object? CryptoContract.generatePrimeSync(double size)
        => throw CreateNotImplementedException("generatePrimeSync");

    object? CryptoContract.generatePrimeSync(double size, object? options)
        => throw CreateNotImplementedException("generatePrimeSync");

    object? CryptoContract.getCipherInfo(object? nameOrNid)
        => throw CreateNotImplementedException("getCipherInfo");

    object? CryptoContract.getCipherInfo(object? nameOrNid, object? options)
        => throw CreateNotImplementedException("getCipherInfo");

    global::JavaScriptRuntime.IJavaScriptArray CryptoContract.getCiphers()
        => throw CreateNotImplementedException("getCiphers");

    global::JavaScriptRuntime.IJavaScriptArray CryptoContract.getCurves()
        => throw CreateNotImplementedException("getCurves");

    object? CryptoContract.getDiffieHellman(string groupName)
        => throw CreateNotImplementedException("getDiffieHellman");

    double CryptoContract.getFips()
        => throw CreateNotImplementedException("getFips");

    global::JavaScriptRuntime.IJavaScriptArray CryptoContract.getHashes()
        => throw CreateNotImplementedException("getHashes");

    object? CryptoContract.getRandomValues(object? typedArray)
        => getRandomValues(typedArray!);

    object? CryptoContract.hash(object? algorithm, object? data)
        => throw CreateNotImplementedException("hash");

    object? CryptoContract.hash(object? algorithm, object? data, object? options)
        => throw CreateNotImplementedException("hash");

    void CryptoContract.hkdf(string digest, object? ikm, object? salt, object? info, double keylen, global::System.Delegate callback)
        => throw CreateNotImplementedException("hkdf");

    global::JavaScriptRuntime.ArrayBuffer CryptoContract.hkdfSync(string digest, object? ikm, object? salt, object? info, double keylen)
        => throw CreateNotImplementedException("hkdfSync");

    void CryptoContract.pbkdf2(object? password, object? salt, double iterations, double keylen, string digest, global::System.Delegate callback)
        => throw CreateNotImplementedException("pbkdf2");

    global::JavaScriptRuntime.Node.Buffer CryptoContract.pbkdf2Sync(object? password, object? salt, double iterations, double keylen, string digest)
        => (global::JavaScriptRuntime.Node.Buffer)pbkdf2Sync(password!, salt!, iterations!, keylen!, digest!)!;

    global::JavaScriptRuntime.Node.Buffer CryptoContract.privateDecrypt(object? privateKey, object? buffer)
        => throw CreateNotImplementedException("privateDecrypt");

    global::JavaScriptRuntime.Node.Buffer CryptoContract.privateEncrypt(object? privateKey, object? buffer)
        => throw CreateNotImplementedException("privateEncrypt");

    global::JavaScriptRuntime.Node.Buffer CryptoContract.publicDecrypt(object? key, object? buffer)
        => throw CreateNotImplementedException("publicDecrypt");

    global::JavaScriptRuntime.Node.Buffer CryptoContract.publicEncrypt(object? key, object? buffer)
        => throw CreateNotImplementedException("publicEncrypt");

    void CryptoContract.randomFill(object? buffer, global::System.Delegate callback)
        => throw CreateNotImplementedException("randomFill");

    void CryptoContract.randomFill(object? buffer, object? size, global::System.Delegate callback)
        => throw CreateNotImplementedException("randomFill");

    void CryptoContract.randomFill(object? buffer, object? offset, object? size, global::System.Delegate callback)
        => throw CreateNotImplementedException("randomFill");

    object? CryptoContract.randomFillSync(object? buffer)
        => throw CreateNotImplementedException("randomFillSync");

    object? CryptoContract.randomFillSync(object? buffer, object? size)
        => throw CreateNotImplementedException("randomFillSync");

    object? CryptoContract.randomFillSync(object? buffer, object? offset, object? size)
        => throw CreateNotImplementedException("randomFillSync");

    string CryptoContract.randomUUID()
        => throw CreateNotImplementedException("randomUUID");

    string CryptoContract.randomUUID(object? options)
        => throw CreateNotImplementedException("randomUUID");

    string CryptoContract.randomUUIDv7()
        => throw CreateNotImplementedException("randomUUIDv7");

    string CryptoContract.randomUUIDv7(object? options)
        => throw CreateNotImplementedException("randomUUIDv7");

    void CryptoContract.scrypt(object? password, object? salt, double keylen, global::System.Delegate callback)
        => throw CreateNotImplementedException("scrypt");

    void CryptoContract.scrypt(object? password, object? salt, double keylen, object? options, global::System.Delegate callback)
        => throw CreateNotImplementedException("scrypt");

    global::JavaScriptRuntime.Node.Buffer CryptoContract.scryptSync(object? password, object? salt, double keylen)
        => throw CreateNotImplementedException("scryptSync");

    global::JavaScriptRuntime.Node.Buffer CryptoContract.scryptSync(object? password, object? salt, double keylen, object? options)
        => throw CreateNotImplementedException("scryptSync");

    object? CryptoContract.secureHeapUsed()
        => throw CreateNotImplementedException("secureHeapUsed");

    void CryptoContract.setEngine(string engine)
        => throw CreateNotImplementedException("setEngine");

    void CryptoContract.setEngine(string engine, object? flags)
        => throw CreateNotImplementedException("setEngine");

    void CryptoContract.setFips(bool @bool)
        => throw CreateNotImplementedException("setFips");

    bool CryptoContract.timingSafeEqual(object? a, object? b)
        => throw CreateNotImplementedException("timingSafeEqual");

    global::JavaScriptRuntime.Node.Buffer CryptoContract.decapsulate(object? key, object? ciphertext)
        => throw CreateNotImplementedException("decapsulate");

    void CryptoContract.decapsulate(object? key, object? ciphertext, global::System.Delegate callback)
        => throw CreateNotImplementedException("decapsulate");

    global::JavaScriptRuntime.Node.Buffer CryptoContract.diffieHellman(object? options)
        => throw CreateNotImplementedException("diffieHellman");

    void CryptoContract.diffieHellman(object? options, global::System.Delegate callback)
        => throw CreateNotImplementedException("diffieHellman");

    object? CryptoContract.encapsulate(object? key)
        => throw CreateNotImplementedException("encapsulate");

    void CryptoContract.encapsulate(object? key, global::System.Delegate callback)
        => throw CreateNotImplementedException("encapsulate");

    global::JavaScriptRuntime.Node.Buffer CryptoContract.randomBytes(double size)
        => (global::JavaScriptRuntime.Node.Buffer)randomBytes(size!)!;

    void CryptoContract.randomBytes(double size, global::System.Delegate callback)
        => throw CreateNotImplementedException("randomBytes");

    double CryptoContract.randomInt(double max)
        => throw CreateNotImplementedException("randomInt");

    void CryptoContract.randomInt(double max, global::System.Delegate callback)
        => throw CreateNotImplementedException("randomInt");

    double CryptoContract.randomInt(double min, double max)
        => throw CreateNotImplementedException("randomInt");

    void CryptoContract.randomInt(double min, double max, global::System.Delegate callback)
        => throw CreateNotImplementedException("randomInt");

    global::JavaScriptRuntime.Node.Buffer CryptoContract.sign(object? algorithm, object? data, object? key)
        => throw CreateNotImplementedException("sign");

    void CryptoContract.sign(object? algorithm, object? data, object? key, global::System.Delegate callback)
        => throw CreateNotImplementedException("sign");

    bool CryptoContract.verify(object? algorithm, object? data, object? key, object? signature)
        => throw CreateNotImplementedException("verify");

    void CryptoContract.verify(object? algorithm, object? data, object? key, object? signature, global::System.Delegate callback)
        => throw CreateNotImplementedException("verify");

    private static global::System.NotImplementedException CreateNotImplementedException(string memberName)
        => new($"The intrinsic node:crypto module does not implement 'crypto.{memberName}'.");
}
