// <auto-generated />
// Generated from the official Node.js 24.18.1 dns API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/dns.json
// SHA-256: bc24b3f753476a2c1fe244de2948030777da9d4096d064fbdccc11ae00fc7380

#nullable enable
#pragma warning disable CS0618

using DnsContract = Jroc.Runtime.Node.Contracts.IDnsModule;

namespace JavaScriptRuntime.Node;

public sealed partial class Dns : DnsContract
{
    global::Jroc.Runtime.Node.Contracts.IResolver DnsContract.Resolver
        => throw CreateNotImplementedException("Resolver");

    double DnsContract.ADDRCONFIG
        => throw CreateNotImplementedException("ADDRCONFIG");

    double DnsContract.ALL
        => throw CreateNotImplementedException("ALL");

    double DnsContract.V4MAPPED
        => throw CreateNotImplementedException("V4MAPPED");

    double DnsContract.NODATA
        => throw CreateNotImplementedException("NODATA");

    double DnsContract.FORMERR
        => throw CreateNotImplementedException("FORMERR");

    double DnsContract.SERVFAIL
        => throw CreateNotImplementedException("SERVFAIL");

    double DnsContract.NOTFOUND
        => throw CreateNotImplementedException("NOTFOUND");

    double DnsContract.NOTIMP
        => throw CreateNotImplementedException("NOTIMP");

    double DnsContract.REFUSED
        => throw CreateNotImplementedException("REFUSED");

    double DnsContract.BADQUERY
        => throw CreateNotImplementedException("BADQUERY");

    double DnsContract.BADNAME
        => throw CreateNotImplementedException("BADNAME");

    double DnsContract.BADFAMILY
        => throw CreateNotImplementedException("BADFAMILY");

    double DnsContract.BADRESP
        => throw CreateNotImplementedException("BADRESP");

    double DnsContract.CONNREFUSED
        => throw CreateNotImplementedException("CONNREFUSED");

    double DnsContract.TIMEOUT
        => throw CreateNotImplementedException("TIMEOUT");

    double DnsContract.EOF
        => throw CreateNotImplementedException("EOF");

    double DnsContract.FILE
        => throw CreateNotImplementedException("FILE");

    double DnsContract.NOMEM
        => throw CreateNotImplementedException("NOMEM");

    double DnsContract.DESTRUCTION
        => throw CreateNotImplementedException("DESTRUCTION");

    double DnsContract.BADSTR
        => throw CreateNotImplementedException("BADSTR");

    double DnsContract.BADFLAGS
        => throw CreateNotImplementedException("BADFLAGS");

    double DnsContract.NONAME
        => throw CreateNotImplementedException("NONAME");

    double DnsContract.BADHINTS
        => throw CreateNotImplementedException("BADHINTS");

    double DnsContract.NOTINITIALIZED
        => throw CreateNotImplementedException("NOTINITIALIZED");

    double DnsContract.LOADIPHLPAPI
        => throw CreateNotImplementedException("LOADIPHLPAPI");

    double DnsContract.ADDRGETNETWORKPARAMS
        => throw CreateNotImplementedException("ADDRGETNETWORKPARAMS");

    double DnsContract.CANCELLED
        => throw CreateNotImplementedException("CANCELLED");

    object? DnsContract.promises
        => throw CreateNotImplementedException("promises");

    global::JavaScriptRuntime.IJavaScriptArray DnsContract.getServers()
        => throw CreateNotImplementedException("getServers");

    void DnsContract.lookupService(string address, double port, global::System.Delegate callback)
        => throw CreateNotImplementedException("lookupService");

    void DnsContract.resolveAny(string hostname, global::System.Delegate callback)
        => throw CreateNotImplementedException("resolveAny");

    void DnsContract.resolveCname(string hostname, global::System.Delegate callback)
        => throw CreateNotImplementedException("resolveCname");

    void DnsContract.resolveCaa(string hostname, global::System.Delegate callback)
        => throw CreateNotImplementedException("resolveCaa");

    void DnsContract.resolveMx(string hostname, global::System.Delegate callback)
        => throw CreateNotImplementedException("resolveMx");

    void DnsContract.resolveNaptr(string hostname, global::System.Delegate callback)
        => throw CreateNotImplementedException("resolveNaptr");

    void DnsContract.resolveNs(string hostname, global::System.Delegate callback)
        => throw CreateNotImplementedException("resolveNs");

    void DnsContract.resolvePtr(string hostname, global::System.Delegate callback)
        => throw CreateNotImplementedException("resolvePtr");

    void DnsContract.resolveSoa(string hostname, global::System.Delegate callback)
        => throw CreateNotImplementedException("resolveSoa");

    void DnsContract.resolveSrv(string hostname, global::System.Delegate callback)
        => throw CreateNotImplementedException("resolveSrv");

    void DnsContract.resolveTxt(string hostname, global::System.Delegate callback)
        => throw CreateNotImplementedException("resolveTxt");

    void DnsContract.reverse(string ip, global::System.Delegate callback)
        => throw CreateNotImplementedException("reverse");

    void DnsContract.setDefaultResultOrder(string order)
        => setDefaultResultOrder(order!);

    void DnsContract.setServers(global::JavaScriptRuntime.IJavaScriptArray servers)
        => throw CreateNotImplementedException("setServers");

    void DnsContract.lookup(string hostname, global::System.Delegate callback)
        => _ = lookup(new object[] { hostname!, callback! });

    void DnsContract.lookup(string hostname, object? options, global::System.Delegate callback)
        => _ = lookup(new object[] { hostname!, options!, callback! });

    void DnsContract.resolve(string hostname, global::System.Delegate callback)
        => throw CreateNotImplementedException("resolve");

    void DnsContract.resolve(string hostname, string rrtype, global::System.Delegate callback)
        => throw CreateNotImplementedException("resolve");

    void DnsContract.resolve4(string hostname, global::System.Delegate callback)
        => throw CreateNotImplementedException("resolve4");

    void DnsContract.resolve4(string hostname, object? options, global::System.Delegate callback)
        => throw CreateNotImplementedException("resolve4");

    void DnsContract.resolve6(string hostname, global::System.Delegate callback)
        => throw CreateNotImplementedException("resolve6");

    void DnsContract.resolve6(string hostname, object? options, global::System.Delegate callback)
        => throw CreateNotImplementedException("resolve6");

    void DnsContract.resolveTlsa(string hostname, global::System.Delegate callback)
        => throw CreateNotImplementedException("resolveTlsa");

    string DnsContract.getDefaultResultOrder()
        => global::JavaScriptRuntime.DotNet2JSConversions.ToString(getDefaultResultOrder());

    private static global::System.NotImplementedException CreateNotImplementedException(string memberName)
        => new($"The intrinsic node:dns module does not implement 'dns.{memberName}'.");
}
