// <auto-generated />
// Generated from the official Node.js 24.18.1 fs API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/fs.json
// SHA-256: 3145e3751afc28b868f9b481788a081fd87adf3215aa638f850fcb52d636ab6b

#nullable enable
#pragma warning disable CS0618

using NestedContract = Jroc.Runtime.Node.Contracts.IFsFileHandle;

namespace JavaScriptRuntime.Node;

public sealed partial class FileHandle : NestedContract
{
    double NestedContract.fd
        => (double)fd!;
    global::JavaScriptRuntime.IJavaScriptPromise NestedContract.appendFile(object? data)
        => throw CreateNotImplementedException("appendFile");
    global::JavaScriptRuntime.IJavaScriptPromise NestedContract.appendFile(object? data, object? options)
        => throw CreateNotImplementedException("appendFile");
    global::JavaScriptRuntime.IJavaScriptPromise NestedContract.chmod(double mode)
        => throw CreateNotImplementedException("chmod");
    global::JavaScriptRuntime.IJavaScriptPromise NestedContract.chown(double uid, double gid)
        => throw CreateNotImplementedException("chown");
    global::JavaScriptRuntime.IJavaScriptPromise NestedContract.close()
        => (global::JavaScriptRuntime.IJavaScriptPromise)close()!;
    object? NestedContract.createReadStream()
        => throw CreateNotImplementedException("createReadStream");
    object? NestedContract.createReadStream(object? options)
        => throw CreateNotImplementedException("createReadStream");
    object? NestedContract.createWriteStream()
        => throw CreateNotImplementedException("createWriteStream");
    object? NestedContract.createWriteStream(object? options)
        => throw CreateNotImplementedException("createWriteStream");
    global::JavaScriptRuntime.IJavaScriptPromise NestedContract.datasync()
        => throw CreateNotImplementedException("datasync");
    global::JavaScriptRuntime.IJavaScriptPromise NestedContract.read(object? buffer, double offset, double length, object? position)
        => throw CreateNotImplementedException("read");
    global::JavaScriptRuntime.IJavaScriptPromise NestedContract.read()
        => throw CreateNotImplementedException("read");
    global::JavaScriptRuntime.IJavaScriptPromise NestedContract.read(object? options)
        => throw CreateNotImplementedException("read");
    global::JavaScriptRuntime.IJavaScriptPromise NestedContract.read(object? buffer, object? options)
        => throw CreateNotImplementedException("read");
    object? NestedContract.readableWebStream()
        => throw CreateNotImplementedException("readableWebStream");
    object? NestedContract.readableWebStream(object? options)
        => throw CreateNotImplementedException("readableWebStream");
    global::JavaScriptRuntime.IJavaScriptPromise NestedContract.readFile(object? options)
        => throw CreateNotImplementedException("readFile");
    object? NestedContract.readLines()
        => throw CreateNotImplementedException("readLines");
    object? NestedContract.readLines(object? options)
        => throw CreateNotImplementedException("readLines");
    global::JavaScriptRuntime.IJavaScriptPromise NestedContract.readv(global::JavaScriptRuntime.IJavaScriptArray buffers)
        => throw CreateNotImplementedException("readv");
    global::JavaScriptRuntime.IJavaScriptPromise NestedContract.readv(global::JavaScriptRuntime.IJavaScriptArray buffers, object? position)
        => throw CreateNotImplementedException("readv");
    global::JavaScriptRuntime.IJavaScriptPromise NestedContract.stat()
        => throw CreateNotImplementedException("stat");
    global::JavaScriptRuntime.IJavaScriptPromise NestedContract.stat(object? options)
        => throw CreateNotImplementedException("stat");
    global::JavaScriptRuntime.IJavaScriptPromise NestedContract.sync()
        => throw CreateNotImplementedException("sync");
    global::JavaScriptRuntime.IJavaScriptPromise NestedContract.truncate(double len)
        => throw CreateNotImplementedException("truncate");
    global::JavaScriptRuntime.IJavaScriptPromise NestedContract.utimes(object? atime, object? mtime)
        => throw CreateNotImplementedException("utimes");
    global::JavaScriptRuntime.IJavaScriptPromise NestedContract.write(object? buffer, double offset)
        => throw CreateNotImplementedException("write");
    global::JavaScriptRuntime.IJavaScriptPromise NestedContract.write(object? buffer, double offset, object? length)
        => throw CreateNotImplementedException("write");
    global::JavaScriptRuntime.IJavaScriptPromise NestedContract.write(object? buffer, double offset, object? length, object? position)
        => throw CreateNotImplementedException("write");
    global::JavaScriptRuntime.IJavaScriptPromise NestedContract.write(object? buffer)
        => throw CreateNotImplementedException("write");
    global::JavaScriptRuntime.IJavaScriptPromise NestedContract.write(object? buffer, object? options)
        => throw CreateNotImplementedException("write");
    global::JavaScriptRuntime.IJavaScriptPromise NestedContract.write(string @string)
        => throw CreateNotImplementedException("write");
    global::JavaScriptRuntime.IJavaScriptPromise NestedContract.write(string @string, object? position)
        => throw CreateNotImplementedException("write");
    global::JavaScriptRuntime.IJavaScriptPromise NestedContract.write(string @string, object? position, object? encoding)
        => throw CreateNotImplementedException("write");
    global::JavaScriptRuntime.IJavaScriptPromise NestedContract.writeFile(object? data, object? options)
        => throw CreateNotImplementedException("writeFile");
    global::JavaScriptRuntime.IJavaScriptPromise NestedContract.writev(global::JavaScriptRuntime.IJavaScriptArray buffers)
        => throw CreateNotImplementedException("writev");
    global::JavaScriptRuntime.IJavaScriptPromise NestedContract.writev(global::JavaScriptRuntime.IJavaScriptArray buffers, object? position)
        => throw CreateNotImplementedException("writev");
    void NestedContract.filehandle_SymbolAsyncDispose_()
        => throw CreateNotImplementedException("filehandle[Symbol.asyncDispose]");

    private static global::System.NotImplementedException CreateNotImplementedException(string memberName)
        => new($"The intrinsic node:fs.FileHandle contract does not implement 'filehandle.{memberName}'.");
}
