// <auto-generated />
// Generated from the official Node.js 24.18.1 fs API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/fs.json
// SHA-256: 3145e3751afc28b868f9b481788a081fd87adf3215aa638f850fcb52d636ab6b

#nullable enable
#pragma warning disable CS0618

using FsContract = Jroc.Runtime.Node.Contracts.IFsModule;

namespace JavaScriptRuntime.Node;

public sealed partial class FS : FsContract
{
    object? FsContract.constants
        => constants;

    object? FsContract.promises
        => promises;

    double FsContract.F_OK
        => throw CreateNotImplementedException("F_OK");

    double FsContract.R_OK
        => throw CreateNotImplementedException("R_OK");

    double FsContract.W_OK
        => throw CreateNotImplementedException("W_OK");

    double FsContract.X_OK
        => throw CreateNotImplementedException("X_OK");

    void FsContract.access(object? path, global::System.Delegate callback)
        => _ = InvokeContractMember("access", [path!, callback!]);

    void FsContract.access(object? path, object? mode, global::System.Delegate callback)
        => _ = InvokeContractMember("access", [path!, mode!, callback!]);

    void FsContract.appendFile(object? path, object? data, global::System.Delegate callback)
        => _ = InvokeContractMember("appendFile", [path!, data!, callback!]);

    void FsContract.appendFile(object? path, object? data, object? options, global::System.Delegate callback)
        => _ = InvokeContractMember("appendFile", [path!, data!, options!, callback!]);

    void FsContract.chmod(object? path, object? mode, global::System.Delegate callback)
        => throw CreateNotImplementedException("chmod");

    void FsContract.chown(object? path, double uid, double gid, global::System.Delegate callback)
        => throw CreateNotImplementedException("chown");

    void FsContract.close(double fd)
        => throw CreateNotImplementedException("close");

    void FsContract.close(double fd, object? callback)
        => throw CreateNotImplementedException("close");

    void FsContract.copyFile(object? src, object? dest, global::System.Delegate callback)
        => _ = InvokeContractMember("copyFile", [src!, dest!, callback!]);

    void FsContract.copyFile(object? src, object? dest, object? mode, global::System.Delegate callback)
        => _ = InvokeContractMember("copyFile", [src!, dest!, mode!, callback!]);

    void FsContract.cp(object? src, object? dest, global::System.Delegate callback)
        => throw CreateNotImplementedException("cp");

    void FsContract.cp(object? src, object? dest, object? options, global::System.Delegate callback)
        => throw CreateNotImplementedException("cp");

    object? FsContract.createReadStream(object? path)
        => InvokeContractMember("createReadStream", [path!]);

    object? FsContract.createReadStream(object? path, object? options)
        => InvokeContractMember("createReadStream", [path!, options!]);

    object? FsContract.createWriteStream(object? path)
        => InvokeContractMember("createWriteStream", [path!]);

    object? FsContract.createWriteStream(object? path, object? options)
        => InvokeContractMember("createWriteStream", [path!, options!]);

    void FsContract.exists(object? path, global::System.Delegate callback)
        => throw CreateNotImplementedException("exists");

    void FsContract.fchmod(double fd, object? mode, global::System.Delegate callback)
        => throw CreateNotImplementedException("fchmod");

    void FsContract.fchown(double fd, double uid, double gid, global::System.Delegate callback)
        => throw CreateNotImplementedException("fchown");

    void FsContract.fdatasync(double fd, global::System.Delegate callback)
        => throw CreateNotImplementedException("fdatasync");

    void FsContract.fstat(double fd, global::System.Delegate callback)
        => throw CreateNotImplementedException("fstat");

    void FsContract.fstat(double fd, object? options, global::System.Delegate callback)
        => throw CreateNotImplementedException("fstat");

    void FsContract.fsync(double fd, global::System.Delegate callback)
        => throw CreateNotImplementedException("fsync");

    void FsContract.ftruncate(double fd, global::System.Delegate callback)
        => throw CreateNotImplementedException("ftruncate");

    void FsContract.ftruncate(double fd, object? len, global::System.Delegate callback)
        => throw CreateNotImplementedException("ftruncate");

    void FsContract.futimes(double fd, object? atime, object? mtime, global::System.Delegate callback)
        => throw CreateNotImplementedException("futimes");

    void FsContract.glob(object? pattern, global::System.Delegate callback)
        => throw CreateNotImplementedException("glob");

    void FsContract.glob(object? pattern, object? options, global::System.Delegate callback)
        => throw CreateNotImplementedException("glob");

    void FsContract.lchmod(object? path, double mode, global::System.Delegate callback)
        => throw CreateNotImplementedException("lchmod");

    void FsContract.lchown(object? path, double uid, double gid, global::System.Delegate callback)
        => throw CreateNotImplementedException("lchown");

    void FsContract.lutimes(object? path, object? atime, object? mtime, global::System.Delegate callback)
        => throw CreateNotImplementedException("lutimes");

    void FsContract.link(object? existingPath, object? newPath, global::System.Delegate callback)
        => throw CreateNotImplementedException("link");

    void FsContract.lstat(object? path, global::System.Delegate callback)
        => throw CreateNotImplementedException("lstat");

    void FsContract.lstat(object? path, object? options, global::System.Delegate callback)
        => throw CreateNotImplementedException("lstat");

    void FsContract.mkdir(object? path, global::System.Delegate callback)
        => _ = InvokeContractMember("mkdir", [path!, callback!]);

    void FsContract.mkdir(object? path, object? options, global::System.Delegate callback)
        => _ = InvokeContractMember("mkdir", [path!, options!, callback!]);

    void FsContract.mkdtemp(object? prefix, global::System.Delegate callback)
        => throw CreateNotImplementedException("mkdtemp");

    void FsContract.mkdtemp(object? prefix, object? options, global::System.Delegate callback)
        => throw CreateNotImplementedException("mkdtemp");

    void FsContract.open(object? path, global::System.Delegate callback)
        => _ = InvokeContractMember("open", [path!, callback!]);

    void FsContract.open(object? path, object? flags, global::System.Delegate callback)
        => _ = InvokeContractMember("open", [path!, flags!, callback!]);

    void FsContract.open(object? path, object? flags, object? mode, global::System.Delegate callback)
        => _ = InvokeContractMember("open", [path!, flags!, mode!, callback!]);

    global::JavaScriptRuntime.Promise FsContract.openAsBlob(object? path)
        => throw CreateNotImplementedException("openAsBlob");

    global::JavaScriptRuntime.Promise FsContract.openAsBlob(object? path, object? options)
        => throw CreateNotImplementedException("openAsBlob");

    void FsContract.opendir(object? path, global::System.Delegate callback)
        => throw CreateNotImplementedException("opendir");

    void FsContract.opendir(object? path, object? options, global::System.Delegate callback)
        => throw CreateNotImplementedException("opendir");

    void FsContract.read(double fd, object? buffer, double offset, double length, object? position, global::System.Delegate callback)
        => throw CreateNotImplementedException("read");

    void FsContract.read(double fd, global::System.Delegate callback)
        => throw CreateNotImplementedException("read");

    void FsContract.read(double fd, object? options, global::System.Delegate callback)
        => throw CreateNotImplementedException("read");

    void FsContract.read(double fd, object? buffer, object? options, global::System.Delegate callback)
        => throw CreateNotImplementedException("read");

    void FsContract.readdir(object? path, global::System.Delegate callback)
        => _ = InvokeContractMember("readdir", [path!, callback!]);

    void FsContract.readdir(object? path, object? options, global::System.Delegate callback)
        => _ = InvokeContractMember("readdir", [path!, options!, callback!]);

    void FsContract.readFile(object? path, global::System.Delegate callback)
        => _ = InvokeContractMember("readFile", [path!, callback!]);

    void FsContract.readFile(object? path, object? options, global::System.Delegate callback)
        => _ = InvokeContractMember("readFile", [path!, options!, callback!]);

    void FsContract.readlink(object? path, global::System.Delegate callback)
        => throw CreateNotImplementedException("readlink");

    void FsContract.readlink(object? path, object? options, global::System.Delegate callback)
        => throw CreateNotImplementedException("readlink");

    void FsContract.readv(double fd, global::JavaScriptRuntime.IJavaScriptArray buffers, global::System.Delegate callback)
        => throw CreateNotImplementedException("readv");

    void FsContract.readv(double fd, global::JavaScriptRuntime.IJavaScriptArray buffers, object? position, global::System.Delegate callback)
        => throw CreateNotImplementedException("readv");

    void FsContract.realpath(object? path, global::System.Delegate callback)
        => _ = InvokeContractMember("realpath", [path!, callback!]);

    void FsContract.realpath(object? path, object? options, global::System.Delegate callback)
        => _ = InvokeContractMember("realpath", [path!, options!, callback!]);

    void FsContract.realpathNative(object? path, global::System.Delegate callback)
        => throw CreateNotImplementedException("realpath.native");

    void FsContract.realpathNative(object? path, object? options, global::System.Delegate callback)
        => throw CreateNotImplementedException("realpath.native");

    void FsContract.rename(object? oldPath, object? newPath, global::System.Delegate callback)
        => _ = InvokeContractMember("rename", [oldPath!, newPath!, callback!]);

    void FsContract.rmdir(object? path, global::System.Delegate callback)
        => throw CreateNotImplementedException("rmdir");

    void FsContract.rmdir(object? path, object? options, global::System.Delegate callback)
        => throw CreateNotImplementedException("rmdir");

    void FsContract.rm(object? path, global::System.Delegate callback)
        => _ = InvokeContractMember("rm", [path!, callback!]);

    void FsContract.rm(object? path, object? options, global::System.Delegate callback)
        => _ = InvokeContractMember("rm", [path!, options!, callback!]);

    void FsContract.stat(object? path, global::System.Delegate callback)
        => _ = InvokeContractMember("stat", [path!, callback!]);

    void FsContract.stat(object? path, object? options, global::System.Delegate callback)
        => _ = InvokeContractMember("stat", [path!, options!, callback!]);

    void FsContract.statfs(object? path, global::System.Delegate callback)
        => throw CreateNotImplementedException("statfs");

    void FsContract.statfs(object? path, object? options, global::System.Delegate callback)
        => throw CreateNotImplementedException("statfs");

    void FsContract.symlink(object? target, object? path, global::System.Delegate callback)
        => throw CreateNotImplementedException("symlink");

    void FsContract.symlink(object? target, object? path, object? type, global::System.Delegate callback)
        => throw CreateNotImplementedException("symlink");

    void FsContract.truncate(object? path, global::System.Delegate callback)
        => throw CreateNotImplementedException("truncate");

    void FsContract.truncate(object? path, object? len, global::System.Delegate callback)
        => throw CreateNotImplementedException("truncate");

    void FsContract.unlink(object? path, global::System.Delegate callback)
        => _ = InvokeContractMember("unlink", [path!, callback!]);

    void FsContract.unwatchFile(object? filename)
        => throw CreateNotImplementedException("unwatchFile");

    void FsContract.unwatchFile(object? filename, object? listener)
        => throw CreateNotImplementedException("unwatchFile");

    void FsContract.utimes(object? path, object? atime, object? mtime, global::System.Delegate callback)
        => throw CreateNotImplementedException("utimes");

    object? FsContract.watch(object? filename)
        => throw CreateNotImplementedException("watch");

    object? FsContract.watch(object? filename, object? listener)
        => throw CreateNotImplementedException("watch");

    object? FsContract.watch(object? filename, object? options, object? listener)
        => throw CreateNotImplementedException("watch");

    object? FsContract.watchFile(object? filename, global::System.Delegate listener)
        => throw CreateNotImplementedException("watchFile");

    object? FsContract.watchFile(object? filename, object? options, global::System.Delegate listener)
        => throw CreateNotImplementedException("watchFile");

    void FsContract.write(double fd, object? buffer, double offset, global::System.Delegate callback)
        => throw CreateNotImplementedException("write");

    void FsContract.write(double fd, object? buffer, double offset, object? length, global::System.Delegate callback)
        => throw CreateNotImplementedException("write");

    void FsContract.write(double fd, object? buffer, double offset, object? length, object? position, global::System.Delegate callback)
        => throw CreateNotImplementedException("write");

    void FsContract.write(double fd, object? buffer, global::System.Delegate callback)
        => throw CreateNotImplementedException("write");

    void FsContract.write(double fd, object? buffer, object? options, global::System.Delegate callback)
        => throw CreateNotImplementedException("write");

    void FsContract.write(double fd, string @string, global::System.Delegate callback)
        => throw CreateNotImplementedException("write");

    void FsContract.write(double fd, string @string, object? position, global::System.Delegate callback)
        => throw CreateNotImplementedException("write");

    void FsContract.write(double fd, string @string, object? position, object? encoding, global::System.Delegate callback)
        => throw CreateNotImplementedException("write");

    void FsContract.writeFile(object? file, object? data, global::System.Delegate callback)
        => _ = InvokeContractMember("writeFile", [file!, data!, callback!]);

    void FsContract.writeFile(object? file, object? data, object? options, global::System.Delegate callback)
        => _ = InvokeContractMember("writeFile", [file!, data!, options!, callback!]);

    void FsContract.writev(double fd, global::JavaScriptRuntime.IJavaScriptArray buffers, global::System.Delegate callback)
        => throw CreateNotImplementedException("writev");

    void FsContract.writev(double fd, global::JavaScriptRuntime.IJavaScriptArray buffers, object? position, global::System.Delegate callback)
        => throw CreateNotImplementedException("writev");

    void FsContract.accessSync(object? path)
        => throw CreateNotImplementedException("accessSync");

    void FsContract.accessSync(object? path, object? mode)
        => throw CreateNotImplementedException("accessSync");

    void FsContract.appendFileSync(object? path, object? data)
        => throw CreateNotImplementedException("appendFileSync");

    void FsContract.appendFileSync(object? path, object? data, object? options)
        => throw CreateNotImplementedException("appendFileSync");

    void FsContract.chmodSync(object? path, object? mode)
        => throw CreateNotImplementedException("chmodSync");

    void FsContract.chownSync(object? path, double uid, double gid)
        => throw CreateNotImplementedException("chownSync");

    void FsContract.closeSync(double fd)
        => throw CreateNotImplementedException("closeSync");

    void FsContract.copyFileSync(object? src, object? dest)
        => throw CreateNotImplementedException("copyFileSync");

    void FsContract.copyFileSync(object? src, object? dest, object? mode)
        => throw CreateNotImplementedException("copyFileSync");

    void FsContract.cpSync(object? src, object? dest)
        => throw CreateNotImplementedException("cpSync");

    void FsContract.cpSync(object? src, object? dest, object? options)
        => throw CreateNotImplementedException("cpSync");

    bool FsContract.existsSync(object? path)
        => global::JavaScriptRuntime.TypeUtilities.ToBoolean(InvokeContractMember("existsSync", [path!]));

    void FsContract.fchmodSync(double fd, object? mode)
        => throw CreateNotImplementedException("fchmodSync");

    void FsContract.fchownSync(double fd, double uid, double gid)
        => throw CreateNotImplementedException("fchownSync");

    void FsContract.fdatasyncSync(double fd)
        => throw CreateNotImplementedException("fdatasyncSync");

    object? FsContract.fstatSync(double fd)
        => throw CreateNotImplementedException("fstatSync");

    object? FsContract.fstatSync(double fd, object? options)
        => throw CreateNotImplementedException("fstatSync");

    void FsContract.fsyncSync(double fd)
        => throw CreateNotImplementedException("fsyncSync");

    void FsContract.ftruncateSync(double fd)
        => throw CreateNotImplementedException("ftruncateSync");

    void FsContract.ftruncateSync(double fd, object? len)
        => throw CreateNotImplementedException("ftruncateSync");

    void FsContract.futimesSync(double fd, object? atime, object? mtime)
        => throw CreateNotImplementedException("futimesSync");

    global::JavaScriptRuntime.IJavaScriptArray FsContract.globSync(object? pattern)
        => throw CreateNotImplementedException("globSync");

    global::JavaScriptRuntime.IJavaScriptArray FsContract.globSync(object? pattern, object? options)
        => throw CreateNotImplementedException("globSync");

    void FsContract.lchmodSync(object? path, double mode)
        => throw CreateNotImplementedException("lchmodSync");

    void FsContract.lchownSync(object? path, double uid, double gid)
        => throw CreateNotImplementedException("lchownSync");

    void FsContract.lutimesSync(object? path, object? atime, object? mtime)
        => throw CreateNotImplementedException("lutimesSync");

    void FsContract.linkSync(object? existingPath, object? newPath)
        => throw CreateNotImplementedException("linkSync");

    object? FsContract.lstatSync(object? path)
        => throw CreateNotImplementedException("lstatSync");

    object? FsContract.lstatSync(object? path, object? options)
        => throw CreateNotImplementedException("lstatSync");

    object? FsContract.mkdirSync(object? path)
        => InvokeContractMember("mkdirSync", [path!]);

    object? FsContract.mkdirSync(object? path, object? options)
        => InvokeContractMember("mkdirSync", [path!, options!]);

    string FsContract.mkdtempSync(object? prefix)
        => throw CreateNotImplementedException("mkdtempSync");

    string FsContract.mkdtempSync(object? prefix, object? options)
        => throw CreateNotImplementedException("mkdtempSync");

    object? FsContract.mkdtempDisposableSync(object? prefix)
        => throw CreateNotImplementedException("mkdtempDisposableSync");

    object? FsContract.mkdtempDisposableSync(object? prefix, object? options)
        => throw CreateNotImplementedException("mkdtempDisposableSync");

    object? FsContract.opendirSync(object? path)
        => throw CreateNotImplementedException("opendirSync");

    object? FsContract.opendirSync(object? path, object? options)
        => throw CreateNotImplementedException("opendirSync");

    double FsContract.openSync(object? path)
        => throw CreateNotImplementedException("openSync");

    double FsContract.openSync(object? path, object? flags)
        => throw CreateNotImplementedException("openSync");

    double FsContract.openSync(object? path, object? flags, object? mode)
        => throw CreateNotImplementedException("openSync");

    global::JavaScriptRuntime.IJavaScriptArray FsContract.readdirSync(object? path)
        => (global::JavaScriptRuntime.IJavaScriptArray)InvokeContractMember("readdirSync", [path!])!;

    global::JavaScriptRuntime.IJavaScriptArray FsContract.readdirSync(object? path, object? options)
        => (global::JavaScriptRuntime.IJavaScriptArray)InvokeContractMember("readdirSync", [path!, options!])!;

    object? FsContract.readFileSync(object? path)
        => InvokeContractMember("readFileSync", [path!]);

    object? FsContract.readFileSync(object? path, object? options)
        => InvokeContractMember("readFileSync", [path!, options!]);

    object? FsContract.readlinkSync(object? path)
        => throw CreateNotImplementedException("readlinkSync");

    object? FsContract.readlinkSync(object? path, object? options)
        => throw CreateNotImplementedException("readlinkSync");

    double FsContract.readSync(double fd, object? buffer, double offset, double length)
        => throw CreateNotImplementedException("readSync");

    double FsContract.readSync(double fd, object? buffer, double offset, double length, object? position)
        => throw CreateNotImplementedException("readSync");

    double FsContract.readSync(double fd, object? buffer)
        => throw CreateNotImplementedException("readSync");

    double FsContract.readSync(double fd, object? buffer, object? options)
        => throw CreateNotImplementedException("readSync");

    double FsContract.readvSync(double fd, global::JavaScriptRuntime.IJavaScriptArray buffers)
        => throw CreateNotImplementedException("readvSync");

    double FsContract.readvSync(double fd, global::JavaScriptRuntime.IJavaScriptArray buffers, object? position)
        => throw CreateNotImplementedException("readvSync");

    object? FsContract.realpathSync(object? path)
        => throw CreateNotImplementedException("realpathSync");

    object? FsContract.realpathSync(object? path, object? options)
        => throw CreateNotImplementedException("realpathSync");

    object? FsContract.realpathSyncNative(object? path)
        => throw CreateNotImplementedException("realpathSync.native");

    object? FsContract.realpathSyncNative(object? path, object? options)
        => throw CreateNotImplementedException("realpathSync.native");

    void FsContract.renameSync(object? oldPath, object? newPath)
        => throw CreateNotImplementedException("renameSync");

    void FsContract.rmdirSync(object? path)
        => throw CreateNotImplementedException("rmdirSync");

    void FsContract.rmdirSync(object? path, object? options)
        => throw CreateNotImplementedException("rmdirSync");

    void FsContract.rmSync(object? path)
        => _ = InvokeContractMember("rmSync", [path!]);

    void FsContract.rmSync(object? path, object? options)
        => _ = InvokeContractMember("rmSync", [path!, options!]);

    object? FsContract.statSync(object? path)
        => InvokeContractMember("statSync", [path!]);

    object? FsContract.statSync(object? path, object? options)
        => InvokeContractMember("statSync", [path!, options!]);

    object? FsContract.statfsSync(object? path)
        => throw CreateNotImplementedException("statfsSync");

    object? FsContract.statfsSync(object? path, object? options)
        => throw CreateNotImplementedException("statfsSync");

    void FsContract.symlinkSync(object? target, object? path)
        => throw CreateNotImplementedException("symlinkSync");

    void FsContract.symlinkSync(object? target, object? path, object? type)
        => throw CreateNotImplementedException("symlinkSync");

    void FsContract.truncateSync(object? path)
        => throw CreateNotImplementedException("truncateSync");

    void FsContract.truncateSync(object? path, object? len)
        => throw CreateNotImplementedException("truncateSync");

    void FsContract.unlinkSync(object? path)
        => _ = InvokeContractMember("unlinkSync", [path!]);

    void FsContract.utimesSync(object? path, object? atime, object? mtime)
        => throw CreateNotImplementedException("utimesSync");

    void FsContract.writeFileSync(object? file, object? data)
        => _ = InvokeContractMember("writeFileSync", [file!, data!]);

    void FsContract.writeFileSync(object? file, object? data, object? options)
        => _ = InvokeContractMember("writeFileSync", [file!, data!, options!]);

    double FsContract.writeSync(double fd, object? buffer, double offset)
        => throw CreateNotImplementedException("writeSync");

    double FsContract.writeSync(double fd, object? buffer, double offset, object? length)
        => throw CreateNotImplementedException("writeSync");

    double FsContract.writeSync(double fd, object? buffer, double offset, object? length, object? position)
        => throw CreateNotImplementedException("writeSync");

    double FsContract.writeSync(double fd, object? buffer)
        => throw CreateNotImplementedException("writeSync");

    double FsContract.writeSync(double fd, object? buffer, object? options)
        => throw CreateNotImplementedException("writeSync");

    double FsContract.writeSync(double fd, string @string)
        => throw CreateNotImplementedException("writeSync");

    double FsContract.writeSync(double fd, string @string, object? position)
        => throw CreateNotImplementedException("writeSync");

    double FsContract.writeSync(double fd, string @string, object? position, object? encoding)
        => throw CreateNotImplementedException("writeSync");

    double FsContract.writevSync(double fd, global::JavaScriptRuntime.IJavaScriptArray buffers)
        => throw CreateNotImplementedException("writevSync");

    double FsContract.writevSync(double fd, global::JavaScriptRuntime.IJavaScriptArray buffers, object? position)
        => throw CreateNotImplementedException("writevSync");

    private static bool IsImplementedContractMethod(string memberName)
        => memberName switch
        {
            nameof(access) => true,
            nameof(appendFile) => true,
            nameof(copyFile) => true,
            nameof(createReadStream) => true,
            nameof(createWriteStream) => true,
            nameof(existsSync) => true,
            nameof(mkdir) => true,
            nameof(mkdirSync) => true,
            nameof(open) => true,
            nameof(readFile) => true,
            nameof(readFileSync) => true,
            nameof(readdir) => true,
            nameof(readdirSync) => true,
            nameof(realpath) => true,
            nameof(rename) => true,
            nameof(rm) => true,
            nameof(rmSync) => true,
            nameof(stat) => true,
            nameof(statSync) => true,
            nameof(unlink) => true,
            nameof(unlinkSync) => true,
            nameof(writeFile) => true,
            nameof(writeFileSync) => true,
            _ => false
        };

    private object? InvokeContractMember(string memberName, object[] arguments)
    {
        if (!IsImplementedContractMethod(memberName))
        {
            throw CreateNotImplementedException(memberName);
        }

        return global::JavaScriptRuntime.ObjectRuntime.CallInstanceMethod(this, memberName, arguments);
    }

    private static global::System.NotImplementedException CreateNotImplementedException(string memberName)
        => new($"The intrinsic node:fs module does not implement 'fs.{memberName}'.");
}
