// <auto-generated />
// Generated from the official Node.js 24.18.1 fs API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/fs.json
// SHA-256: 3145e3751afc28b868f9b481788a081fd87adf3215aa638f850fcb52d636ab6b

#nullable enable
#pragma warning disable CS0618

using FsContract = Jroc.Runtime.Node.Contracts.IFsPromisesModule;

namespace JavaScriptRuntime.Node;

public sealed partial class FSPromises : FsContract
{
    object? FsContract.constants
        => throw CreateNotImplementedException("constants");

    global::JavaScriptRuntime.IJavaScriptPromise FsContract.access(object? path)
        => (global::JavaScriptRuntime.IJavaScriptPromise)access(path!)!;

    global::JavaScriptRuntime.IJavaScriptPromise FsContract.access(object? path, object? mode)
        => (global::JavaScriptRuntime.IJavaScriptPromise)access(path!, mode!)!;

    global::JavaScriptRuntime.IJavaScriptPromise FsContract.appendFile(object? path, object? data)
        => (global::JavaScriptRuntime.IJavaScriptPromise)appendFile(path!, data!)!;

    global::JavaScriptRuntime.IJavaScriptPromise FsContract.appendFile(object? path, object? data, object? options)
        => (global::JavaScriptRuntime.IJavaScriptPromise)appendFile(path!, data!, options!)!;

    global::JavaScriptRuntime.IJavaScriptPromise FsContract.chmod(object? path, object? mode)
        => throw CreateNotImplementedException("chmod");

    global::JavaScriptRuntime.IJavaScriptPromise FsContract.chown(object? path, double uid, double gid)
        => throw CreateNotImplementedException("chown");

    global::JavaScriptRuntime.IJavaScriptPromise FsContract.copyFile(object? src, object? dest)
        => (global::JavaScriptRuntime.IJavaScriptPromise)copyFile(src!, dest!)!;

    global::JavaScriptRuntime.IJavaScriptPromise FsContract.copyFile(object? src, object? dest, object? mode)
        => (global::JavaScriptRuntime.IJavaScriptPromise)copyFile(src!, dest!)!;

    global::JavaScriptRuntime.IJavaScriptPromise FsContract.cp(object? src, object? dest)
        => throw CreateNotImplementedException("cp");

    global::JavaScriptRuntime.IJavaScriptPromise FsContract.cp(object? src, object? dest, object? options)
        => throw CreateNotImplementedException("cp");

    global::JavaScriptRuntime.IJavaScriptAsyncIterator FsContract.glob(object? pattern)
        => throw CreateNotImplementedException("glob");

    global::JavaScriptRuntime.IJavaScriptAsyncIterator FsContract.glob(object? pattern, object? options)
        => throw CreateNotImplementedException("glob");

    global::JavaScriptRuntime.IJavaScriptPromise FsContract.lchmod(object? path, double mode)
        => throw CreateNotImplementedException("lchmod");

    global::JavaScriptRuntime.IJavaScriptPromise FsContract.lchown(object? path, double uid, double gid)
        => throw CreateNotImplementedException("lchown");

    global::JavaScriptRuntime.IJavaScriptPromise FsContract.lutimes(object? path, object? atime, object? mtime)
        => throw CreateNotImplementedException("lutimes");

    global::JavaScriptRuntime.IJavaScriptPromise FsContract.link(object? existingPath, object? newPath)
        => throw CreateNotImplementedException("link");

    global::JavaScriptRuntime.IJavaScriptPromise FsContract.lstat(object? path)
        => (global::JavaScriptRuntime.IJavaScriptPromise)lstat(path!)!;

    global::JavaScriptRuntime.IJavaScriptPromise FsContract.lstat(object? path, object? options)
        => (global::JavaScriptRuntime.IJavaScriptPromise)lstat(path!)!;

    global::JavaScriptRuntime.IJavaScriptPromise FsContract.mkdir(object? path)
        => (global::JavaScriptRuntime.IJavaScriptPromise)mkdir(path!)!;

    global::JavaScriptRuntime.IJavaScriptPromise FsContract.mkdir(object? path, object? options)
        => (global::JavaScriptRuntime.IJavaScriptPromise)mkdir(path!, options!)!;

    global::JavaScriptRuntime.IJavaScriptPromise FsContract.mkdtemp(object? prefix)
        => throw CreateNotImplementedException("mkdtemp");

    global::JavaScriptRuntime.IJavaScriptPromise FsContract.mkdtemp(object? prefix, object? options)
        => throw CreateNotImplementedException("mkdtemp");

    global::JavaScriptRuntime.IJavaScriptPromise FsContract.mkdtempDisposable(object? prefix)
        => throw CreateNotImplementedException("mkdtempDisposable");

    global::JavaScriptRuntime.IJavaScriptPromise FsContract.mkdtempDisposable(object? prefix, object? options)
        => throw CreateNotImplementedException("mkdtempDisposable");

    global::JavaScriptRuntime.IJavaScriptPromise FsContract.open(object? path, object? flags)
        => (global::JavaScriptRuntime.IJavaScriptPromise)open(path!, flags!)!;

    global::JavaScriptRuntime.IJavaScriptPromise FsContract.open(object? path, object? flags, object? mode)
        => (global::JavaScriptRuntime.IJavaScriptPromise)open(path!, flags!, mode!)!;

    global::JavaScriptRuntime.IJavaScriptPromise FsContract.opendir(object? path)
        => throw CreateNotImplementedException("opendir");

    global::JavaScriptRuntime.IJavaScriptPromise FsContract.opendir(object? path, object? options)
        => throw CreateNotImplementedException("opendir");

    global::JavaScriptRuntime.IJavaScriptPromise FsContract.readdir(object? path)
        => (global::JavaScriptRuntime.IJavaScriptPromise)readdir(path!)!;

    global::JavaScriptRuntime.IJavaScriptPromise FsContract.readdir(object? path, object? options)
        => (global::JavaScriptRuntime.IJavaScriptPromise)readdir(path!, options!)!;

    global::JavaScriptRuntime.IJavaScriptPromise FsContract.readFile(object? path)
        => (global::JavaScriptRuntime.IJavaScriptPromise)readFile(path!)!;

    global::JavaScriptRuntime.IJavaScriptPromise FsContract.readFile(object? path, object? options)
        => (global::JavaScriptRuntime.IJavaScriptPromise)readFile(path!, global::Jroc.Runtime.Node.Contracts.NodeModuleContractHosting.Unwrap(options!)!)!;

    global::JavaScriptRuntime.IJavaScriptPromise FsContract.readlink(object? path)
        => throw CreateNotImplementedException("readlink");

    global::JavaScriptRuntime.IJavaScriptPromise FsContract.readlink(object? path, object? options)
        => throw CreateNotImplementedException("readlink");

    global::JavaScriptRuntime.IJavaScriptPromise FsContract.realpath(object? path)
        => (global::JavaScriptRuntime.IJavaScriptPromise)realpath(path!)!;

    global::JavaScriptRuntime.IJavaScriptPromise FsContract.realpath(object? path, object? options)
        => (global::JavaScriptRuntime.IJavaScriptPromise)realpath(path!)!;

    global::JavaScriptRuntime.IJavaScriptPromise FsContract.rename(object? oldPath, object? newPath)
        => (global::JavaScriptRuntime.IJavaScriptPromise)rename(oldPath!, newPath!)!;

    global::JavaScriptRuntime.IJavaScriptPromise FsContract.rmdir(object? path)
        => throw CreateNotImplementedException("rmdir");

    global::JavaScriptRuntime.IJavaScriptPromise FsContract.rmdir(object? path, object? options)
        => throw CreateNotImplementedException("rmdir");

    global::JavaScriptRuntime.IJavaScriptPromise FsContract.rm(object? path)
        => throw CreateNotImplementedException("rm");

    global::JavaScriptRuntime.IJavaScriptPromise FsContract.rm(object? path, object? options)
        => throw CreateNotImplementedException("rm");

    global::JavaScriptRuntime.IJavaScriptPromise FsContract.stat(object? path)
        => (global::JavaScriptRuntime.IJavaScriptPromise)stat(path!)!;

    global::JavaScriptRuntime.IJavaScriptPromise FsContract.stat(object? path, object? options)
        => (global::JavaScriptRuntime.IJavaScriptPromise)stat(path!)!;

    global::JavaScriptRuntime.IJavaScriptPromise FsContract.statfs(object? path)
        => throw CreateNotImplementedException("statfs");

    global::JavaScriptRuntime.IJavaScriptPromise FsContract.statfs(object? path, object? options)
        => throw CreateNotImplementedException("statfs");

    global::JavaScriptRuntime.IJavaScriptPromise FsContract.symlink(object? target, object? path)
        => throw CreateNotImplementedException("symlink");

    global::JavaScriptRuntime.IJavaScriptPromise FsContract.symlink(object? target, object? path, object? type)
        => throw CreateNotImplementedException("symlink");

    global::JavaScriptRuntime.IJavaScriptPromise FsContract.truncate(object? path)
        => throw CreateNotImplementedException("truncate");

    global::JavaScriptRuntime.IJavaScriptPromise FsContract.truncate(object? path, object? len)
        => throw CreateNotImplementedException("truncate");

    global::JavaScriptRuntime.IJavaScriptPromise FsContract.unlink(object? path)
        => (global::JavaScriptRuntime.IJavaScriptPromise)unlink(path!)!;

    global::JavaScriptRuntime.IJavaScriptPromise FsContract.utimes(object? path, object? atime, object? mtime)
        => throw CreateNotImplementedException("utimes");

    global::JavaScriptRuntime.IJavaScriptAsyncIterator FsContract.watch(object? filename)
        => throw CreateNotImplementedException("watch");

    global::JavaScriptRuntime.IJavaScriptAsyncIterator FsContract.watch(object? filename, object? options)
        => throw CreateNotImplementedException("watch");

    global::JavaScriptRuntime.IJavaScriptPromise FsContract.writeFile(object? file, object? data)
        => (global::JavaScriptRuntime.IJavaScriptPromise)writeFile(file!, data!)!;

    global::JavaScriptRuntime.IJavaScriptPromise FsContract.writeFile(object? file, object? data, object? options)
        => (global::JavaScriptRuntime.IJavaScriptPromise)writeFile(file!, data!, global::Jroc.Runtime.Node.Contracts.NodeModuleContractHosting.Unwrap(options!)!)!;

    private static global::System.NotImplementedException CreateNotImplementedException(string memberName)
        => new($"The intrinsic node:fs/promises module does not implement 'fsPromises.{memberName}'.");
}
