// <auto-generated />
// Generated from the official Node.js 24.18.1 http API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/http.json
// SHA-256: 25994076a4ed8a903b743eab54b9b9f7509497fd2f0a49bf00eee291145a8a1b

#nullable enable
#pragma warning disable CS0618

using HttpContract = Jroc.Runtime.Node.Contracts.IHttpModule;

namespace JavaScriptRuntime.Node;

public sealed partial class Http : HttpContract
{
    global::JavaScriptRuntime.IJavaScriptArray HttpContract.METHODS
        => throw CreateNotImplementedException("METHODS");

    object? HttpContract.STATUS_CODES
        => throw CreateNotImplementedException("STATUS_CODES");

    object? HttpContract.globalAgent
    {
        get => globalAgent;
        set => throw CreateNotImplementedException("globalAgent");
    }

    double HttpContract.maxHeaderSize
        => throw CreateNotImplementedException("maxHeaderSize");

    object? HttpContract.Agent
        => Agent;

    object? HttpContract.ClientRequest
        => ClientRequest;

    object? HttpContract.IncomingMessage
        => IncomingMessage;

    object? HttpContract.OutgoingMessage
        => throw CreateNotImplementedException("OutgoingMessage");

    object? HttpContract.Server
        => Server;

    object? HttpContract.ServerResponse
        => ServerResponse;

    object? HttpContract.WebSocket
        => throw CreateNotImplementedException("WebSocket");

    object? HttpContract.createServer()
        => createServer(new object[] {  });

    object? HttpContract.createServer(object? requestListener)
        => createServer(new object[] { requestListener! });

    object? HttpContract.createServer(object? options, object? requestListener)
        => createServer(new object[] { options!, requestListener! });

    void HttpContract.validateHeaderName(string name)
        => throw CreateNotImplementedException("validateHeaderName");

    void HttpContract.validateHeaderName(string name, object? label)
        => throw CreateNotImplementedException("validateHeaderName");

    void HttpContract.validateHeaderValue(string name, object? value)
        => throw CreateNotImplementedException("validateHeaderValue");

    void HttpContract.setMaxIdleHTTPParsers(double max)
        => throw CreateNotImplementedException("setMaxIdleHTTPParsers");

    global::System.Delegate HttpContract.setGlobalProxyFromEnv()
        => throw CreateNotImplementedException("setGlobalProxyFromEnv");

    global::System.Delegate HttpContract.setGlobalProxyFromEnv(object? proxyEnv)
        => throw CreateNotImplementedException("setGlobalProxyFromEnv");

    object? HttpContract.get(object? optionsOrUrl)
        => get(new object[] { optionsOrUrl! });

    object? HttpContract.get(object? optionsOrUrl, global::System.Delegate callback)
        => get(new object[] { optionsOrUrl!, callback! });

    object? HttpContract.get(object? url, object? options)
        => get(new object[] { url!, options! });

    object? HttpContract.get(object? url, object? options, global::System.Delegate callback)
        => get(new object[] { url!, options!, callback! });

    object? HttpContract.request(object? optionsOrUrl)
        => request(new object[] { optionsOrUrl! });

    object? HttpContract.request(object? optionsOrUrl, global::System.Delegate callback)
        => request(new object[] { optionsOrUrl!, callback! });

    object? HttpContract.request(object? url, object? options)
        => request(new object[] { url!, options! });

    object? HttpContract.request(object? url, object? options, global::System.Delegate callback)
        => request(new object[] { url!, options!, callback! });

    private static global::System.NotImplementedException CreateNotImplementedException(string memberName)
        => new($"The intrinsic node:http module does not implement 'http.{memberName}'.");
}
