// <auto-generated />
// Generated from the official Node.js 24.18.1 https API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/https.json
// SHA-256: 01cd27f75bfd46f819893ef3d1de923603f97dfe368ef792858e5a745c7fe016

#nullable enable
#pragma warning disable CS0618

using HttpsContract = Jroc.Runtime.Node.Contracts.IHttpsModule;

namespace JavaScriptRuntime.Node;

public sealed partial class Https : HttpsContract
{
    object? HttpsContract.globalAgent
    {
        get => throw CreateNotImplementedException("globalAgent");
        set => throw CreateNotImplementedException("globalAgent");
    }

    object? HttpsContract.Agent
        => throw CreateNotImplementedException("Agent");

    object? HttpsContract.Server
        => Server;

    object? HttpsContract.createServer()
        => createServer(new object[] {  });

    object? HttpsContract.createServer(object? requestListener)
        => createServer(new object[] { requestListener! });

    object? HttpsContract.createServer(object? options, object? requestListener)
        => createServer(new object[] { options!, requestListener! });

    object? HttpsContract.get(object? optionsOrUrl)
        => get(new object[] { optionsOrUrl! });

    object? HttpsContract.get(object? optionsOrUrl, global::System.Delegate callback)
        => get(new object[] { optionsOrUrl!, callback! });

    object? HttpsContract.get(object? url, object? options)
        => get(new object[] { url!, options! });

    object? HttpsContract.get(object? url, object? options, global::System.Delegate callback)
        => get(new object[] { url!, options!, callback! });

    object? HttpsContract.request(object? optionsOrUrl)
        => request(new object[] { optionsOrUrl! });

    object? HttpsContract.request(object? optionsOrUrl, global::System.Delegate callback)
        => request(new object[] { optionsOrUrl!, callback! });

    object? HttpsContract.request(object? url, object? options)
        => request(new object[] { url!, options! });

    object? HttpsContract.request(object? url, object? options, global::System.Delegate callback)
        => request(new object[] { url!, options!, callback! });

    private static global::System.NotImplementedException CreateNotImplementedException(string memberName)
        => new($"The intrinsic node:https module does not implement 'https.{memberName}'.");
}
