// <auto-generated />
// Generated from the official Node.js 24.18.1 net API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/net.json
// SHA-256: 2d33daee78e804a2eab914dde4bb3a70fd1fa8b48a8e7bb0563f26b473be7d27

#nullable enable
#pragma warning disable CS0618

using NetContract = Jroc.Runtime.Node.Contracts.INetModule;

namespace JavaScriptRuntime.Node;

public sealed partial class Net : NetContract
{
    object? NetContract.BlockList
        => throw CreateNotImplementedException("BlockList");

    object? NetContract.SocketAddress
        => throw CreateNotImplementedException("SocketAddress");

    object? NetContract.Server
        => Server;

    object? NetContract.Socket
        => Socket;

    object? NetContract.connect(object? options)
        => connect(new object[] { options! });

    object? NetContract.connect(object? options, global::System.Delegate connectListener)
        => connect(new object[] { options!, connectListener! });

    object? NetContract.connect(string path)
        => connect(new object[] { path! });

    object? NetContract.connect(string path, global::System.Delegate connectListener)
        => connect(new object[] { path!, connectListener! });

    object? NetContract.connect(double port)
        => connect(new object[] { port! });

    object? NetContract.connect(double port, string host)
        => connect(new object[] { port!, host! });

    object? NetContract.connect(double port, global::System.Delegate connectListener)
        => connect(new object[] { port!, connectListener! });

    object? NetContract.connect(double port, string host, global::System.Delegate connectListener)
        => connect(new object[] { port!, host!, connectListener! });

    object? NetContract.createConnection(object? options)
        => createConnection(new object[] { options! });

    object? NetContract.createConnection(object? options, global::System.Delegate connectListener)
        => createConnection(new object[] { options!, connectListener! });

    object? NetContract.createConnection(string path)
        => createConnection(new object[] { path! });

    object? NetContract.createConnection(string path, global::System.Delegate connectListener)
        => createConnection(new object[] { path!, connectListener! });

    object? NetContract.createConnection(double port)
        => createConnection(new object[] { port! });

    object? NetContract.createConnection(double port, string host)
        => createConnection(new object[] { port!, host! });

    object? NetContract.createConnection(double port, global::System.Delegate connectListener)
        => createConnection(new object[] { port!, connectListener! });

    object? NetContract.createConnection(double port, string host, global::System.Delegate connectListener)
        => createConnection(new object[] { port!, host!, connectListener! });

    object? NetContract.createServer()
        => createServer(new object[] {  });

    object? NetContract.createServer(object? options)
        => createServer(new object[] { options! });

    object? NetContract.createServer(global::System.Delegate connectionListener)
        => createServer(new object[] { connectionListener! });

    object? NetContract.createServer(object? options, global::System.Delegate connectionListener)
        => createServer(new object[] { options!, connectionListener! });

    bool NetContract.getDefaultAutoSelectFamily()
        => throw CreateNotImplementedException("getDefaultAutoSelectFamily");

    void NetContract.setDefaultAutoSelectFamily(bool value)
        => throw CreateNotImplementedException("setDefaultAutoSelectFamily");

    double NetContract.getDefaultAutoSelectFamilyAttemptTimeout()
        => throw CreateNotImplementedException("getDefaultAutoSelectFamilyAttemptTimeout");

    void NetContract.setDefaultAutoSelectFamilyAttemptTimeout(double value)
        => throw CreateNotImplementedException("setDefaultAutoSelectFamilyAttemptTimeout");

    double NetContract.isIP(string input)
        => throw CreateNotImplementedException("isIP");

    bool NetContract.isIPv4(string input)
        => throw CreateNotImplementedException("isIPv4");

    bool NetContract.isIPv6(string input)
        => throw CreateNotImplementedException("isIPv6");

    private static global::System.NotImplementedException CreateNotImplementedException(string memberName)
        => new($"The intrinsic node:net module does not implement 'net.{memberName}'.");
}
