// <auto-generated />
// Generated from the official Node.js 24.18.1 os API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/os.json
// SHA-256: 059b5b4c88a45d181bfddd90c3f2b45a008dcf5e356ccaa886959b87ab108c07

#nullable enable
#pragma warning disable CS0618

using OsContract = Jroc.Runtime.Node.Contracts.IOsModule;

namespace JavaScriptRuntime.Node;

public sealed partial class OS : OsContract
{
    string OsContract.EOL
        => throw CreateNotImplementedException("EOL");

    object? OsContract.constants
        => throw CreateNotImplementedException("constants");

    string OsContract.devNull
        => throw CreateNotImplementedException("devNull");

    double OsContract.availableParallelism()
        => throw CreateNotImplementedException("availableParallelism");

    string OsContract.arch()
        => throw CreateNotImplementedException("arch");

    global::JavaScriptRuntime.IJavaScriptArray OsContract.cpus()
        => throw CreateNotImplementedException("cpus");

    string OsContract.endianness()
        => throw CreateNotImplementedException("endianness");

    double OsContract.freemem()
        => throw CreateNotImplementedException("freemem");

    double OsContract.getPriority()
        => throw CreateNotImplementedException("getPriority");

    double OsContract.getPriority(object? pid)
        => throw CreateNotImplementedException("getPriority");

    string OsContract.homedir()
        => global::JavaScriptRuntime.DotNet2JSConversions.ToString(homedir());

    string OsContract.hostname()
        => throw CreateNotImplementedException("hostname");

    global::JavaScriptRuntime.IJavaScriptArray OsContract.loadavg()
        => throw CreateNotImplementedException("loadavg");

    string OsContract.machine()
        => throw CreateNotImplementedException("machine");

    object? OsContract.networkInterfaces()
        => throw CreateNotImplementedException("networkInterfaces");

    string OsContract.platform()
        => throw CreateNotImplementedException("platform");

    string OsContract.release()
        => throw CreateNotImplementedException("release");

    void OsContract.setPriority(double priority)
        => throw CreateNotImplementedException("setPriority");

    void OsContract.setPriority(object? pid, double priority)
        => throw CreateNotImplementedException("setPriority");

    string OsContract.tmpdir()
        => global::JavaScriptRuntime.DotNet2JSConversions.ToString(tmpdir());

    double OsContract.totalmem()
        => throw CreateNotImplementedException("totalmem");

    string OsContract.type()
        => throw CreateNotImplementedException("type");

    double OsContract.uptime()
        => throw CreateNotImplementedException("uptime");

    object? OsContract.userInfo()
        => throw CreateNotImplementedException("userInfo");

    object? OsContract.userInfo(object? options)
        => throw CreateNotImplementedException("userInfo");

    string OsContract.version()
        => throw CreateNotImplementedException("version");

    private static global::System.NotImplementedException CreateNotImplementedException(string memberName)
        => new($"The intrinsic node:os module does not implement 'os.{memberName}'.");
}
