// <auto-generated />
// Generated from the official Node.js 24.18.1 path API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/path.json
// SHA-256: 9f93050a3383e78ffb2ac7f14f5c2addf1f030488481e8508e9c3097ba62a296

#nullable enable
#pragma warning disable CS0618

using PathContract = Jroc.Runtime.Node.Contracts.IPathModule;

namespace JavaScriptRuntime.Node;

public sealed partial class Path : PathContract
{
    string PathContract.delimiter
        => delimiter;

    object? PathContract.posix
        => posix;

    string PathContract.sep
        => sep;

    object? PathContract.win32
        => win32;

    string PathContract.basename(string path)
        => global::JavaScriptRuntime.DotNet2JSConversions.ToString(basename(path!));

    string PathContract.basename(string path, object? suffix)
        => global::JavaScriptRuntime.DotNet2JSConversions.ToString(basename(path!, suffix!));

    string PathContract.dirname(string path)
        => global::JavaScriptRuntime.DotNet2JSConversions.ToString(dirname(path!));

    string PathContract.extname(string path)
        => global::JavaScriptRuntime.DotNet2JSConversions.ToString(extname(path!));

    string PathContract.format(object? pathObject)
        => global::JavaScriptRuntime.DotNet2JSConversions.ToString(format(pathObject!));

    bool PathContract.matchesGlob(string path, string pattern)
        => throw CreateNotImplementedException("matchesGlob");

    bool PathContract.isAbsolute(string path)
        => global::JavaScriptRuntime.TypeUtilities.ToBoolean(isAbsolute(path!));

    string PathContract.join(params object?[] paths)
        => global::JavaScriptRuntime.DotNet2JSConversions.ToString(join(paths!));

    string PathContract.normalize(string path)
        => global::JavaScriptRuntime.DotNet2JSConversions.ToString(normalize(path!));

    object? PathContract.parse(string path)
        => parse(path!);

    string PathContract.relative(string from, string to)
        => global::JavaScriptRuntime.DotNet2JSConversions.ToString(relative(from!, to!));

    string PathContract.resolve(params object?[] paths)
        => global::JavaScriptRuntime.DotNet2JSConversions.ToString(resolve(paths!));

    string PathContract.toNamespacedPath(string path)
        => global::JavaScriptRuntime.DotNet2JSConversions.ToString(toNamespacedPath(path!));

    private static global::System.NotImplementedException CreateNotImplementedException(string memberName)
        => new($"The intrinsic node:path module does not implement 'path.{memberName}'.");
}
