// <auto-generated />
// Generated from the official Node.js 24.18.1 perf_hooks API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/perf_hooks.json
// SHA-256: f01887a857d70a430f9d13b13b5e98641f1d6d12b1259dea0baaa74a996ab4b7

#nullable enable
#pragma warning disable CS0618

using NestedContract = Jroc.Runtime.Node.Contracts.IPerfHooksPerformance;

namespace JavaScriptRuntime.Node;

public sealed partial class PerfHooks
{
    public sealed partial class Performance : NestedContract
    {
        double NestedContract.now()
            => now();

        private static global::System.NotImplementedException CreateNotImplementedException(string memberName)
            => new($"The intrinsic node:perf_hooks.Performance contract does not implement 'performance.{memberName}'.");
    }
}
