// <auto-generated />
// Generated from the official Node.js 24.18.1 perf_hooks API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/perf_hooks.json
// SHA-256: f01887a857d70a430f9d13b13b5e98641f1d6d12b1259dea0baaa74a996ab4b7

#nullable enable
#pragma warning disable CS0618

using PerfHooksContract = Jroc.Runtime.Node.Contracts.IPerfHooksModule;

namespace JavaScriptRuntime.Node;

public sealed partial class PerfHooks : PerfHooksContract
{
    object? PerfHooksContract.Performance
        => throw CreateNotImplementedException("Performance");

    object? PerfHooksContract.PerformanceEntry
        => throw CreateNotImplementedException("PerformanceEntry");

    object? PerfHooksContract.PerformanceMark
        => throw CreateNotImplementedException("PerformanceMark");

    object? PerfHooksContract.PerformanceMeasure
        => throw CreateNotImplementedException("PerformanceMeasure");

    object? PerfHooksContract.PerformanceObserver
        => throw CreateNotImplementedException("PerformanceObserver");

    object? PerfHooksContract.PerformanceObserverEntryList
        => throw CreateNotImplementedException("PerformanceObserverEntryList");

    object? PerfHooksContract.PerformanceResourceTiming
        => throw CreateNotImplementedException("PerformanceResourceTiming");

    object? PerfHooksContract.constants
        => throw CreateNotImplementedException("constants");

    global::Jroc.Runtime.Node.Contracts.IPerfHooksPerformance PerfHooksContract.performance
        => (global::Jroc.Runtime.Node.Contracts.IPerfHooksPerformance)performance!;

    object? PerfHooksContract.createHistogram()
        => throw CreateNotImplementedException("createHistogram");

    object? PerfHooksContract.createHistogram(object? options)
        => throw CreateNotImplementedException("createHistogram");

    object? PerfHooksContract.eventLoopUtilization()
        => throw CreateNotImplementedException("eventLoopUtilization");

    object? PerfHooksContract.eventLoopUtilization(object? utilization1)
        => throw CreateNotImplementedException("eventLoopUtilization");

    object? PerfHooksContract.eventLoopUtilization(object? utilization1, object? utilization2)
        => throw CreateNotImplementedException("eventLoopUtilization");

    object? PerfHooksContract.monitorEventLoopDelay()
        => throw CreateNotImplementedException("monitorEventLoopDelay");

    object? PerfHooksContract.monitorEventLoopDelay(object? options)
        => throw CreateNotImplementedException("monitorEventLoopDelay");

    global::System.Delegate PerfHooksContract.timerify(global::System.Delegate fn)
        => throw CreateNotImplementedException("timerify");

    global::System.Delegate PerfHooksContract.timerify(global::System.Delegate fn, object? options)
        => throw CreateNotImplementedException("timerify");

    private static global::System.NotImplementedException CreateNotImplementedException(string memberName)
        => new($"The intrinsic node:perf_hooks module does not implement 'perf_hooks.{memberName}'.");
}
