// <auto-generated />
// Generated from the official Node.js 24.18.1 querystring API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/querystring.json
// SHA-256: d042a799ccc565df8352cd62b3e57f50b609b08291fcaa28a9cb9d3da5641023

#nullable enable
#pragma warning disable CS0618

using QueryStringContract = Jroc.Runtime.Node.Contracts.IQueryStringModule;

namespace JavaScriptRuntime.Node;

public sealed partial class QueryString : QueryStringContract
{
    object? QueryStringContract.decode(string str)
        => parse(str!);

    object? QueryStringContract.decode(string str, string sep)
        => parse(str!, sep!);

    object? QueryStringContract.decode(string str, string sep, string eq)
        => parse(str!, sep!, eq!);

    object? QueryStringContract.decode(string str, string sep, string eq, object? options)
        => parse(str!, sep!, eq!, options!);

    string QueryStringContract.encode(object? obj)
        => global::JavaScriptRuntime.DotNet2JSConversions.ToString(stringify(obj!));

    string QueryStringContract.encode(object? obj, string sep)
        => global::JavaScriptRuntime.DotNet2JSConversions.ToString(stringify(obj!, sep!));

    string QueryStringContract.encode(object? obj, string sep, string eq)
        => global::JavaScriptRuntime.DotNet2JSConversions.ToString(stringify(obj!, sep!, eq!));

    string QueryStringContract.encode(object? obj, string sep, string eq, object? options)
        => global::JavaScriptRuntime.DotNet2JSConversions.ToString(stringify(obj!, sep!, eq!, options!));

    string QueryStringContract.escape(string str)
        => throw CreateNotImplementedException("escape");

    object? QueryStringContract.parse(string str)
        => parse(str!);

    object? QueryStringContract.parse(string str, string sep)
        => parse(str!, sep!);

    object? QueryStringContract.parse(string str, string sep, string eq)
        => parse(str!, sep!, eq!);

    object? QueryStringContract.parse(string str, string sep, string eq, object? options)
        => parse(str!, sep!, eq!, options!);

    string QueryStringContract.stringify(object? obj)
        => global::JavaScriptRuntime.DotNet2JSConversions.ToString(stringify(obj!));

    string QueryStringContract.stringify(object? obj, string sep)
        => global::JavaScriptRuntime.DotNet2JSConversions.ToString(stringify(obj!, sep!));

    string QueryStringContract.stringify(object? obj, string sep, string eq)
        => global::JavaScriptRuntime.DotNet2JSConversions.ToString(stringify(obj!, sep!, eq!));

    string QueryStringContract.stringify(object? obj, string sep, string eq, object? options)
        => global::JavaScriptRuntime.DotNet2JSConversions.ToString(stringify(obj!, sep!, eq!, options!));

    string QueryStringContract.unescape(string str)
        => throw CreateNotImplementedException("unescape");

    private static global::System.NotImplementedException CreateNotImplementedException(string memberName)
        => new($"The intrinsic node:querystring module does not implement 'querystring.{memberName}'.");
}
