// <auto-generated />
// Generated from the official Node.js 24.18.1 stream API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/stream.json
// SHA-256: d60aeb160a21b7ec143de394320e97dc8751777325c698eb1fcc36c82da5e06e

#nullable enable
#pragma warning disable CS0618

using StreamContract = Jroc.Runtime.Node.Contracts.IStreamModule;

namespace JavaScriptRuntime.Node;

public sealed partial class Stream : StreamContract
{
    object? StreamContract.Readable
        => Readable;

    object? StreamContract.Writable
        => Writable;

    object? StreamContract.Duplex
        => Duplex;

    object? StreamContract.Transform
        => Transform;

    object? StreamContract.PassThrough
        => PassThrough;

    object? StreamContract.promises
        => throw CreateNotImplementedException("promises");

    global::System.Delegate StreamContract.finished(object? stream, global::System.Delegate callback)
        => (global::System.Delegate)finished(new object[] { stream!, callback! })!;

    global::System.Delegate StreamContract.finished(object? stream, object? options, global::System.Delegate callback)
        => (global::System.Delegate)finished(new object[] { stream!, options!, callback! })!;

    bool StreamContract.isErrored(object? stream)
        => throw CreateNotImplementedException("isErrored");

    object? StreamContract.isReadable(object? stream)
        => throw CreateNotImplementedException("isReadable");

    object? StreamContract.isWritable(object? stream)
        => throw CreateNotImplementedException("isWritable");

    object? StreamContract.addAbortSignal(object? signal, object? stream)
        => throw CreateNotImplementedException("addAbortSignal");

    double StreamContract.getDefaultHighWaterMark(bool objectMode)
        => throw CreateNotImplementedException("getDefaultHighWaterMark");

    void StreamContract.setDefaultHighWaterMark(bool objectMode, double value)
        => throw CreateNotImplementedException("setDefaultHighWaterMark");

    global::JavaScriptRuntime.IJavaScriptArray StreamContract.duplexPair()
        => throw CreateNotImplementedException("duplexPair");

    global::JavaScriptRuntime.IJavaScriptArray StreamContract.duplexPair(object? options)
        => throw CreateNotImplementedException("duplexPair");

    object? StreamContract.pipeline(params object?[] args)
        => pipeline(args!);

    object? StreamContract.compose(params object?[] streams)
        => throw CreateNotImplementedException("compose");

    private static global::System.NotImplementedException CreateNotImplementedException(string memberName)
        => new($"The intrinsic node:stream module does not implement 'stream.{memberName}'.");
}
