// <auto-generated />
// Generated from the official Node.js 24.18.1 stream API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/stream.json
// SHA-256: d60aeb160a21b7ec143de394320e97dc8751777325c698eb1fcc36c82da5e06e

#nullable enable
#pragma warning disable CS0618

using StreamPromisesContract = Jroc.Runtime.Node.Contracts.IStreamPromisesModule;

namespace JavaScriptRuntime.Node;

public sealed partial class StreamPromises : StreamPromisesContract
{
    global::JavaScriptRuntime.IJavaScriptPromise StreamPromisesContract.finished(object? stream)
        => (global::JavaScriptRuntime.IJavaScriptPromise)finished(new object[] { stream! })!;

    global::JavaScriptRuntime.IJavaScriptPromise StreamPromisesContract.finished(object? stream, object? options)
        => (global::JavaScriptRuntime.IJavaScriptPromise)finished(new object[] { stream!, options! })!;

    global::JavaScriptRuntime.IJavaScriptPromise StreamPromisesContract.pipeline(params object?[] args)
        => (global::JavaScriptRuntime.IJavaScriptPromise)pipeline(args!)!;

    private static global::System.NotImplementedException CreateNotImplementedException(string memberName)
        => new($"The intrinsic node:stream/promises module does not implement 'stream.{memberName}'.");
}
