// <auto-generated />
// Generated from the official Node.js 24.18.1 string_decoder API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/string_decoder.json
// SHA-256: 5a9d34a9cf17624c5379f87a90111c8885b2ca2d5e686bdc4c36b7b5a807991b

#nullable enable
#pragma warning disable CS0618

using StringDecoderContract = Jroc.Runtime.Node.Contracts.IStringDecoderModule;

namespace JavaScriptRuntime.Node;

public sealed partial class StringDecoderModule : StringDecoderContract
{
    object? StringDecoderContract.StringDecoder
        => StringDecoder;

    private static global::System.NotImplementedException CreateNotImplementedException(string memberName)
        => new($"The intrinsic node:string_decoder module does not implement 'string_decoder.{memberName}'.");
}
