// <auto-generated />
// Generated from the official Node.js 24.18.1 tls API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/tls.json
// SHA-256: 3f8071ce06e3bd3a699389237241cde54458b5fe92edb9f868c036c3c408ac8f

#nullable enable
#pragma warning disable CS0618

using TlsContract = Jroc.Runtime.Node.Contracts.ITlsModule;

namespace JavaScriptRuntime.Node;

public sealed partial class Tls : TlsContract
{
    global::JavaScriptRuntime.IJavaScriptArray TlsContract.rootCertificates
        => throw CreateNotImplementedException("rootCertificates");

    string TlsContract.DEFAULT_ECDH_CURVE
    {
        get => throw CreateNotImplementedException("DEFAULT_ECDH_CURVE");
        set => throw CreateNotImplementedException("DEFAULT_ECDH_CURVE");
    }

    string TlsContract.DEFAULT_MAX_VERSION
    {
        get => throw CreateNotImplementedException("DEFAULT_MAX_VERSION");
        set => throw CreateNotImplementedException("DEFAULT_MAX_VERSION");
    }

    string TlsContract.DEFAULT_MIN_VERSION
    {
        get => throw CreateNotImplementedException("DEFAULT_MIN_VERSION");
        set => throw CreateNotImplementedException("DEFAULT_MIN_VERSION");
    }

    string TlsContract.DEFAULT_CIPHERS
    {
        get => throw CreateNotImplementedException("DEFAULT_CIPHERS");
        set => throw CreateNotImplementedException("DEFAULT_CIPHERS");
    }

    object? TlsContract.TLSSocket
        => TLSSocket;

    object? TlsContract.Server
        => Server;

    object? TlsContract.checkServerIdentity(string hostname, object? cert)
        => throw CreateNotImplementedException("checkServerIdentity");

    object? TlsContract.connect(object? options)
        => connect(new object[] { options! });

    object? TlsContract.connect(object? options, global::System.Delegate callback)
        => connect(new object[] { options!, callback! });

    object? TlsContract.connect(string path)
        => connect(new object[] { path! });

    object? TlsContract.connect(string path, object? options)
        => connect(new object[] { path!, options! });

    object? TlsContract.connect(string path, global::System.Delegate callback)
        => connect(new object[] { path!, callback! });

    object? TlsContract.connect(string path, object? options, global::System.Delegate callback)
        => connect(new object[] { path!, options!, callback! });

    object? TlsContract.connect(double port)
        => connect(new object[] { port! });

    object? TlsContract.connect(double port, string host)
        => connect(new object[] { port!, host! });

    object? TlsContract.connect(double port, object? options)
        => connect(new object[] { port!, options! });

    object? TlsContract.connect(double port, global::System.Delegate callback)
        => connect(new object[] { port!, callback! });

    object? TlsContract.connect(double port, string host, object? options)
        => connect(new object[] { port!, host!, options! });

    object? TlsContract.connect(double port, string host, global::System.Delegate callback)
        => connect(new object[] { port!, host!, callback! });

    object? TlsContract.connect(double port, object? options, global::System.Delegate callback)
        => connect(new object[] { port!, options!, callback! });

    object? TlsContract.connect(double port, string host, object? options, global::System.Delegate callback)
        => connect(new object[] { port!, host!, options!, callback! });

    object? TlsContract.createSecureContext()
        => createSecureContext();

    object? TlsContract.createSecureContext(object? options)
        => createSecureContext(options!);

    object? TlsContract.createServer()
        => createServer(new object[] {  });

    object? TlsContract.createServer(object? options)
        => createServer(new object[] { options! });

    object? TlsContract.createServer(global::System.Delegate secureConnectionListener)
        => createServer(new object[] { secureConnectionListener! });

    object? TlsContract.createServer(object? options, global::System.Delegate secureConnectionListener)
        => createServer(new object[] { options!, secureConnectionListener! });

    void TlsContract.setDefaultCACertificates(global::JavaScriptRuntime.IJavaScriptArray certs)
        => throw CreateNotImplementedException("setDefaultCACertificates");

    global::JavaScriptRuntime.IJavaScriptArray TlsContract.getCACertificates()
        => throw CreateNotImplementedException("getCACertificates");

    global::JavaScriptRuntime.IJavaScriptArray TlsContract.getCACertificates(string type)
        => throw CreateNotImplementedException("getCACertificates");

    global::JavaScriptRuntime.IJavaScriptArray TlsContract.getCiphers()
        => throw CreateNotImplementedException("getCiphers");

    private static global::System.NotImplementedException CreateNotImplementedException(string memberName)
        => new($"The intrinsic node:tls module does not implement 'tls.{memberName}'.");
}
