// <auto-generated />
// Generated from the official Node.js 24.18.1 url API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/url.json
// SHA-256: a04e0b637e409e07e83459d2936f07fa334f4c666c0c434a13e0734c52e9cbb0

#nullable enable
#pragma warning disable CS0618

using UrlContract = Jroc.Runtime.Node.Contracts.IUrlModule;

namespace JavaScriptRuntime.Node;

public sealed partial class Url : UrlContract
{
    object? UrlContract.URL
        => URL;

    object? UrlContract.URLSearchParams
        => URLSearchParams;

    object? UrlContract.URLPattern
        => throw CreateNotImplementedException("URLPattern");

    string UrlContract.domainToASCII(string domain)
        => throw CreateNotImplementedException("domainToASCII");

    string UrlContract.domainToUnicode(string domain)
        => throw CreateNotImplementedException("domainToUnicode");

    string UrlContract.fileURLToPath(object? url)
        => global::JavaScriptRuntime.DotNet2JSConversions.ToString(fileURLToPath(url!));

    string UrlContract.fileURLToPath(object? url, object? options)
        => throw CreateNotImplementedException("fileURLToPath");

    global::JavaScriptRuntime.Node.Buffer UrlContract.fileURLToPathBuffer(object? url)
        => throw CreateNotImplementedException("fileURLToPathBuffer");

    global::JavaScriptRuntime.Node.Buffer UrlContract.fileURLToPathBuffer(object? url, object? options)
        => throw CreateNotImplementedException("fileURLToPathBuffer");

    string UrlContract.format(object? url)
        => throw CreateNotImplementedException("format");

    string UrlContract.format(object? url, object? options)
        => throw CreateNotImplementedException("format");

    object? UrlContract.pathToFileURL(string path)
        => pathToFileURL(path!);

    object? UrlContract.pathToFileURL(string path, object? options)
        => throw CreateNotImplementedException("pathToFileURL");

    object? UrlContract.urlToHttpOptions(object? url)
        => throw CreateNotImplementedException("urlToHttpOptions");

    object? UrlContract.parse(string urlString)
        => throw CreateNotImplementedException("parse");

    object? UrlContract.parse(string urlString, bool parseQueryString)
        => throw CreateNotImplementedException("parse");

    object? UrlContract.parse(string urlString, bool parseQueryString, bool slashesDenoteHost)
        => throw CreateNotImplementedException("parse");

    string UrlContract.resolve(string from, string to)
        => throw CreateNotImplementedException("resolve");

    private static global::System.NotImplementedException CreateNotImplementedException(string memberName)
        => new($"The intrinsic node:url module does not implement 'url.{memberName}'.");
}
