// <auto-generated />
// Generated from the official Node.js 24.18.1 util API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/util.json
// SHA-256: c5b022671190286c09675cae44732369d3ad0b25a4dd040e158dcc101ff26183

#nullable enable
#pragma warning disable CS0618

using UtilTypesContract = Jroc.Runtime.Node.Contracts.IUtilTypesModule;

namespace JavaScriptRuntime.Node;

public sealed partial class UtilTypesModule : UtilTypesContract
{
    bool UtilTypesContract.isAnyArrayBuffer(object? value)
        => global::JavaScriptRuntime.TypeUtilities.ToBoolean(ContractIsAnyArrayBuffer(value!));

    bool UtilTypesContract.isArrayBufferView(object? value)
        => global::JavaScriptRuntime.TypeUtilities.ToBoolean(ContractIsArrayBufferView(value!));

    bool UtilTypesContract.isArgumentsObject(object? value)
        => global::JavaScriptRuntime.TypeUtilities.ToBoolean(ContractIsArgumentsObject(value!));

    bool UtilTypesContract.isArrayBuffer(object? value)
        => global::JavaScriptRuntime.TypeUtilities.ToBoolean(ContractIsArrayBuffer(value!));

    bool UtilTypesContract.isAsyncFunction(object? value)
        => global::JavaScriptRuntime.TypeUtilities.ToBoolean(ContractIsAsyncFunction(value!));

    bool UtilTypesContract.isBigInt64Array(object? value)
        => global::JavaScriptRuntime.TypeUtilities.ToBoolean(ContractIsBigInt64Array(value!));

    bool UtilTypesContract.isBigIntObject(object? value)
        => throw CreateNotImplementedException("isBigIntObject");

    bool UtilTypesContract.isBigUint64Array(object? value)
        => global::JavaScriptRuntime.TypeUtilities.ToBoolean(ContractIsBigUint64Array(value!));

    bool UtilTypesContract.isBooleanObject(object? value)
        => throw CreateNotImplementedException("isBooleanObject");

    bool UtilTypesContract.isBoxedPrimitive(object? value)
        => throw CreateNotImplementedException("isBoxedPrimitive");

    bool UtilTypesContract.isCryptoKey(object? value)
        => global::JavaScriptRuntime.TypeUtilities.ToBoolean(ContractIsCryptoKey(value!));

    bool UtilTypesContract.isDataView(object? value)
        => global::JavaScriptRuntime.TypeUtilities.ToBoolean(ContractIsDataView(value!));

    bool UtilTypesContract.isDate(object? value)
        => global::JavaScriptRuntime.TypeUtilities.ToBoolean(ContractIsDate(value!));

    bool UtilTypesContract.isExternal(object? value)
        => global::JavaScriptRuntime.TypeUtilities.ToBoolean(ContractIsExternal(value!));

    bool UtilTypesContract.isFloat16Array(object? value)
        => global::JavaScriptRuntime.TypeUtilities.ToBoolean(ContractIsFloat16Array(value!));

    bool UtilTypesContract.isFloat32Array(object? value)
        => global::JavaScriptRuntime.TypeUtilities.ToBoolean(ContractIsFloat32Array(value!));

    bool UtilTypesContract.isFloat64Array(object? value)
        => global::JavaScriptRuntime.TypeUtilities.ToBoolean(ContractIsFloat64Array(value!));

    bool UtilTypesContract.isGeneratorFunction(object? value)
        => throw CreateNotImplementedException("isGeneratorFunction");

    bool UtilTypesContract.isGeneratorObject(object? value)
        => global::JavaScriptRuntime.TypeUtilities.ToBoolean(ContractIsGeneratorObject(value!));

    bool UtilTypesContract.isInt8Array(object? value)
        => global::JavaScriptRuntime.TypeUtilities.ToBoolean(ContractIsInt8Array(value!));

    bool UtilTypesContract.isInt16Array(object? value)
        => global::JavaScriptRuntime.TypeUtilities.ToBoolean(ContractIsInt16Array(value!));

    bool UtilTypesContract.isInt32Array(object? value)
        => global::JavaScriptRuntime.TypeUtilities.ToBoolean(ContractIsInt32Array(value!));

    bool UtilTypesContract.isKeyObject(object? value)
        => throw CreateNotImplementedException("isKeyObject");

    bool UtilTypesContract.isMap(object? value)
        => global::JavaScriptRuntime.TypeUtilities.ToBoolean(ContractIsMap(value!));

    bool UtilTypesContract.isMapIterator(object? value)
        => throw CreateNotImplementedException("isMapIterator");

    bool UtilTypesContract.isModuleNamespaceObject(object? value)
        => throw CreateNotImplementedException("isModuleNamespaceObject");

    bool UtilTypesContract.isNativeError(object? value)
        => global::JavaScriptRuntime.TypeUtilities.ToBoolean(ContractIsNativeError(value!));

    bool UtilTypesContract.isNumberObject(object? value)
        => throw CreateNotImplementedException("isNumberObject");

    bool UtilTypesContract.isPromise(object? value)
        => global::JavaScriptRuntime.TypeUtilities.ToBoolean(ContractIsPromise(value!));

    bool UtilTypesContract.isProxy(object? value)
        => global::JavaScriptRuntime.TypeUtilities.ToBoolean(ContractIsProxy(value!));

    bool UtilTypesContract.isRegExp(object? value)
        => global::JavaScriptRuntime.TypeUtilities.ToBoolean(ContractIsRegExp(value!));

    bool UtilTypesContract.isSet(object? value)
        => global::JavaScriptRuntime.TypeUtilities.ToBoolean(ContractIsSet(value!));

    bool UtilTypesContract.isSetIterator(object? value)
        => throw CreateNotImplementedException("isSetIterator");

    bool UtilTypesContract.isSharedArrayBuffer(object? value)
        => global::JavaScriptRuntime.TypeUtilities.ToBoolean(ContractIsSharedArrayBuffer(value!));

    bool UtilTypesContract.isStringObject(object? value)
        => throw CreateNotImplementedException("isStringObject");

    bool UtilTypesContract.isSymbolObject(object? value)
        => throw CreateNotImplementedException("isSymbolObject");

    bool UtilTypesContract.isTypedArray(object? value)
        => global::JavaScriptRuntime.TypeUtilities.ToBoolean(ContractIsTypedArray(value!));

    bool UtilTypesContract.isUint8Array(object? value)
        => global::JavaScriptRuntime.TypeUtilities.ToBoolean(ContractIsUint8Array(value!));

    bool UtilTypesContract.isUint8ClampedArray(object? value)
        => global::JavaScriptRuntime.TypeUtilities.ToBoolean(ContractIsUint8ClampedArray(value!));

    bool UtilTypesContract.isUint16Array(object? value)
        => global::JavaScriptRuntime.TypeUtilities.ToBoolean(ContractIsUint16Array(value!));

    bool UtilTypesContract.isUint32Array(object? value)
        => global::JavaScriptRuntime.TypeUtilities.ToBoolean(ContractIsUint32Array(value!));

    bool UtilTypesContract.isWeakMap(object? value)
        => global::JavaScriptRuntime.TypeUtilities.ToBoolean(ContractIsWeakMap(value!));

    bool UtilTypesContract.isWeakSet(object? value)
        => global::JavaScriptRuntime.TypeUtilities.ToBoolean(ContractIsWeakSet(value!));

    private static global::System.NotImplementedException CreateNotImplementedException(string memberName)
        => new($"The intrinsic node:util/types module does not implement 'util.types.{memberName}'.");
}
