// <auto-generated />
// Generated from the official Node.js 24.18.1 util API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/util.json
// SHA-256: c5b022671190286c09675cae44732369d3ad0b25a4dd040e158dcc101ff26183

#nullable enable
#pragma warning disable CS0618

using UtilContract = Jroc.Runtime.Node.Contracts.IUtilModule;

namespace JavaScriptRuntime.Node;

public sealed partial class Util : UtilContract
{
    object? UtilContract.types
        => types;

    object? UtilContract.MIMEType
        => throw CreateNotImplementedException("MIMEType");

    object? UtilContract.MIMEParams
        => throw CreateNotImplementedException("MIMEParams");

    object? UtilContract.TextDecoder
        => throw CreateNotImplementedException("TextDecoder");

    object? UtilContract.TextEncoder
        => throw CreateNotImplementedException("TextEncoder");

    global::System.Delegate UtilContract.callbackify(global::System.Delegate original)
        => throw CreateNotImplementedException("callbackify");

    double UtilContract.convertProcessSignalToExitCode(string signal)
        => throw CreateNotImplementedException("convertProcessSignalToExitCode");

    global::System.Delegate UtilContract.debuglog(string section)
        => throw CreateNotImplementedException("debuglog");

    global::System.Delegate UtilContract.debuglog(string section, object? callback)
        => throw CreateNotImplementedException("debuglog");

    global::System.Delegate UtilContract.deprecate(global::System.Delegate fn, string msg)
        => throw CreateNotImplementedException("deprecate");

    global::System.Delegate UtilContract.deprecate(global::System.Delegate fn, string msg, object? code)
        => throw CreateNotImplementedException("deprecate");

    global::System.Delegate UtilContract.deprecate(global::System.Delegate fn, string msg, object? code, object? options)
        => throw CreateNotImplementedException("deprecate");

    global::JavaScriptRuntime.IJavaScriptArray UtilContract.diff(object? actual, object? expected)
        => throw CreateNotImplementedException("diff");

    global::JavaScriptRuntime.IJavaScriptArray UtilContract.getCallSites()
        => throw CreateNotImplementedException("getCallSites");

    global::JavaScriptRuntime.IJavaScriptArray UtilContract.getCallSites(object? options)
        => throw CreateNotImplementedException("getCallSites");

    global::JavaScriptRuntime.IJavaScriptArray UtilContract.getCallSites(object? frameCount, object? options)
        => throw CreateNotImplementedException("getCallSites");

    string UtilContract.getSystemErrorName(double err)
        => throw CreateNotImplementedException("getSystemErrorName");

    object? UtilContract.getSystemErrorMap()
        => throw CreateNotImplementedException("getSystemErrorMap");

    string UtilContract.getSystemErrorMessage(double err)
        => throw CreateNotImplementedException("getSystemErrorMessage");

    void UtilContract.setTraceSigInt(bool enable)
        => throw CreateNotImplementedException("setTraceSigInt");

    void UtilContract.inherits(global::System.Delegate constructor, global::System.Delegate superConstructor)
        => _ = inherits(constructor!, superConstructor!);

    object? UtilContract.parseArgs()
        => throw CreateNotImplementedException("parseArgs");

    object? UtilContract.parseArgs(object? config)
        => throw CreateNotImplementedException("parseArgs");

    object? UtilContract.parseEnv(string content)
        => throw CreateNotImplementedException("parseEnv");

    global::System.Delegate UtilContract.promisify(global::System.Delegate original)
        => (global::System.Delegate)promisify(original!)!;

    string UtilContract.stripVTControlCharacters(string str)
        => throw CreateNotImplementedException("stripVTControlCharacters");

    string UtilContract.styleText(object? format, string text)
        => throw CreateNotImplementedException("styleText");

    string UtilContract.styleText(object? format, string text, object? options)
        => throw CreateNotImplementedException("styleText");

    string UtilContract.toUSVString(string @string)
        => throw CreateNotImplementedException("toUSVString");

    object? UtilContract.transferableAbortController()
        => throw CreateNotImplementedException("transferableAbortController");

    object? UtilContract.transferableAbortSignal(object? signal)
        => throw CreateNotImplementedException("transferableAbortSignal");

    global::JavaScriptRuntime.IJavaScriptPromise UtilContract.aborted(object? signal, object? resource)
        => throw CreateNotImplementedException("aborted");

    global::System.Delegate UtilContract.debug(string section)
        => throw CreateNotImplementedException("debug");

    string UtilContract.format(string format, params object?[] args)
        => global::JavaScriptRuntime.DotNet2JSConversions.ToString(ContractFormat(format!, args!));

    string UtilContract.formatWithOptions(object? inspectOptions, string format, params object?[] args)
        => throw CreateNotImplementedException("formatWithOptions");

    string UtilContract.inspect(object? value)
        => global::JavaScriptRuntime.DotNet2JSConversions.ToString(ContractInspect(value!));

    string UtilContract.inspect(object? value, object? optionsOrShowHidden)
        => global::JavaScriptRuntime.DotNet2JSConversions.ToString(ContractInspect(value!, optionsOrShowHidden!));

    string UtilContract.inspect(object? value, object? showHidden, object? depth)
        => global::JavaScriptRuntime.DotNet2JSConversions.ToString(ContractInspect(value!, showHidden!, depth!));

    string UtilContract.inspect(object? value, object? showHidden, object? depth, object? colors)
        => global::JavaScriptRuntime.DotNet2JSConversions.ToString(ContractInspect(value!, showHidden!, depth!, colors!));

    bool UtilContract.isDeepStrictEqual(object? val1, object? val2)
        => throw CreateNotImplementedException("isDeepStrictEqual");

    bool UtilContract.isDeepStrictEqual(object? val1, object? val2, object? options)
        => throw CreateNotImplementedException("isDeepStrictEqual");

    object? UtilContract._extend(object? target, object? source)
        => throw CreateNotImplementedException("_extend");

    bool UtilContract.isArray(object? @object)
        => throw CreateNotImplementedException("isArray");

    private static global::System.NotImplementedException CreateNotImplementedException(string memberName)
        => new($"The intrinsic node:util module does not implement 'util.{memberName}'.");
}
