// <auto-generated />
// Generated from the official Node.js 24.18.1 zlib API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/zlib.json
// SHA-256: 2dbd054fb3e17430614ef2c7200629cde1944b08f9fa4cb597ddd43f40277d92

#nullable enable
#pragma warning disable CS0618

using ZlibContract = Jroc.Runtime.Node.Contracts.IZlibModule;

namespace JavaScriptRuntime.Node;

public sealed partial class Zlib : ZlibContract
{
    double ZlibContract.ZSTD_btlazy2
        => throw CreateNotImplementedException("ZSTD_btlazy2");

    double ZlibContract.ZSTD_btopt
        => throw CreateNotImplementedException("ZSTD_btopt");

    double ZlibContract.ZSTD_btultra
        => throw CreateNotImplementedException("ZSTD_btultra");

    double ZlibContract.ZSTD_btultra2
        => throw CreateNotImplementedException("ZSTD_btultra2");

    double ZlibContract.ZSTD_c_checksumFlag
        => throw CreateNotImplementedException("ZSTD_c_checksumFlag");

    double ZlibContract.ZSTD_c_compressionLevel
        => throw CreateNotImplementedException("ZSTD_c_compressionLevel");

    double ZlibContract.ZSTD_c_strategy
        => throw CreateNotImplementedException("ZSTD_c_strategy");

    double ZlibContract.ZSTD_dfast
        => throw CreateNotImplementedException("ZSTD_dfast");

    double ZlibContract.ZSTD_e_continue
        => throw CreateNotImplementedException("ZSTD_e_continue");

    double ZlibContract.ZSTD_e_end
        => throw CreateNotImplementedException("ZSTD_e_end");

    double ZlibContract.ZSTD_e_flush
        => throw CreateNotImplementedException("ZSTD_e_flush");

    double ZlibContract.ZSTD_fast
        => throw CreateNotImplementedException("ZSTD_fast");

    double ZlibContract.ZSTD_greedy
        => throw CreateNotImplementedException("ZSTD_greedy");

    double ZlibContract.ZSTD_lazy
        => throw CreateNotImplementedException("ZSTD_lazy");

    double ZlibContract.ZSTD_lazy2
        => throw CreateNotImplementedException("ZSTD_lazy2");

    double ZlibContract.Z_BEST_COMPRESSION
        => throw CreateNotImplementedException("Z_BEST_COMPRESSION");

    double ZlibContract.Z_BEST_SPEED
        => throw CreateNotImplementedException("Z_BEST_SPEED");

    double ZlibContract.Z_BLOCK
        => throw CreateNotImplementedException("Z_BLOCK");

    double ZlibContract.Z_BUF_ERROR
        => throw CreateNotImplementedException("Z_BUF_ERROR");

    double ZlibContract.Z_DATA_ERROR
        => throw CreateNotImplementedException("Z_DATA_ERROR");

    double ZlibContract.Z_DEFAULT_COMPRESSION
        => throw CreateNotImplementedException("Z_DEFAULT_COMPRESSION");

    double ZlibContract.Z_DEFAULT_STRATEGY
        => throw CreateNotImplementedException("Z_DEFAULT_STRATEGY");

    double ZlibContract.Z_ERRNO
        => throw CreateNotImplementedException("Z_ERRNO");

    double ZlibContract.Z_FILTERED
        => throw CreateNotImplementedException("Z_FILTERED");

    double ZlibContract.Z_FINISH
        => throw CreateNotImplementedException("Z_FINISH");

    double ZlibContract.Z_FIXED
        => throw CreateNotImplementedException("Z_FIXED");

    double ZlibContract.Z_FULL_FLUSH
        => throw CreateNotImplementedException("Z_FULL_FLUSH");

    double ZlibContract.Z_HUFFMAN_ONLY
        => throw CreateNotImplementedException("Z_HUFFMAN_ONLY");

    double ZlibContract.Z_MEM_ERROR
        => throw CreateNotImplementedException("Z_MEM_ERROR");

    double ZlibContract.Z_NEED_DICT
        => throw CreateNotImplementedException("Z_NEED_DICT");

    double ZlibContract.Z_NO_COMPRESSION
        => throw CreateNotImplementedException("Z_NO_COMPRESSION");

    double ZlibContract.Z_NO_FLUSH
        => throw CreateNotImplementedException("Z_NO_FLUSH");

    double ZlibContract.Z_OK
        => throw CreateNotImplementedException("Z_OK");

    double ZlibContract.Z_PARTIAL_FLUSH
        => throw CreateNotImplementedException("Z_PARTIAL_FLUSH");

    double ZlibContract.Z_RLE
        => throw CreateNotImplementedException("Z_RLE");

    double ZlibContract.Z_STREAM_END
        => throw CreateNotImplementedException("Z_STREAM_END");

    double ZlibContract.Z_STREAM_ERROR
        => throw CreateNotImplementedException("Z_STREAM_ERROR");

    double ZlibContract.Z_SYNC_FLUSH
        => throw CreateNotImplementedException("Z_SYNC_FLUSH");

    double ZlibContract.Z_VERSION_ERROR
        => throw CreateNotImplementedException("Z_VERSION_ERROR");

    object? ZlibContract.constants
        => throw CreateNotImplementedException("constants");

    object? ZlibContract.codes
        => throw CreateNotImplementedException("codes");

    object? ZlibContract.BrotliCompress
        => throw CreateNotImplementedException("BrotliCompress");

    object? ZlibContract.BrotliDecompress
        => throw CreateNotImplementedException("BrotliDecompress");

    object? ZlibContract.Deflate
        => throw CreateNotImplementedException("Deflate");

    object? ZlibContract.DeflateRaw
        => throw CreateNotImplementedException("DeflateRaw");

    object? ZlibContract.Gunzip
        => throw CreateNotImplementedException("Gunzip");

    object? ZlibContract.Gzip
        => throw CreateNotImplementedException("Gzip");

    object? ZlibContract.Inflate
        => throw CreateNotImplementedException("Inflate");

    object? ZlibContract.InflateRaw
        => throw CreateNotImplementedException("InflateRaw");

    object? ZlibContract.Unzip
        => throw CreateNotImplementedException("Unzip");

    object? ZlibContract.ZstdCompress
        => throw CreateNotImplementedException("ZstdCompress");

    object? ZlibContract.ZstdDecompress
        => throw CreateNotImplementedException("ZstdDecompress");

    double ZlibContract.crc32(object? data)
        => throw CreateNotImplementedException("crc32");

    double ZlibContract.crc32(object? data, object? value)
        => throw CreateNotImplementedException("crc32");

    object? ZlibContract.createBrotliCompress()
        => throw CreateNotImplementedException("createBrotliCompress");

    object? ZlibContract.createBrotliCompress(object? options)
        => throw CreateNotImplementedException("createBrotliCompress");

    object? ZlibContract.createBrotliDecompress()
        => throw CreateNotImplementedException("createBrotliDecompress");

    object? ZlibContract.createBrotliDecompress(object? options)
        => throw CreateNotImplementedException("createBrotliDecompress");

    object? ZlibContract.createDeflate()
        => throw CreateNotImplementedException("createDeflate");

    object? ZlibContract.createDeflate(object? options)
        => throw CreateNotImplementedException("createDeflate");

    object? ZlibContract.createDeflateRaw()
        => throw CreateNotImplementedException("createDeflateRaw");

    object? ZlibContract.createDeflateRaw(object? options)
        => throw CreateNotImplementedException("createDeflateRaw");

    object? ZlibContract.createGunzip()
        => createGunzip();

    object? ZlibContract.createGunzip(object? options)
        => createGunzip(options!);

    object? ZlibContract.createGzip()
        => createGzip();

    object? ZlibContract.createGzip(object? options)
        => createGzip(options!);

    object? ZlibContract.createInflate()
        => throw CreateNotImplementedException("createInflate");

    object? ZlibContract.createInflate(object? options)
        => throw CreateNotImplementedException("createInflate");

    object? ZlibContract.createInflateRaw()
        => throw CreateNotImplementedException("createInflateRaw");

    object? ZlibContract.createInflateRaw(object? options)
        => throw CreateNotImplementedException("createInflateRaw");

    object? ZlibContract.createUnzip()
        => throw CreateNotImplementedException("createUnzip");

    object? ZlibContract.createUnzip(object? options)
        => throw CreateNotImplementedException("createUnzip");

    object? ZlibContract.createZstdCompress()
        => throw CreateNotImplementedException("createZstdCompress");

    object? ZlibContract.createZstdCompress(object? options)
        => throw CreateNotImplementedException("createZstdCompress");

    object? ZlibContract.createZstdDecompress()
        => throw CreateNotImplementedException("createZstdDecompress");

    object? ZlibContract.createZstdDecompress(object? options)
        => throw CreateNotImplementedException("createZstdDecompress");

    void ZlibContract.brotliCompress(object? buffer, global::System.Delegate callback)
        => throw CreateNotImplementedException("brotliCompress");

    void ZlibContract.brotliCompress(object? buffer, object? options, global::System.Delegate callback)
        => throw CreateNotImplementedException("brotliCompress");

    global::JavaScriptRuntime.Node.Buffer ZlibContract.brotliCompressSync(object? buffer)
        => throw CreateNotImplementedException("brotliCompressSync");

    global::JavaScriptRuntime.Node.Buffer ZlibContract.brotliCompressSync(object? buffer, object? options)
        => throw CreateNotImplementedException("brotliCompressSync");

    void ZlibContract.brotliDecompress(object? buffer, global::System.Delegate callback)
        => throw CreateNotImplementedException("brotliDecompress");

    void ZlibContract.brotliDecompress(object? buffer, object? options, global::System.Delegate callback)
        => throw CreateNotImplementedException("brotliDecompress");

    global::JavaScriptRuntime.Node.Buffer ZlibContract.brotliDecompressSync(object? buffer)
        => throw CreateNotImplementedException("brotliDecompressSync");

    global::JavaScriptRuntime.Node.Buffer ZlibContract.brotliDecompressSync(object? buffer, object? options)
        => throw CreateNotImplementedException("brotliDecompressSync");

    void ZlibContract.deflate(object? buffer, global::System.Delegate callback)
        => throw CreateNotImplementedException("deflate");

    void ZlibContract.deflate(object? buffer, object? options, global::System.Delegate callback)
        => throw CreateNotImplementedException("deflate");

    global::JavaScriptRuntime.Node.Buffer ZlibContract.deflateSync(object? buffer)
        => throw CreateNotImplementedException("deflateSync");

    global::JavaScriptRuntime.Node.Buffer ZlibContract.deflateSync(object? buffer, object? options)
        => throw CreateNotImplementedException("deflateSync");

    void ZlibContract.deflateRaw(object? buffer, global::System.Delegate callback)
        => throw CreateNotImplementedException("deflateRaw");

    void ZlibContract.deflateRaw(object? buffer, object? options, global::System.Delegate callback)
        => throw CreateNotImplementedException("deflateRaw");

    global::JavaScriptRuntime.Node.Buffer ZlibContract.deflateRawSync(object? buffer)
        => throw CreateNotImplementedException("deflateRawSync");

    global::JavaScriptRuntime.Node.Buffer ZlibContract.deflateRawSync(object? buffer, object? options)
        => throw CreateNotImplementedException("deflateRawSync");

    void ZlibContract.gunzip(object? buffer, global::System.Delegate callback)
        => throw CreateNotImplementedException("gunzip");

    void ZlibContract.gunzip(object? buffer, object? options, global::System.Delegate callback)
        => throw CreateNotImplementedException("gunzip");

    global::JavaScriptRuntime.Node.Buffer ZlibContract.gunzipSync(object? buffer)
        => (global::JavaScriptRuntime.Node.Buffer)gunzipSync(buffer!)!;

    global::JavaScriptRuntime.Node.Buffer ZlibContract.gunzipSync(object? buffer, object? options)
        => (global::JavaScriptRuntime.Node.Buffer)gunzipSync(buffer!, options!)!;

    void ZlibContract.gzip(object? buffer, global::System.Delegate callback)
        => throw CreateNotImplementedException("gzip");

    void ZlibContract.gzip(object? buffer, object? options, global::System.Delegate callback)
        => throw CreateNotImplementedException("gzip");

    global::JavaScriptRuntime.Node.Buffer ZlibContract.gzipSync(object? buffer)
        => (global::JavaScriptRuntime.Node.Buffer)gzipSync(buffer!)!;

    global::JavaScriptRuntime.Node.Buffer ZlibContract.gzipSync(object? buffer, object? options)
        => (global::JavaScriptRuntime.Node.Buffer)gzipSync(buffer!, options!)!;

    void ZlibContract.inflate(object? buffer, global::System.Delegate callback)
        => throw CreateNotImplementedException("inflate");

    void ZlibContract.inflate(object? buffer, object? options, global::System.Delegate callback)
        => throw CreateNotImplementedException("inflate");

    global::JavaScriptRuntime.Node.Buffer ZlibContract.inflateSync(object? buffer)
        => throw CreateNotImplementedException("inflateSync");

    global::JavaScriptRuntime.Node.Buffer ZlibContract.inflateSync(object? buffer, object? options)
        => throw CreateNotImplementedException("inflateSync");

    void ZlibContract.inflateRaw(object? buffer, global::System.Delegate callback)
        => throw CreateNotImplementedException("inflateRaw");

    void ZlibContract.inflateRaw(object? buffer, object? options, global::System.Delegate callback)
        => throw CreateNotImplementedException("inflateRaw");

    global::JavaScriptRuntime.Node.Buffer ZlibContract.inflateRawSync(object? buffer)
        => throw CreateNotImplementedException("inflateRawSync");

    global::JavaScriptRuntime.Node.Buffer ZlibContract.inflateRawSync(object? buffer, object? options)
        => throw CreateNotImplementedException("inflateRawSync");

    void ZlibContract.unzip(object? buffer, global::System.Delegate callback)
        => throw CreateNotImplementedException("unzip");

    void ZlibContract.unzip(object? buffer, object? options, global::System.Delegate callback)
        => throw CreateNotImplementedException("unzip");

    global::JavaScriptRuntime.Node.Buffer ZlibContract.unzipSync(object? buffer)
        => throw CreateNotImplementedException("unzipSync");

    global::JavaScriptRuntime.Node.Buffer ZlibContract.unzipSync(object? buffer, object? options)
        => throw CreateNotImplementedException("unzipSync");

    void ZlibContract.zstdCompress(object? buffer, global::System.Delegate callback)
        => throw CreateNotImplementedException("zstdCompress");

    void ZlibContract.zstdCompress(object? buffer, object? options, global::System.Delegate callback)
        => throw CreateNotImplementedException("zstdCompress");

    global::JavaScriptRuntime.Node.Buffer ZlibContract.zstdCompressSync(object? buffer)
        => throw CreateNotImplementedException("zstdCompressSync");

    global::JavaScriptRuntime.Node.Buffer ZlibContract.zstdCompressSync(object? buffer, object? options)
        => throw CreateNotImplementedException("zstdCompressSync");

    void ZlibContract.zstdDecompress(object? buffer, global::System.Delegate callback)
        => throw CreateNotImplementedException("zstdDecompress");

    void ZlibContract.zstdDecompress(object? buffer, object? options, global::System.Delegate callback)
        => throw CreateNotImplementedException("zstdDecompress");

    global::JavaScriptRuntime.Node.Buffer ZlibContract.zstdDecompressSync(object? buffer)
        => throw CreateNotImplementedException("zstdDecompressSync");

    global::JavaScriptRuntime.Node.Buffer ZlibContract.zstdDecompressSync(object? buffer, object? options)
        => throw CreateNotImplementedException("zstdDecompressSync");

    private static global::System.NotImplementedException CreateNotImplementedException(string memberName)
        => new($"The intrinsic node:zlib module does not implement 'zlib.{memberName}'.");
}
