#!/usr/bin/env node
"use strict";

/**
 * Generates markdown files from individual Node.js module/global JSON files.
 * 
 * Usage:
 *   node scripts/generateNodeModuleDocs.js                # Generate all
 *   node scripts/generateNodeModuleDocs.js --module path  # Generate specific module
 */

const fs = require('fs');
const path = require('path');

function parseArgs(argv) {
  const args = {
    module: null,
    help: false,
  };

  for (let i = 2; i < argv.length; i++) {
    const a = argv[i];

    if (a === '--help' || a === '-h') {
      args.help = true;
      continue;
    }

    if (a === '--module' || a === '-m') {
      args.module = argv[i + 1] || '';
      i++;
      continue;
    }

    if (a.startsWith('--module=')) {
      args.module = a.substring('--module='.length);
      continue;
    }

    // Allow positional module argument
    if (!a.startsWith('-') && !args.module) {
      args.module = a;
      continue;
    }
  }

  return args;
}

function sanitizeFileName(name) {
  return name.replace(/[\/\.]/g, '_');
}

function asArray(v) {
  return Array.isArray(v) ? v : (v == null ? [] : [v]);
}

function fmtCode(s) {
  return s ? '`' + s + '`' : '';
}

function link(href, text) {
  return href ? `[${text || href}](${href})` : (text || '');
}

function renderImplementation(impl) {
  const parts = asArray(impl);
  if (!parts.length) return '';
  return parts.map(p => `- ${fmtCode(p)}`).join('\n');
}

function renderApisTable(apis) {
  if (!apis || !apis.length) return '';
  const rows = [];
  rows.push('| API | Kind | Status | Docs |');
  rows.push('| --- | ---- | ------ | ---- |');
  for (const api of apis) {
    const name = api.name || '';
    const kind = api.kind || '';
    const status = api.status || '';
    const docs = api.docs ? link(api.docs, 'docs') : '';
    rows.push(`| ${name} | ${kind} | ${status} | ${docs} |`);
  }
  return rows.join('\n');
}

function renderApiDetails(apis) {
  if (!apis || !apis.length) return '';
  const lines = [];
  
  for (const api of apis) {
    if (!api.notes && (!api.tests || !api.tests.length)) continue;
    
    lines.push(`### ${api.name}`);
    lines.push('');
    
    if (api.notes) {
      lines.push(api.notes);
      lines.push('');
    }
    
    if (api.tests && api.tests.length) {
      lines.push('**Tests:**');
      for (const t of api.tests) {
        const label = t.name ? fmtCode(t.name) : '';
        const file = t.file ? ` (${fmtCode(t.file)})` : '';
        lines.push(`- ${label}${file}`);
      }
      lines.push('');
    }
  }
  
  return lines.join('\n');
}

function renderGlobalTests(tests) {
  if (!tests || !tests.length) return '';
  const lines = ['## Tests', ''];
  for (const t of tests) {
    const label = t.name ? fmtCode(t.name) : '';
    const file = t.file ? ` (${fmtCode(t.file)})` : '';
    lines.push(`- ${label}${file}`);
  }
  return lines.join('\n');
}

function generateMarkdown(doc) {
  const lines = [];
  
  if (doc.autoGeneratedHeader !== false) {
    lines.push('<!-- AUTO-GENERATED: generateNodeModuleDocs.js -->');
    lines.push('');
  }
  
  // Title
  const typeLabel = doc.type === 'module' ? 'Module' : 'Global';
  lines.push(`# ${typeLabel}: ${doc.name}`);
  lines.push('');
  
  // Back link
  lines.push('[Back to Index](Index.md)');
  lines.push('');
  
  // Metadata table
  lines.push('| Property | Value |');
  lines.push('| --- | --- |');
  lines.push(`| Type | ${doc.type} |`);
  lines.push(`| Status | ${doc.status} |`);
  lines.push(`| Node.js Version | ${doc.nodeVersionTarget} |`);
  if (doc.docsUrl) {
    lines.push(`| Documentation | ${link(doc.docsUrl, 'Node.js Docs')} |`);
  }
  lines.push('');
  
  // Implementation
  if (doc.implementation) {
    lines.push('## Implementation');
    lines.push('');
    lines.push(renderImplementation(doc.implementation));
    lines.push('');
  }
  
  // Notes
  if (doc.notes) {
    lines.push('## Notes');
    lines.push('');
    lines.push(doc.notes);
    lines.push('');
  }
  
  // APIs (for modules)
  if (doc.type === 'module' && doc.apis && doc.apis.length > 0) {
    lines.push('## APIs');
    lines.push('');
    lines.push(renderApisTable(doc.apis));
    lines.push('');
    
    const details = renderApiDetails(doc.apis);
    if (details) {
      lines.push('## API Details');
      lines.push('');
      lines.push(details);
    }
  }
  
  // Tests (for globals)
  if (doc.type === 'global' && doc.tests && doc.tests.length > 0) {
    const testsSection = renderGlobalTests(doc.tests);
    if (testsSection) {
      lines.push(testsSection);
      lines.push('');
    }
  }
  
  return lines.join('\n');
}

function processFile(jsonPath, nodejsDir) {
  const doc = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));
  const baseName = path.basename(jsonPath, '.json');
  const mdPath = path.join(nodejsDir, baseName + '.md');
  
  const markdown = generateMarkdown(doc);
  fs.writeFileSync(mdPath, markdown, 'utf8');
  
  return path.basename(mdPath);
}

function main() {
  const args = parseArgs(process.argv);
  
  if (args.help) {
    console.log('Generate markdown documentation from Node.js module/global JSON files.');
    console.log('');
    console.log('Usage:');
    console.log('  node scripts/generateNodeModuleDocs.js              # Generate all');
    console.log('  node scripts/generateNodeModuleDocs.js --module fs  # Generate specific');
    console.log('');
    process.exit(0);
  }
  
  const repoRoot = path.resolve(__dirname, '..');
  const nodejsDir = path.join(repoRoot, 'docs', 'nodejs');
  
  let jsonFiles = [];
  
  if (args.module) {
    // Generate specific module
    const fileName = sanitizeFileName(args.module) + '.json';
    const filePath = path.join(nodejsDir, fileName);
    
    if (!fs.existsSync(filePath)) {
      console.error(`Error: Module file not found: ${fileName}`);
      process.exit(1);
    }
    
    jsonFiles = [filePath];
  } else {
    // Generate all modules
    const allFiles = fs.readdirSync(nodejsDir);
    jsonFiles = allFiles
      .filter(f => f.endsWith('.json'))
      .filter(f => f !== 'NodeSupport.json' && 
                   f !== 'NodeSupport.schema.json' && 
                   f !== 'ModuleDoc.schema.json' &&
                   f !== 'NodeLimitations.json')
      .map(f => path.join(nodejsDir, f));
  }
  
  console.log(`Generating markdown for ${jsonFiles.length} file(s)...\n`);
  
  let generated = 0;
  for (const jsonPath of jsonFiles) {
    try {
      const mdFile = processFile(jsonPath, nodejsDir);
      console.log(`  ✓ ${mdFile}`);
      generated++;
    } catch (err) {
      console.error(`  ✗ ${path.basename(jsonPath)}: ${err.message}`);
    }
  }
  
  console.log(`\nGenerated ${generated} markdown file(s)`);
}

main();
