// <auto-generated />
// Generated from the official Node.js 24.18.1 fs API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/fs.json
// SHA-256: 3145e3751afc28b868f9b481788a081fd87adf3215aa638f850fcb52d636ab6b

#nullable enable

namespace Jroc.Runtime.Node.Contracts;

[global::System.CodeDom.Compiler.GeneratedCode("generateNodeModuleInterface.js", "sha256:9126c7db48fedfbf7645d8b0f91f5cd9ce18f98db5f0ed246b9e0b8eee2b872d")]
public static class FsNestedContractAdapters
{
    public static IFsReadFileOptions AsFsReadFileOptions(object? value)
        => value as IFsReadFileOptions ?? new FsReadFileOptionsHost(value);

    private sealed class FsReadFileOptionsHost : IFsReadFileOptions
    {
        private readonly object? _value;

        public FsReadFileOptionsHost(object? value)
        {
            _value = value;
        }

        object? IJavaScriptValueHost.JavaScriptValue => _value;

        public object? encoding
            => (object?)global::JavaScriptRuntime.ObjectRuntime.GetProperty(_value!, "encoding")!;

        public object? flag
            => (object?)global::JavaScriptRuntime.ObjectRuntime.GetProperty(_value!, "flag")!;

    }

    public static IFsWriteFileOptions AsFsWriteFileOptions(object? value)
        => value as IFsWriteFileOptions ?? new FsWriteFileOptionsHost(value);

    private sealed class FsWriteFileOptionsHost : IFsWriteFileOptions
    {
        private readonly object? _value;

        public FsWriteFileOptionsHost(object? value)
        {
            _value = value;
        }

        object? IJavaScriptValueHost.JavaScriptValue => _value;

        public object? encoding
            => (object?)global::JavaScriptRuntime.ObjectRuntime.GetProperty(_value!, "encoding")!;

        public object? mode
            => (object?)global::JavaScriptRuntime.ObjectRuntime.GetProperty(_value!, "mode")!;

        public object? flag
            => (object?)global::JavaScriptRuntime.ObjectRuntime.GetProperty(_value!, "flag")!;

        public bool flush
            => global::JavaScriptRuntime.TypeUtilities.ToBoolean(global::JavaScriptRuntime.ObjectRuntime.GetProperty(_value!, "flush"));

    }

}
