// <auto-generated />
// Generated from the official Node.js 24.18.1 async_hooks API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/async_hooks.json
// SHA-256: d5bd9fd8a8feef7a6a666cfdb96b7b4094a062f6b0a594141f485095cf834dd3

#nullable enable

namespace Jroc.Runtime.Node.Contracts;

/// <summary>
/// Defines the documented <c>node:async_hooks.AsyncHook</c> contract.
/// </summary>
/// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/async_hooks.html#class-asynchook</c>.</remarks>
[global::System.CodeDom.Compiler.GeneratedCode("generateNodeModuleInterface.js", "sha256:2e1877a88a0be5be6f1ce68d6801f81345518c2272d2b70984df61b7ca02aca0")]
[NodeModuleType("async_hooks", "AsyncHook")]
public interface IAsyncHook : IJavaScriptValueHost
{
    /// <summary>
    /// Node.js signature: <c>asyncHook.enable()</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/async_hooks.html#asynchookenable</c>.</remarks>
    [NodeModuleMember("enable")]
    object? enable();

    /// <summary>
    /// Node.js signature: <c>asyncHook.disable()</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/async_hooks.html#asynchookdisable</c>.</remarks>
    [NodeModuleMember("disable")]
    object? disable();

}
