// <auto-generated />
// Generated from the official Node.js 24.18.1 async_hooks API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/async_hooks.json
// SHA-256: d5bd9fd8a8feef7a6a666cfdb96b7b4094a062f6b0a594141f485095cf834dd3

#nullable enable

namespace Jroc.Runtime.Node.Contracts;

/// <summary>
/// Defines the public top-level <c>node:async_hooks</c> module contract from Node.js 24.18.1.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCode("generateNodeModuleInterface.js", "sha256:9126c7db48fedfbf7645d8b0f91f5cd9ce18f98db5f0ed246b9e0b8eee2b872d")]
[NodeModuleInterface("async_hooks")]
public interface IAsyncHooksModule
{
    /// <summary>
    /// Gets the exported <c>async_hooks.AsyncResource</c> member.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/async_context.html#class-asyncresource</c>.</remarks>
    [NodeModuleMember("AsyncResource")]
    object? AsyncResource { get; }

    /// <summary>
    /// Gets the exported <c>async_hooks.AsyncLocalStorage</c> member.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/async_context.html#class-asynclocalstorage</c>.</remarks>
    [NodeModuleMember("AsyncLocalStorage")]
    object? AsyncLocalStorage { get; }

    /// <summary>
    /// Gets the exported <c>async_hooks.asyncWrapProviders</c> member.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/async_hooks.html#async_hooksasyncwrapproviders</c>.</remarks>
    [NodeModuleMember("asyncWrapProviders")]
    object? asyncWrapProviders { get; }

    // node:async_hooks methods
    /// <summary>
    /// Node.js signature: <c>async_hooks.createHook(options)</c>.
    /// </summary>
    [NodeModuleMember("createHook")]
    object? createHook(object? options);

    /// <summary>
    /// Node.js signature: <c>async_hooks.executionAsyncId()</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/async_hooks.html#async_hooksexecutionasyncid</c>.</remarks>
    [NodeModuleMember("executionAsyncId")]
    double executionAsyncId();

    /// <summary>
    /// Node.js signature: <c>async_hooks.triggerAsyncId()</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/async_hooks.html#async_hookstriggerasyncid</c>.</remarks>
    [NodeModuleMember("triggerAsyncId")]
    double triggerAsyncId();

    /// <summary>
    /// Node.js signature: <c>async_hooks.executionAsyncResource()</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/async_hooks.html#async_hooksexecutionasyncresource</c>.</remarks>
    [NodeModuleMember("executionAsyncResource")]
    object? executionAsyncResource();

}
