// <auto-generated />
// Generated from the official Node.js 24.18.1 async_context API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/async_context.json
// SHA-256: 2a98c3110f798c9a94cb47d77a9e0d4cea2289ea0a7929bdfe557c2d1369714d

#nullable enable

namespace Jroc.Runtime.Node.Contracts;

/// <summary>
/// Defines the documented <c>node:async_hooks.AsyncLocalStorage</c> contract.
/// </summary>
/// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/async_context.html#class-asynclocalstorage</c>.</remarks>
[global::System.CodeDom.Compiler.GeneratedCode("generateNodeModuleInterface.js", "sha256:2e1877a88a0be5be6f1ce68d6801f81345518c2272d2b70984df61b7ca02aca0")]
[NodeModuleType("async_hooks", "AsyncLocalStorage")]
public interface IAsyncLocalStorage : IJavaScriptValueHost
{
    /// <summary>
    /// Gets <c>name</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/async_context.html#asynclocalstoragename</c>.</remarks>
    [NodeModuleMember("name")]
    string name { get; }

    /// <summary>
    /// Node.js signature: <c>asyncLocalStorage.disable()</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/async_context.html#asynclocalstoragedisable</c>.</remarks>
    [NodeModuleMember("disable")]
    object? disable();

    /// <summary>
    /// Node.js signature: <c>asyncLocalStorage.getStore()</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/async_context.html#asynclocalstoragegetstore</c>.</remarks>
    [NodeModuleMember("getStore")]
    object? getStore();

    /// <summary>
    /// Node.js signature: <c>asyncLocalStorage.enterWith(store)</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/async_context.html#asynclocalstorageenterwithstore</c>.</remarks>
    [NodeModuleMember("enterWith")]
    object? enterWith(object? store);

    /// <summary>
    /// Node.js signature: <c>asyncLocalStorage.run(store, callback[, ...args])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/async_context.html#asynclocalstoragerunstore-callback-args</c>.</remarks>
    [NodeModuleMember("run")]
    object? run(object? store, global::System.Delegate callback, params object?[] args);

    /// <summary>
    /// Node.js signature: <c>asyncLocalStorage.exit(callback[, ...args])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/async_context.html#asynclocalstorageexitcallback-args</c>.</remarks>
    [NodeModuleMember("exit")]
    object? exit(global::System.Delegate callback, params object?[] args);

}
