// <auto-generated />
// Generated from the official Node.js 24.18.1 async_context API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/async_context.json
// SHA-256: 2a98c3110f798c9a94cb47d77a9e0d4cea2289ea0a7929bdfe557c2d1369714d

#nullable enable

namespace Jroc.Runtime.Node.Contracts;

/// <summary>
/// Defines the documented <c>node:async_hooks.AsyncResource</c> contract.
/// </summary>
/// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/async_context.html#class-asyncresource</c>.</remarks>
[global::System.CodeDom.Compiler.GeneratedCode("generateNodeModuleInterface.js", "sha256:de7d46c347d581581a76dc391aa1fcd75d184d772e05ee622c88f4c5b6aa96ad")]
[NodeModuleType("async_hooks", "AsyncResource")]
public interface IAsyncResource : IJavaScriptValueHost
{
    /// <summary>
    /// Node.js signature: <c>asyncResource.bind(fn[, thisArg])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/async_context.html#asyncresourcebindfn-thisarg</c>.</remarks>
    [NodeModuleMember("bind")]
    global::System.Delegate bind(global::System.Delegate fn);

    /// <summary>
    /// Node.js signature: <c>asyncResource.bind(fn[, thisArg])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/async_context.html#asyncresourcebindfn-thisarg</c>.</remarks>
    [NodeModuleMember("bind")]
    global::System.Delegate bind(global::System.Delegate fn, object? thisArg);

    /// <summary>
    /// Node.js signature: <c>asyncResource.runInAsyncScope(fn[, thisArg, ...args])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/async_context.html#asyncresourceruninasyncscopefn-thisarg-args</c>.</remarks>
    [NodeModuleMember("runInAsyncScope")]
    object? runInAsyncScope(global::System.Delegate fn);

    /// <summary>
    /// Node.js signature: <c>asyncResource.runInAsyncScope(fn[, thisArg, ...args])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/async_context.html#asyncresourceruninasyncscopefn-thisarg-args</c>.</remarks>
    [NodeModuleMember("runInAsyncScope")]
    object? runInAsyncScope(global::System.Delegate fn, object? thisArg, params object?[] args);

    /// <summary>
    /// Node.js signature: <c>asyncResource.emitDestroy()</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/async_context.html#asyncresourceemitdestroy</c>.</remarks>
    [NodeModuleMember("emitDestroy")]
    object? emitDestroy();

    /// <summary>
    /// Node.js signature: <c>asyncResource.asyncId()</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/async_context.html#asyncresourceasyncid</c>.</remarks>
    [NodeModuleMember("asyncId")]
    double asyncId();

    /// <summary>
    /// Node.js signature: <c>asyncResource.triggerAsyncId()</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/async_context.html#asyncresourcetriggerasyncid</c>.</remarks>
    [NodeModuleMember("triggerAsyncId")]
    double triggerAsyncId();

}
