// <auto-generated />
// Generated from the official Node.js 24.18.1 buffer API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/buffer.json
// SHA-256: 3ad0db0620e96f0e06fc666a787a7d19cbb99f3e47fd4b17d9725df12ccd361a

#nullable enable

namespace Jroc.Runtime.Node.Contracts;

/// <summary>
/// Defines the public top-level <c>node:buffer</c> module contract from Node.js 24.18.1.
/// </summary>
/// <remarks>
/// Nested option, result, and handle contracts intentionally remain dynamic in this proof of concept.
/// They will be strongly typed by the work tracked in GitHub issue #1660.
/// </remarks>
[global::System.CodeDom.Compiler.GeneratedCode("generateNodeModuleInterface.js", "sha256:be6e78d5530a6d86fe34cd3cb26bca862717703f0617ff439ff5d5caa18b8c25")]
[NodeModuleInterface("buffer")]
public interface IBufferModule
{
    /// <summary>
    /// Node.js property: <c>`INSPECT_MAX_BYTES` Type: {integer} **Default:** `50`</c>.
    /// </summary>
    [NodeModuleMember("INSPECT_MAX_BYTES")]
    double INSPECT_MAX_BYTES { get; set; }

    /// <summary>
    /// Node.js property: <c>`kMaxLength` Type: {integer} The largest size allowed for a single `Buffer` instance.</c>.
    /// </summary>
    [NodeModuleMember("kMaxLength")]
    double kMaxLength { get; }

    /// <summary>
    /// Node.js property: <c>`kStringMaxLength` Type: {integer} The largest length allowed for a single `string` instance.</c>.
    /// </summary>
    [NodeModuleMember("kStringMaxLength")]
    double kStringMaxLength { get; }

    /// <summary>
    /// Gets the exported Buffer constructor.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/buffer.html#class-buffer</c>.</remarks>
    [NodeModuleMember("Buffer")]
    object? Buffer { get; }

    /// <summary>
    /// Gets the deprecated SlowBuffer constructor.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/buffer.html#class-slowbuffer</c>.</remarks>
    [global::System.Obsolete("Deprecated by Node.js since v6.0.0.")]
    [NodeModuleMember("SlowBuffer")]
    object? SlowBuffer { get; }

    /// <summary>
    /// Gets the exported Blob constructor.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/buffer.html#class-blob</c>.</remarks>
    [NodeModuleMember("Blob")]
    object? Blob { get; }

    /// <summary>
    /// Gets the exported File constructor.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/buffer.html#class-file</c>.</remarks>
    [NodeModuleMember("File")]
    object? File { get; }

    /// <summary>
    /// Gets the exported buffer constants object.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/buffer.html#buffer-constants</c>.</remarks>
    [NodeModuleMember("constants")]
    object? constants { get; }

    // Buffer module methods
    /// <summary>
    /// Node.js signature: <c>buffer.atob(data)</c>.
    /// </summary>
    [NodeModuleMember("atob")]
    string atob(object? data);

    /// <summary>
    /// Node.js signature: <c>buffer.btoa(data)</c>.
    /// </summary>
    [NodeModuleMember("btoa")]
    string btoa(object? data);

    /// <summary>
    /// Node.js signature: <c>buffer.isAscii(input)</c>.
    /// </summary>
    [NodeModuleMember("isAscii")]
    bool isAscii(object? input);

    /// <summary>
    /// Node.js signature: <c>buffer.isUtf8(input)</c>.
    /// </summary>
    [NodeModuleMember("isUtf8")]
    bool isUtf8(object? input);

    /// <summary>
    /// Node.js signature: <c>buffer.resolveObjectURL(id)</c>.
    /// </summary>
    [NodeModuleMember("resolveObjectURL")]
    object? resolveObjectURL(string id);

    /// <summary>
    /// Node.js signature: <c>buffer.transcode(source, fromEnc, toEnc)</c>.
    /// </summary>
    [NodeModuleMember("transcode")]
    global::JavaScriptRuntime.Node.Buffer transcode(object? source, string fromEnc, string toEnc);

}
