// <auto-generated />
// Generated from the official Node.js 24.18.1 crypto API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/crypto.json
// SHA-256: 34d332169d5a3915ce9f8ad3becd4a1fba34fac7dd487bb7b5a4fc99a01d207c

#nullable enable

namespace Jroc.Runtime.Node.Contracts;

/// <summary>
/// Defines the public top-level <c>node:crypto</c> module contract from Node.js 24.18.1.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCode("generateNodeModuleInterface.js", "sha256:9126c7db48fedfbf7645d8b0f91f5cd9ce18f98db5f0ed246b9e0b8eee2b872d")]
[NodeModuleInterface("crypto")]
public interface ICryptoModule
{
    /// <summary>
    /// Gets the exported <c>crypto.constants</c> member.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/crypto.html#cryptoconstants</c>.</remarks>
    [NodeModuleMember("constants")]
    object? constants { get; }

    /// <summary>
    /// Gets the exported <c>crypto.subtle</c> member.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/crypto.html#cryptosubtle</c>.</remarks>
    [NodeModuleMember("subtle")]
    object? subtle { get; }

    /// <summary>
    /// Gets the exported <c>crypto.webcrypto</c> member.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/crypto.html#cryptowebcrypto</c>.</remarks>
    [NodeModuleMember("webcrypto")]
    object? webcrypto { get; }

    /// <summary>
    /// Gets the deprecated <c>crypto.fips</c> constant.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/crypto.html#cryptofips</c>.</remarks>
    [global::System.Obsolete("Use crypto.getFips() and crypto.setFips() instead.")]
    [NodeModuleMember("fips")]
    double fips { get; set; }

    /// <summary>
    /// Gets the exported <c>crypto.Certificate</c> member.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/crypto.html#class-certificate</c>.</remarks>
    [NodeModuleMember("Certificate")]
    object? Certificate { get; }

    /// <summary>
    /// Gets the exported <c>crypto.Cipheriv</c> member.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/crypto.html#class-cipheriv</c>.</remarks>
    [NodeModuleMember("Cipheriv")]
    object? Cipheriv { get; }

    /// <summary>
    /// Gets the exported <c>crypto.Decipheriv</c> member.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/crypto.html#class-decipheriv</c>.</remarks>
    [NodeModuleMember("Decipheriv")]
    object? Decipheriv { get; }

    /// <summary>
    /// Gets the exported <c>crypto.DiffieHellman</c> member.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/crypto.html#class-diffiehellman</c>.</remarks>
    [NodeModuleMember("DiffieHellman")]
    object? DiffieHellman { get; }

    /// <summary>
    /// Gets the exported <c>crypto.DiffieHellmanGroup</c> member.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/crypto.html#class-diffiehellmangroup</c>.</remarks>
    [NodeModuleMember("DiffieHellmanGroup")]
    object? DiffieHellmanGroup { get; }

    /// <summary>
    /// Gets the exported <c>crypto.ECDH</c> member.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/crypto.html#class-ecdh</c>.</remarks>
    [NodeModuleMember("ECDH")]
    object? ECDH { get; }

    /// <summary>
    /// Gets the deprecated <c>crypto.Hash</c> constant.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/crypto.html#class-hash</c>.</remarks>
    [global::System.Obsolete("The crypto.Hash constructor is deprecated.")]
    [NodeModuleMember("Hash")]
    object? Hash { get; }

    /// <summary>
    /// Gets the deprecated <c>crypto.Hmac</c> constant.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/crypto.html#class-hmac</c>.</remarks>
    [global::System.Obsolete("The crypto.Hmac constructor is deprecated.")]
    [NodeModuleMember("Hmac")]
    object? Hmac { get; }

    /// <summary>
    /// Gets the exported <c>crypto.KeyObject</c> member.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/crypto.html#class-keyobject</c>.</remarks>
    [NodeModuleMember("KeyObject")]
    object? KeyObject { get; }

    /// <summary>
    /// Gets the exported <c>crypto.Sign</c> member.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/crypto.html#class-sign</c>.</remarks>
    [NodeModuleMember("Sign")]
    object? Sign { get; }

    /// <summary>
    /// Gets the exported <c>crypto.Verify</c> member.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/crypto.html#class-verify</c>.</remarks>
    [NodeModuleMember("Verify")]
    object? Verify { get; }

    /// <summary>
    /// Gets the exported <c>crypto.X509Certificate</c> member.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/crypto.html#class-x509certificate</c>.</remarks>
    [NodeModuleMember("X509Certificate")]
    object? X509Certificate { get; }

    // node:crypto methods
    /// <summary>
    /// Node.js signature: <c>crypto.argon2(algorithm, parameters, callback)</c>.
    /// </summary>
    [NodeModuleMember("argon2")]
    void argon2(string algorithm, object? parameters, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>crypto.argon2Sync(algorithm, parameters)</c>.
    /// </summary>
    [NodeModuleMember("argon2Sync")]
    global::JavaScriptRuntime.Node.Buffer argon2Sync(string algorithm, object? parameters);

    /// <summary>
    /// Node.js signature: <c>crypto.checkPrime(candidate[, options], callback)</c>.
    /// </summary>
    [NodeModuleMember("checkPrime")]
    void checkPrime(object? candidate, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>crypto.checkPrime(candidate[, options], callback)</c>.
    /// </summary>
    [NodeModuleMember("checkPrime")]
    void checkPrime(object? candidate, object? options, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>crypto.checkPrimeSync(candidate[, options])</c>.
    /// </summary>
    [NodeModuleMember("checkPrimeSync")]
    bool checkPrimeSync(object? candidate);

    /// <summary>
    /// Node.js signature: <c>crypto.checkPrimeSync(candidate[, options])</c>.
    /// </summary>
    [NodeModuleMember("checkPrimeSync")]
    bool checkPrimeSync(object? candidate, object? options);

    /// <summary>
    /// Node.js signature: <c>crypto.createCipheriv(algorithm, key, iv[, options])</c>.
    /// </summary>
    [NodeModuleMember("createCipheriv")]
    object? createCipheriv(string algorithm, object? key, object? iv);

    /// <summary>
    /// Node.js signature: <c>crypto.createCipheriv(algorithm, key, iv[, options])</c>.
    /// </summary>
    [NodeModuleMember("createCipheriv")]
    object? createCipheriv(string algorithm, object? key, object? iv, object? options);

    /// <summary>
    /// Node.js signature: <c>crypto.createDecipheriv(algorithm, key, iv[, options])</c>.
    /// </summary>
    [NodeModuleMember("createDecipheriv")]
    object? createDecipheriv(string algorithm, object? key, object? iv);

    /// <summary>
    /// Node.js signature: <c>crypto.createDecipheriv(algorithm, key, iv[, options])</c>.
    /// </summary>
    [NodeModuleMember("createDecipheriv")]
    object? createDecipheriv(string algorithm, object? key, object? iv, object? options);

    /// <summary>
    /// Node.js signature: <c>crypto.createDiffieHellman(prime[, primeEncoding][, generator][, generatorEncoding])</c>.
    /// </summary>
    [NodeModuleMember("createDiffieHellman")]
    object? createDiffieHellman(object? prime);

    /// <summary>
    /// Node.js signature: <c>crypto.createDiffieHellman(prime[, primeEncoding][, generator][, generatorEncoding])</c>.
    /// </summary>
    [NodeModuleMember("createDiffieHellman")]
    object? createDiffieHellman(object? prime, object? generatorEncoding);

    /// <summary>
    /// Node.js signature: <c>crypto.createDiffieHellman(prime[, primeEncoding][, generator][, generatorEncoding])</c>.
    /// </summary>
    [NodeModuleMember("createDiffieHellman")]
    object? createDiffieHellman(object? prime, object? generator, object? generatorEncoding);

    /// <summary>
    /// Node.js signature: <c>crypto.createDiffieHellman(prime[, primeEncoding][, generator][, generatorEncoding])</c>.
    /// </summary>
    [NodeModuleMember("createDiffieHellman")]
    object? createDiffieHellman(object? prime, object? primeEncoding, object? generator, object? generatorEncoding);

    /// <summary>
    /// Node.js signature: <c>crypto.createDiffieHellman(primeLength[, generator])</c>.
    /// </summary>
    [NodeModuleMember("createDiffieHellman")]
    object? createDiffieHellman(double primeLength);

    /// <summary>
    /// Node.js signature: <c>crypto.createDiffieHellman(primeLength[, generator])</c>.
    /// </summary>
    [NodeModuleMember("createDiffieHellman")]
    object? createDiffieHellman(double primeLength, object? generator);

    /// <summary>
    /// Node.js signature: <c>crypto.createDiffieHellmanGroup(name)</c>.
    /// </summary>
    [NodeModuleMember("createDiffieHellmanGroup")]
    object? createDiffieHellmanGroup(string name);

    /// <summary>
    /// Node.js signature: <c>crypto.createECDH(curveName)</c>.
    /// </summary>
    [NodeModuleMember("createECDH")]
    object? createECDH(string curveName);

    /// <summary>
    /// Node.js signature: <c>crypto.createHash(algorithm[, options])</c>.
    /// </summary>
    [NodeModuleMember("createHash")]
    object? createHash(string algorithm);

    /// <summary>
    /// Node.js signature: <c>crypto.createHash(algorithm[, options])</c>.
    /// </summary>
    [NodeModuleMember("createHash")]
    object? createHash(string algorithm, object? options);

    /// <summary>
    /// Node.js signature: <c>crypto.createHmac(algorithm, key[, options])</c>.
    /// </summary>
    [NodeModuleMember("createHmac")]
    object? createHmac(string algorithm, object? key);

    /// <summary>
    /// Node.js signature: <c>crypto.createHmac(algorithm, key[, options])</c>.
    /// </summary>
    [NodeModuleMember("createHmac")]
    object? createHmac(string algorithm, object? key, object? options);

    /// <summary>
    /// Node.js signature: <c>crypto.createPrivateKey(key)</c>.
    /// </summary>
    [NodeModuleMember("createPrivateKey")]
    object? createPrivateKey(object? key);

    /// <summary>
    /// Node.js signature: <c>crypto.createPublicKey(key)</c>.
    /// </summary>
    [NodeModuleMember("createPublicKey")]
    object? createPublicKey(object? key);

    /// <summary>
    /// Node.js signature: <c>crypto.createSecretKey(key[, encoding])</c>.
    /// </summary>
    [NodeModuleMember("createSecretKey")]
    object? createSecretKey(object? key);

    /// <summary>
    /// Node.js signature: <c>crypto.createSecretKey(key[, encoding])</c>.
    /// </summary>
    [NodeModuleMember("createSecretKey")]
    object? createSecretKey(object? key, object? encoding);

    /// <summary>
    /// Node.js signature: <c>crypto.createSign(algorithm[, options])</c>.
    /// </summary>
    [NodeModuleMember("createSign")]
    object? createSign(string algorithm);

    /// <summary>
    /// Node.js signature: <c>crypto.createSign(algorithm[, options])</c>.
    /// </summary>
    [NodeModuleMember("createSign")]
    object? createSign(string algorithm, object? options);

    /// <summary>
    /// Node.js signature: <c>crypto.createVerify(algorithm[, options])</c>.
    /// </summary>
    [NodeModuleMember("createVerify")]
    object? createVerify(string algorithm);

    /// <summary>
    /// Node.js signature: <c>crypto.createVerify(algorithm[, options])</c>.
    /// </summary>
    [NodeModuleMember("createVerify")]
    object? createVerify(string algorithm, object? options);

    /// <summary>
    /// Node.js signature: <c>crypto.generateKey(type, options, callback)</c>.
    /// </summary>
    [NodeModuleMember("generateKey")]
    void generateKey(string type, object? options, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>crypto.generateKeyPair(type, options, callback)</c>.
    /// </summary>
    [NodeModuleMember("generateKeyPair")]
    void generateKeyPair(string type, object? options, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>crypto.generateKeyPairSync(type, options)</c>.
    /// </summary>
    [NodeModuleMember("generateKeyPairSync")]
    object? generateKeyPairSync(string type, object? options);

    /// <summary>
    /// Node.js signature: <c>crypto.generateKeySync(type, options)</c>.
    /// </summary>
    [NodeModuleMember("generateKeySync")]
    object? generateKeySync(string type, object? options);

    /// <summary>
    /// Node.js signature: <c>crypto.generatePrime(size[, options], callback)</c>.
    /// </summary>
    [NodeModuleMember("generatePrime")]
    void generatePrime(double size, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>crypto.generatePrime(size[, options], callback)</c>.
    /// </summary>
    [NodeModuleMember("generatePrime")]
    void generatePrime(double size, object? options, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>crypto.generatePrimeSync(size[, options])</c>.
    /// </summary>
    [NodeModuleMember("generatePrimeSync")]
    object? generatePrimeSync(double size);

    /// <summary>
    /// Node.js signature: <c>crypto.generatePrimeSync(size[, options])</c>.
    /// </summary>
    [NodeModuleMember("generatePrimeSync")]
    object? generatePrimeSync(double size, object? options);

    /// <summary>
    /// Node.js signature: <c>crypto.getCipherInfo(nameOrNid[, options])</c>.
    /// </summary>
    [NodeModuleMember("getCipherInfo")]
    object? getCipherInfo(object? nameOrNid);

    /// <summary>
    /// Node.js signature: <c>crypto.getCipherInfo(nameOrNid[, options])</c>.
    /// </summary>
    [NodeModuleMember("getCipherInfo")]
    object? getCipherInfo(object? nameOrNid, object? options);

    /// <summary>
    /// Node.js signature: <c>crypto.getCiphers()</c>.
    /// </summary>
    [NodeModuleMember("getCiphers")]
    global::JavaScriptRuntime.IJavaScriptArray getCiphers();

    /// <summary>
    /// Node.js signature: <c>crypto.getCurves()</c>.
    /// </summary>
    [NodeModuleMember("getCurves")]
    global::JavaScriptRuntime.IJavaScriptArray getCurves();

    /// <summary>
    /// Node.js signature: <c>crypto.getDiffieHellman(groupName)</c>.
    /// </summary>
    [NodeModuleMember("getDiffieHellman")]
    object? getDiffieHellman(string groupName);

    /// <summary>
    /// Node.js signature: <c>crypto.getFips()</c>.
    /// </summary>
    [NodeModuleMember("getFips")]
    double getFips();

    /// <summary>
    /// Node.js signature: <c>crypto.getHashes()</c>.
    /// </summary>
    [NodeModuleMember("getHashes")]
    global::JavaScriptRuntime.IJavaScriptArray getHashes();

    /// <summary>
    /// Node.js signature: <c>crypto.getRandomValues(typedArray)</c>.
    /// </summary>
    [NodeModuleMember("getRandomValues")]
    object? getRandomValues(object? typedArray);

    /// <summary>
    /// Node.js signature: <c>crypto.hash(algorithm, data[, options])</c>.
    /// </summary>
    [NodeModuleMember("hash")]
    object? hash(object? algorithm, object? data);

    /// <summary>
    /// Node.js signature: <c>crypto.hash(algorithm, data[, options])</c>.
    /// </summary>
    [NodeModuleMember("hash")]
    object? hash(object? algorithm, object? data, object? options);

    /// <summary>
    /// Node.js signature: <c>crypto.hkdf(digest, ikm, salt, info, keylen, callback)</c>.
    /// </summary>
    [NodeModuleMember("hkdf")]
    void hkdf(string digest, object? ikm, object? salt, object? info, double keylen, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>crypto.hkdfSync(digest, ikm, salt, info, keylen)</c>.
    /// </summary>
    [NodeModuleMember("hkdfSync")]
    global::JavaScriptRuntime.ArrayBuffer hkdfSync(string digest, object? ikm, object? salt, object? info, double keylen);

    /// <summary>
    /// Node.js signature: <c>crypto.pbkdf2(password, salt, iterations, keylen, digest, callback)</c>.
    /// </summary>
    [NodeModuleMember("pbkdf2")]
    void pbkdf2(object? password, object? salt, double iterations, double keylen, string digest, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>crypto.pbkdf2Sync(password, salt, iterations, keylen, digest)</c>.
    /// </summary>
    [NodeModuleMember("pbkdf2Sync")]
    global::JavaScriptRuntime.Node.Buffer pbkdf2Sync(object? password, object? salt, double iterations, double keylen, string digest);

    /// <summary>
    /// Node.js signature: <c>crypto.privateDecrypt(privateKey, buffer)</c>.
    /// </summary>
    [NodeModuleMember("privateDecrypt")]
    global::JavaScriptRuntime.Node.Buffer privateDecrypt(object? privateKey, object? buffer);

    /// <summary>
    /// Node.js signature: <c>crypto.privateEncrypt(privateKey, buffer)</c>.
    /// </summary>
    [NodeModuleMember("privateEncrypt")]
    global::JavaScriptRuntime.Node.Buffer privateEncrypt(object? privateKey, object? buffer);

    /// <summary>
    /// Node.js signature: <c>crypto.publicDecrypt(key, buffer)</c>.
    /// </summary>
    [NodeModuleMember("publicDecrypt")]
    global::JavaScriptRuntime.Node.Buffer publicDecrypt(object? key, object? buffer);

    /// <summary>
    /// Node.js signature: <c>crypto.publicEncrypt(key, buffer)</c>.
    /// </summary>
    [NodeModuleMember("publicEncrypt")]
    global::JavaScriptRuntime.Node.Buffer publicEncrypt(object? key, object? buffer);

    /// <summary>
    /// Node.js signature: <c>crypto.randomFill(buffer[, offset][, size], callback)</c>.
    /// </summary>
    [NodeModuleMember("randomFill")]
    void randomFill(object? buffer, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>crypto.randomFill(buffer[, offset][, size], callback)</c>.
    /// </summary>
    [NodeModuleMember("randomFill")]
    void randomFill(object? buffer, object? size, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>crypto.randomFill(buffer[, offset][, size], callback)</c>.
    /// </summary>
    [NodeModuleMember("randomFill")]
    void randomFill(object? buffer, object? offset, object? size, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>crypto.randomFillSync(buffer[, offset][, size])</c>.
    /// </summary>
    [NodeModuleMember("randomFillSync")]
    object? randomFillSync(object? buffer);

    /// <summary>
    /// Node.js signature: <c>crypto.randomFillSync(buffer[, offset][, size])</c>.
    /// </summary>
    [NodeModuleMember("randomFillSync")]
    object? randomFillSync(object? buffer, object? size);

    /// <summary>
    /// Node.js signature: <c>crypto.randomFillSync(buffer[, offset][, size])</c>.
    /// </summary>
    [NodeModuleMember("randomFillSync")]
    object? randomFillSync(object? buffer, object? offset, object? size);

    /// <summary>
    /// Node.js signature: <c>crypto.randomUUID([options])</c>.
    /// </summary>
    [NodeModuleMember("randomUUID")]
    string randomUUID();

    /// <summary>
    /// Node.js signature: <c>crypto.randomUUID([options])</c>.
    /// </summary>
    [NodeModuleMember("randomUUID")]
    string randomUUID(object? options);

    /// <summary>
    /// Node.js signature: <c>crypto.randomUUIDv7([options])</c>.
    /// </summary>
    [NodeModuleMember("randomUUIDv7")]
    string randomUUIDv7();

    /// <summary>
    /// Node.js signature: <c>crypto.randomUUIDv7([options])</c>.
    /// </summary>
    [NodeModuleMember("randomUUIDv7")]
    string randomUUIDv7(object? options);

    /// <summary>
    /// Node.js signature: <c>crypto.scrypt(password, salt, keylen[, options], callback)</c>.
    /// </summary>
    [NodeModuleMember("scrypt")]
    void scrypt(object? password, object? salt, double keylen, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>crypto.scrypt(password, salt, keylen[, options], callback)</c>.
    /// </summary>
    [NodeModuleMember("scrypt")]
    void scrypt(object? password, object? salt, double keylen, object? options, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>crypto.scryptSync(password, salt, keylen[, options])</c>.
    /// </summary>
    [NodeModuleMember("scryptSync")]
    global::JavaScriptRuntime.Node.Buffer scryptSync(object? password, object? salt, double keylen);

    /// <summary>
    /// Node.js signature: <c>crypto.scryptSync(password, salt, keylen[, options])</c>.
    /// </summary>
    [NodeModuleMember("scryptSync")]
    global::JavaScriptRuntime.Node.Buffer scryptSync(object? password, object? salt, double keylen, object? options);

    /// <summary>
    /// Node.js signature: <c>crypto.secureHeapUsed()</c>.
    /// </summary>
    [NodeModuleMember("secureHeapUsed")]
    object? secureHeapUsed();

    /// <summary>
    /// Node.js signature: <c>crypto.setEngine(engine[, flags])</c>.
    /// </summary>
    [NodeModuleMember("setEngine")]
    void setEngine(string engine);

    /// <summary>
    /// Node.js signature: <c>crypto.setEngine(engine[, flags])</c>.
    /// </summary>
    [NodeModuleMember("setEngine")]
    void setEngine(string engine, object? flags);

    /// <summary>
    /// Node.js signature: <c>crypto.setFips(bool)</c>.
    /// </summary>
    [NodeModuleMember("setFips")]
    void setFips(bool @bool);

    /// <summary>
    /// Node.js signature: <c>crypto.timingSafeEqual(a, b)</c>.
    /// </summary>
    [NodeModuleMember("timingSafeEqual")]
    bool timingSafeEqual(object? a, object? b);

    /// <summary>
    /// Node.js signature: <c>crypto.decapsulate(key, ciphertext[, callback])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/crypto.html#cryptodecapsulatekey-ciphertext-callback</c>.</remarks>
    [NodeModuleMember("decapsulate")]
    global::JavaScriptRuntime.Node.Buffer decapsulate(object? key, object? ciphertext);

    /// <summary>
    /// Node.js signature: <c>crypto.decapsulate(key, ciphertext[, callback])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/crypto.html#cryptodecapsulatekey-ciphertext-callback</c>.</remarks>
    [NodeModuleMember("decapsulate")]
    void decapsulate(object? key, object? ciphertext, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>crypto.diffieHellman(options[, callback])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/crypto.html#cryptodiffiehellmanoptions-callback</c>.</remarks>
    [NodeModuleMember("diffieHellman")]
    global::JavaScriptRuntime.Node.Buffer diffieHellman(object? options);

    /// <summary>
    /// Node.js signature: <c>crypto.diffieHellman(options[, callback])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/crypto.html#cryptodiffiehellmanoptions-callback</c>.</remarks>
    [NodeModuleMember("diffieHellman")]
    void diffieHellman(object? options, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>crypto.encapsulate(key[, callback])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/crypto.html#cryptoencapsulatekey-callback</c>.</remarks>
    [NodeModuleMember("encapsulate")]
    object? encapsulate(object? key);

    /// <summary>
    /// Node.js signature: <c>crypto.encapsulate(key[, callback])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/crypto.html#cryptoencapsulatekey-callback</c>.</remarks>
    [NodeModuleMember("encapsulate")]
    void encapsulate(object? key, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>crypto.randomBytes(size[, callback])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/crypto.html#cryptorandombytessize-callback</c>.</remarks>
    [NodeModuleMember("randomBytes")]
    global::JavaScriptRuntime.Node.Buffer randomBytes(double size);

    /// <summary>
    /// Node.js signature: <c>crypto.randomBytes(size[, callback])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/crypto.html#cryptorandombytessize-callback</c>.</remarks>
    [NodeModuleMember("randomBytes")]
    void randomBytes(double size, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>crypto.randomInt([min, ]max[, callback])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/crypto.html#cryptorandomintmin-max-callback</c>.</remarks>
    [NodeModuleMember("randomInt")]
    double randomInt(double max);

    /// <summary>
    /// Node.js signature: <c>crypto.randomInt([min, ]max[, callback])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/crypto.html#cryptorandomintmin-max-callback</c>.</remarks>
    [NodeModuleMember("randomInt")]
    void randomInt(double max, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>crypto.randomInt([min, ]max[, callback])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/crypto.html#cryptorandomintmin-max-callback</c>.</remarks>
    [NodeModuleMember("randomInt")]
    double randomInt(double min, double max);

    /// <summary>
    /// Node.js signature: <c>crypto.randomInt([min, ]max[, callback])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/crypto.html#cryptorandomintmin-max-callback</c>.</remarks>
    [NodeModuleMember("randomInt")]
    void randomInt(double min, double max, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>crypto.sign(algorithm, data, key[, callback])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/crypto.html#cryptosignalgorithm-data-key-callback</c>.</remarks>
    [NodeModuleMember("sign")]
    global::JavaScriptRuntime.Node.Buffer sign(object? algorithm, object? data, object? key);

    /// <summary>
    /// Node.js signature: <c>crypto.sign(algorithm, data, key[, callback])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/crypto.html#cryptosignalgorithm-data-key-callback</c>.</remarks>
    [NodeModuleMember("sign")]
    void sign(object? algorithm, object? data, object? key, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>crypto.verify(algorithm, data, key, signature[, callback])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/crypto.html#cryptoverifyalgorithm-data-key-signature-callback</c>.</remarks>
    [NodeModuleMember("verify")]
    bool verify(object? algorithm, object? data, object? key, object? signature);

    /// <summary>
    /// Node.js signature: <c>crypto.verify(algorithm, data, key, signature[, callback])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/crypto.html#cryptoverifyalgorithm-data-key-signature-callback</c>.</remarks>
    [NodeModuleMember("verify")]
    void verify(object? algorithm, object? data, object? key, object? signature, global::System.Delegate callback);

}
