// <auto-generated />
// Generated from the official Node.js 24.18.1 diagnostics_channel API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/diagnostics_channel.json
// SHA-256: 79bdb924bb2ba3278fe5d3b6b5729ab7bcb1839b8d39b1afb3a1210e6f6638df

#nullable enable

namespace Jroc.Runtime.Node.Contracts;

/// <summary>
/// Defines the public top-level <c>node:diagnostics_channel</c> module contract from Node.js 24.18.1.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCode("generateNodeModuleInterface.js", "sha256:de7d46c347d581581a76dc391aa1fcd75d184d772e05ee622c88f4c5b6aa96ad")]
[NodeModuleInterface("diagnostics_channel")]
public interface IDiagnosticsChannelModule
{
    /// <summary>
    /// Gets the exported <c>diagnostics_channel.Channel</c> member.
    /// </summary>
    /// <remarks>Source: <c>https://github.com/nodejs/node/blob/v24.18.1/lib/diagnostics_channel.js#L421-L428</c>.</remarks>
    [NodeModuleMember("Channel")]
    object? Channel { get; }

    // node:diagnostics_channel methods
    /// <summary>
    /// Node.js signature: <c>diagnostics_channel.hasSubscribers(name)</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/diagnostics_channel.html#diagnostics_channelhassubscribersname</c>.</remarks>
    [NodeModuleMember("hasSubscribers")]
    bool hasSubscribers(object? name);

    /// <summary>
    /// Node.js signature: <c>diagnostics_channel.channel(name)</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/diagnostics_channel.html#diagnostics_channelchannelname</c>.</remarks>
    [NodeModuleMember("channel")]
    object? channel(object? name);

    /// <summary>
    /// Node.js signature: <c>diagnostics_channel.subscribe(name, onMessage)</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/diagnostics_channel.html#diagnostics_channelsubscribename-onmessage</c>.</remarks>
    [NodeModuleMember("subscribe")]
    void subscribe(object? name, global::System.Delegate onMessage);

    /// <summary>
    /// Node.js signature: <c>diagnostics_channel.unsubscribe(name, onMessage)</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/diagnostics_channel.html#diagnostics_channelunsubscribename-onmessage</c>.</remarks>
    [NodeModuleMember("unsubscribe")]
    bool unsubscribe(object? name, global::System.Delegate onMessage);

    /// <summary>
    /// Node.js signature: <c>diagnostics_channel.tracingChannel(nameOrChannels)</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/diagnostics_channel.html#diagnostics_channeltracingchannelnameorchannels</c>.</remarks>
    [NodeModuleMember("tracingChannel")]
    object? tracingChannel(object? nameOrChannels);

}
