// <auto-generated />
// Generated from the official Node.js 24.18.1 fs API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/fs.json
// SHA-256: 3145e3751afc28b868f9b481788a081fd87adf3215aa638f850fcb52d636ab6b

#nullable enable

namespace Jroc.Runtime.Node.Contracts;

/// <summary>
/// Defines the public top-level <c>node:fs</c> module contract from Node.js 24.18.1.
/// </summary>
/// <remarks>
/// Nested option, result, and handle contracts intentionally remain dynamic in this proof of concept.
/// They will be strongly typed by the work tracked in GitHub issue #1660.
/// </remarks>
[global::System.CodeDom.Compiler.GeneratedCode("generateNodeModuleInterface.js", "sha256:14b2e890000ffcd350022937df7c4cd9fcd9e51a73066e39d8c3fd75e9ca9283")]
[NodeModuleInterface("fs")]
public interface IFsModule
{
    /// <summary>
    /// Gets the file system constants object.
    /// </summary>
    [NodeModuleMember("constants")]
    object? constants { get; }

    /// <summary>
    /// Gets the promise-based file system API.
    /// </summary>
    [NodeModuleMember("promises")]
    object? promises { get; }

    /// <summary>
    /// Gets the deprecated <c>fs.F_OK</c> constant.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/fs.html#fsaccesspath-mode-callback</c>.</remarks>
    [global::System.Obsolete("Use fs.constants.F_OK instead.")]
    [NodeModuleMember("F_OK")]
    double F_OK { get; }

    /// <summary>
    /// Gets the deprecated <c>fs.R_OK</c> constant.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/fs.html#fsaccesspath-mode-callback</c>.</remarks>
    [global::System.Obsolete("Use fs.constants.R_OK instead.")]
    [NodeModuleMember("R_OK")]
    double R_OK { get; }

    /// <summary>
    /// Gets the deprecated <c>fs.W_OK</c> constant.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/fs.html#fsaccesspath-mode-callback</c>.</remarks>
    [global::System.Obsolete("Use fs.constants.W_OK instead.")]
    [NodeModuleMember("W_OK")]
    double W_OK { get; }

    /// <summary>
    /// Gets the deprecated <c>fs.X_OK</c> constant.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/fs.html#fsaccesspath-mode-callback</c>.</remarks>
    [global::System.Obsolete("Use fs.constants.X_OK instead.")]
    [NodeModuleMember("X_OK")]
    double X_OK { get; }

    // Callback API
    /// <summary>
    /// Node.js signature: <c>fs.access(path[, mode], callback)</c>.
    /// </summary>
    [NodeModuleMember("access")]
    void access(object? path, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.access(path[, mode], callback)</c>.
    /// </summary>
    [NodeModuleMember("access")]
    void access(object? path, object? mode, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.appendFile(path, data[, options], callback)</c>.
    /// </summary>
    [NodeModuleMember("appendFile")]
    void appendFile(object? path, object? data, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.appendFile(path, data[, options], callback)</c>.
    /// </summary>
    [NodeModuleMember("appendFile")]
    void appendFile(object? path, object? data, object? options, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.chmod(path, mode, callback)</c>.
    /// </summary>
    [NodeModuleMember("chmod")]
    void chmod(object? path, object? mode, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.chown(path, uid, gid, callback)</c>.
    /// </summary>
    [NodeModuleMember("chown")]
    void chown(object? path, double uid, double gid, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.close(fd[, callback])</c>.
    /// </summary>
    [NodeModuleMember("close")]
    void close(double fd);

    /// <summary>
    /// Node.js signature: <c>fs.close(fd[, callback])</c>.
    /// </summary>
    [NodeModuleMember("close")]
    void close(double fd, object? callback);

    /// <summary>
    /// Node.js signature: <c>fs.copyFile(src, dest[, mode], callback)</c>.
    /// </summary>
    [NodeModuleMember("copyFile")]
    void copyFile(object? src, object? dest, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.copyFile(src, dest[, mode], callback)</c>.
    /// </summary>
    [NodeModuleMember("copyFile")]
    void copyFile(object? src, object? dest, object? mode, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.cp(src, dest[, options], callback)</c>.
    /// </summary>
    [NodeModuleMember("cp")]
    void cp(object? src, object? dest, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.cp(src, dest[, options], callback)</c>.
    /// </summary>
    [NodeModuleMember("cp")]
    void cp(object? src, object? dest, object? options, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.createReadStream(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("createReadStream")]
    object? createReadStream(object? path);

    /// <summary>
    /// Node.js signature: <c>fs.createReadStream(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("createReadStream")]
    object? createReadStream(object? path, object? options);

    /// <summary>
    /// Node.js signature: <c>fs.createWriteStream(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("createWriteStream")]
    object? createWriteStream(object? path);

    /// <summary>
    /// Node.js signature: <c>fs.createWriteStream(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("createWriteStream")]
    object? createWriteStream(object? path, object? options);

    /// <summary>
    /// Node.js signature: <c>fs.exists(path, callback)</c>.
    /// </summary>
    [global::System.Obsolete("Deprecated by Node.js since v1.0.0.")]
    [NodeModuleMember("exists")]
    void exists(object? path, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.fchmod(fd, mode, callback)</c>.
    /// </summary>
    [NodeModuleMember("fchmod")]
    void fchmod(double fd, object? mode, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.fchown(fd, uid, gid, callback)</c>.
    /// </summary>
    [NodeModuleMember("fchown")]
    void fchown(double fd, double uid, double gid, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.fdatasync(fd, callback)</c>.
    /// </summary>
    [NodeModuleMember("fdatasync")]
    void fdatasync(double fd, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.fstat(fd[, options], callback)</c>.
    /// </summary>
    [NodeModuleMember("fstat")]
    void fstat(double fd, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.fstat(fd[, options], callback)</c>.
    /// </summary>
    [NodeModuleMember("fstat")]
    void fstat(double fd, object? options, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.fsync(fd, callback)</c>.
    /// </summary>
    [NodeModuleMember("fsync")]
    void fsync(double fd, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.ftruncate(fd[, len], callback)</c>.
    /// </summary>
    [NodeModuleMember("ftruncate")]
    void ftruncate(double fd, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.ftruncate(fd[, len], callback)</c>.
    /// </summary>
    [NodeModuleMember("ftruncate")]
    void ftruncate(double fd, object? len, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.futimes(fd, atime, mtime, callback)</c>.
    /// </summary>
    [NodeModuleMember("futimes")]
    void futimes(double fd, object? atime, object? mtime, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.glob(pattern[, options], callback)</c>.
    /// </summary>
    [NodeModuleMember("glob")]
    void glob(object? pattern, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.glob(pattern[, options], callback)</c>.
    /// </summary>
    [NodeModuleMember("glob")]
    void glob(object? pattern, object? options, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.lchmod(path, mode, callback)</c>.
    /// </summary>
    [global::System.Obsolete("Deprecated by Node.js since v0.4.7.")]
    [NodeModuleMember("lchmod")]
    void lchmod(object? path, double mode, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.lchown(path, uid, gid, callback)</c>.
    /// </summary>
    [NodeModuleMember("lchown")]
    void lchown(object? path, double uid, double gid, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.lutimes(path, atime, mtime, callback)</c>.
    /// </summary>
    [NodeModuleMember("lutimes")]
    void lutimes(object? path, object? atime, object? mtime, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.link(existingPath, newPath, callback)</c>.
    /// </summary>
    [NodeModuleMember("link")]
    void link(object? existingPath, object? newPath, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.lstat(path[, options], callback)</c>.
    /// </summary>
    [NodeModuleMember("lstat")]
    void lstat(object? path, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.lstat(path[, options], callback)</c>.
    /// </summary>
    [NodeModuleMember("lstat")]
    void lstat(object? path, object? options, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.mkdir(path[, options], callback)</c>.
    /// </summary>
    [NodeModuleMember("mkdir")]
    void mkdir(object? path, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.mkdir(path[, options], callback)</c>.
    /// </summary>
    [NodeModuleMember("mkdir")]
    void mkdir(object? path, object? options, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.mkdtemp(prefix[, options], callback)</c>.
    /// </summary>
    [NodeModuleMember("mkdtemp")]
    void mkdtemp(object? prefix, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.mkdtemp(prefix[, options], callback)</c>.
    /// </summary>
    [NodeModuleMember("mkdtemp")]
    void mkdtemp(object? prefix, object? options, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.open(path[, flags[, mode]], callback)</c>.
    /// </summary>
    [NodeModuleMember("open")]
    void open(object? path, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.open(path[, flags[, mode]], callback)</c>.
    /// </summary>
    [NodeModuleMember("open")]
    void open(object? path, object? flags, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.open(path[, flags[, mode]], callback)</c>.
    /// </summary>
    [NodeModuleMember("open")]
    void open(object? path, object? flags, object? mode, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.openAsBlob(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("openAsBlob")]
    global::JavaScriptRuntime.IJavaScriptPromise openAsBlob(object? path);

    /// <summary>
    /// Node.js signature: <c>fs.openAsBlob(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("openAsBlob")]
    global::JavaScriptRuntime.IJavaScriptPromise openAsBlob(object? path, object? options);

    /// <summary>
    /// Node.js signature: <c>fs.opendir(path[, options], callback)</c>.
    /// </summary>
    [NodeModuleMember("opendir")]
    void opendir(object? path, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.opendir(path[, options], callback)</c>.
    /// </summary>
    [NodeModuleMember("opendir")]
    void opendir(object? path, object? options, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.read(fd, buffer, offset, length, position, callback)</c>.
    /// </summary>
    [NodeModuleMember("read")]
    void read(double fd, object? buffer, double offset, double length, object? position, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.read(fd[, options], callback)</c>.
    /// </summary>
    [NodeModuleMember("read")]
    void read(double fd, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.read(fd[, options], callback)</c>.
    /// </summary>
    [NodeModuleMember("read")]
    void read(double fd, object? options, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.read(fd, buffer[, options], callback)</c>.
    /// </summary>
    [NodeModuleMember("read")]
    void read(double fd, object? buffer, object? options, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.readdir(path[, options], callback)</c>.
    /// </summary>
    [NodeModuleMember("readdir")]
    void readdir(object? path, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.readdir(path[, options], callback)</c>.
    /// </summary>
    [NodeModuleMember("readdir")]
    void readdir(object? path, object? options, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.readFile(path[, options], callback)</c>.
    /// </summary>
    [NodeModuleMember("readFile")]
    void readFile(object? path, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.readFile(path[, options], callback)</c>.
    /// </summary>
    [NodeModuleMember("readFile")]
    void readFile(object? path, object? options, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.readlink(path[, options], callback)</c>.
    /// </summary>
    [NodeModuleMember("readlink")]
    void readlink(object? path, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.readlink(path[, options], callback)</c>.
    /// </summary>
    [NodeModuleMember("readlink")]
    void readlink(object? path, object? options, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.readv(fd, buffers[, position], callback)</c>.
    /// </summary>
    [NodeModuleMember("readv")]
    void readv(double fd, global::JavaScriptRuntime.IJavaScriptArray buffers, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.readv(fd, buffers[, position], callback)</c>.
    /// </summary>
    [NodeModuleMember("readv")]
    void readv(double fd, global::JavaScriptRuntime.IJavaScriptArray buffers, object? position, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.realpath(path[, options], callback)</c>.
    /// </summary>
    [NodeModuleMember("realpath")]
    void realpath(object? path, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.realpath(path[, options], callback)</c>.
    /// </summary>
    [NodeModuleMember("realpath")]
    void realpath(object? path, object? options, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.realpath.native(path[, options], callback)</c>.
    /// </summary>
    [NodeModuleMember("realpath.native")]
    void realpathNative(object? path, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.realpath.native(path[, options], callback)</c>.
    /// </summary>
    [NodeModuleMember("realpath.native")]
    void realpathNative(object? path, object? options, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.rename(oldPath, newPath, callback)</c>.
    /// </summary>
    [NodeModuleMember("rename")]
    void rename(object? oldPath, object? newPath, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.rmdir(path[, options], callback)</c>.
    /// </summary>
    [NodeModuleMember("rmdir")]
    void rmdir(object? path, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.rmdir(path[, options], callback)</c>.
    /// </summary>
    [NodeModuleMember("rmdir")]
    void rmdir(object? path, object? options, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.rm(path[, options], callback)</c>.
    /// </summary>
    [NodeModuleMember("rm")]
    void rm(object? path, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.rm(path[, options], callback)</c>.
    /// </summary>
    [NodeModuleMember("rm")]
    void rm(object? path, object? options, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.stat(path[, options], callback)</c>.
    /// </summary>
    [NodeModuleMember("stat")]
    void stat(object? path, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.stat(path[, options], callback)</c>.
    /// </summary>
    [NodeModuleMember("stat")]
    void stat(object? path, object? options, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.statfs(path[, options], callback)</c>.
    /// </summary>
    [NodeModuleMember("statfs")]
    void statfs(object? path, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.statfs(path[, options], callback)</c>.
    /// </summary>
    [NodeModuleMember("statfs")]
    void statfs(object? path, object? options, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.symlink(target, path[, type], callback)</c>.
    /// </summary>
    [NodeModuleMember("symlink")]
    void symlink(object? target, object? path, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.symlink(target, path[, type], callback)</c>.
    /// </summary>
    [NodeModuleMember("symlink")]
    void symlink(object? target, object? path, object? type, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.truncate(path[, len], callback)</c>.
    /// </summary>
    [NodeModuleMember("truncate")]
    void truncate(object? path, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.truncate(path[, len], callback)</c>.
    /// </summary>
    [NodeModuleMember("truncate")]
    void truncate(object? path, object? len, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.unlink(path, callback)</c>.
    /// </summary>
    [NodeModuleMember("unlink")]
    void unlink(object? path, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.unwatchFile(filename[, listener])</c>.
    /// </summary>
    [NodeModuleMember("unwatchFile")]
    void unwatchFile(object? filename);

    /// <summary>
    /// Node.js signature: <c>fs.unwatchFile(filename[, listener])</c>.
    /// </summary>
    [NodeModuleMember("unwatchFile")]
    void unwatchFile(object? filename, object? listener);

    /// <summary>
    /// Node.js signature: <c>fs.utimes(path, atime, mtime, callback)</c>.
    /// </summary>
    [NodeModuleMember("utimes")]
    void utimes(object? path, object? atime, object? mtime, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.watch(filename[, options][, listener])</c>.
    /// </summary>
    [NodeModuleMember("watch")]
    object? watch(object? filename);

    /// <summary>
    /// Node.js signature: <c>fs.watch(filename[, options][, listener])</c>.
    /// </summary>
    [NodeModuleMember("watch")]
    object? watch(object? filename, object? listener);

    /// <summary>
    /// Node.js signature: <c>fs.watch(filename[, options][, listener])</c>.
    /// </summary>
    [NodeModuleMember("watch")]
    object? watch(object? filename, object? options, object? listener);

    /// <summary>
    /// Node.js signature: <c>fs.watchFile(filename[, options], listener)</c>.
    /// </summary>
    [NodeModuleMember("watchFile")]
    object? watchFile(object? filename, global::System.Delegate listener);

    /// <summary>
    /// Node.js signature: <c>fs.watchFile(filename[, options], listener)</c>.
    /// </summary>
    [NodeModuleMember("watchFile")]
    object? watchFile(object? filename, object? options, global::System.Delegate listener);

    /// <summary>
    /// Node.js signature: <c>fs.write(fd, buffer, offset[, length[, position]], callback)</c>.
    /// </summary>
    [NodeModuleMember("write")]
    void write(double fd, object? buffer, double offset, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.write(fd, buffer, offset[, length[, position]], callback)</c>.
    /// </summary>
    [NodeModuleMember("write")]
    void write(double fd, object? buffer, double offset, object? length, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.write(fd, buffer, offset[, length[, position]], callback)</c>.
    /// </summary>
    [NodeModuleMember("write")]
    void write(double fd, object? buffer, double offset, object? length, object? position, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.write(fd, buffer[, options], callback)</c>.
    /// </summary>
    [NodeModuleMember("write")]
    void write(double fd, object? buffer, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.write(fd, buffer[, options], callback)</c>.
    /// </summary>
    [NodeModuleMember("write")]
    void write(double fd, object? buffer, object? options, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.write(fd, string[, position[, encoding]], callback)</c>.
    /// </summary>
    [NodeModuleMember("write")]
    void write(double fd, string @string, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.write(fd, string[, position[, encoding]], callback)</c>.
    /// </summary>
    [NodeModuleMember("write")]
    void write(double fd, string @string, object? position, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.write(fd, string[, position[, encoding]], callback)</c>.
    /// </summary>
    [NodeModuleMember("write")]
    void write(double fd, string @string, object? position, object? encoding, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.writeFile(file, data[, options], callback)</c>.
    /// </summary>
    [NodeModuleMember("writeFile")]
    void writeFile(object? file, object? data, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.writeFile(file, data[, options], callback)</c>.
    /// </summary>
    [NodeModuleMember("writeFile")]
    void writeFile(object? file, object? data, object? options, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.writev(fd, buffers[, position], callback)</c>.
    /// </summary>
    [NodeModuleMember("writev")]
    void writev(double fd, global::JavaScriptRuntime.IJavaScriptArray buffers, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>fs.writev(fd, buffers[, position], callback)</c>.
    /// </summary>
    [NodeModuleMember("writev")]
    void writev(double fd, global::JavaScriptRuntime.IJavaScriptArray buffers, object? position, global::System.Delegate callback);

    // Synchronous API
    /// <summary>
    /// Node.js signature: <c>fs.accessSync(path[, mode])</c>.
    /// </summary>
    [NodeModuleMember("accessSync")]
    void accessSync(object? path);

    /// <summary>
    /// Node.js signature: <c>fs.accessSync(path[, mode])</c>.
    /// </summary>
    [NodeModuleMember("accessSync")]
    void accessSync(object? path, object? mode);

    /// <summary>
    /// Node.js signature: <c>fs.appendFileSync(path, data[, options])</c>.
    /// </summary>
    [NodeModuleMember("appendFileSync")]
    void appendFileSync(object? path, object? data);

    /// <summary>
    /// Node.js signature: <c>fs.appendFileSync(path, data[, options])</c>.
    /// </summary>
    [NodeModuleMember("appendFileSync")]
    void appendFileSync(object? path, object? data, object? options);

    /// <summary>
    /// Node.js signature: <c>fs.chmodSync(path, mode)</c>.
    /// </summary>
    [NodeModuleMember("chmodSync")]
    void chmodSync(object? path, object? mode);

    /// <summary>
    /// Node.js signature: <c>fs.chownSync(path, uid, gid)</c>.
    /// </summary>
    [NodeModuleMember("chownSync")]
    void chownSync(object? path, double uid, double gid);

    /// <summary>
    /// Node.js signature: <c>fs.closeSync(fd)</c>.
    /// </summary>
    [NodeModuleMember("closeSync")]
    void closeSync(double fd);

    /// <summary>
    /// Node.js signature: <c>fs.copyFileSync(src, dest[, mode])</c>.
    /// </summary>
    [NodeModuleMember("copyFileSync")]
    void copyFileSync(object? src, object? dest);

    /// <summary>
    /// Node.js signature: <c>fs.copyFileSync(src, dest[, mode])</c>.
    /// </summary>
    [NodeModuleMember("copyFileSync")]
    void copyFileSync(object? src, object? dest, object? mode);

    /// <summary>
    /// Node.js signature: <c>fs.cpSync(src, dest[, options])</c>.
    /// </summary>
    [NodeModuleMember("cpSync")]
    void cpSync(object? src, object? dest);

    /// <summary>
    /// Node.js signature: <c>fs.cpSync(src, dest[, options])</c>.
    /// </summary>
    [NodeModuleMember("cpSync")]
    void cpSync(object? src, object? dest, object? options);

    /// <summary>
    /// Node.js signature: <c>fs.existsSync(path)</c>.
    /// </summary>
    [NodeModuleMember("existsSync")]
    bool existsSync(object? path);

    /// <summary>
    /// Node.js signature: <c>fs.fchmodSync(fd, mode)</c>.
    /// </summary>
    [NodeModuleMember("fchmodSync")]
    void fchmodSync(double fd, object? mode);

    /// <summary>
    /// Node.js signature: <c>fs.fchownSync(fd, uid, gid)</c>.
    /// </summary>
    [NodeModuleMember("fchownSync")]
    void fchownSync(double fd, double uid, double gid);

    /// <summary>
    /// Node.js signature: <c>fs.fdatasyncSync(fd)</c>.
    /// </summary>
    [NodeModuleMember("fdatasyncSync")]
    void fdatasyncSync(double fd);

    /// <summary>
    /// Node.js signature: <c>fs.fstatSync(fd[, options])</c>.
    /// </summary>
    [NodeModuleMember("fstatSync")]
    object? fstatSync(double fd);

    /// <summary>
    /// Node.js signature: <c>fs.fstatSync(fd[, options])</c>.
    /// </summary>
    [NodeModuleMember("fstatSync")]
    object? fstatSync(double fd, object? options);

    /// <summary>
    /// Node.js signature: <c>fs.fsyncSync(fd)</c>.
    /// </summary>
    [NodeModuleMember("fsyncSync")]
    void fsyncSync(double fd);

    /// <summary>
    /// Node.js signature: <c>fs.ftruncateSync(fd[, len])</c>.
    /// </summary>
    [NodeModuleMember("ftruncateSync")]
    void ftruncateSync(double fd);

    /// <summary>
    /// Node.js signature: <c>fs.ftruncateSync(fd[, len])</c>.
    /// </summary>
    [NodeModuleMember("ftruncateSync")]
    void ftruncateSync(double fd, object? len);

    /// <summary>
    /// Node.js signature: <c>fs.futimesSync(fd, atime, mtime)</c>.
    /// </summary>
    [NodeModuleMember("futimesSync")]
    void futimesSync(double fd, object? atime, object? mtime);

    /// <summary>
    /// Node.js signature: <c>fs.globSync(pattern[, options])</c>.
    /// </summary>
    [NodeModuleMember("globSync")]
    global::JavaScriptRuntime.IJavaScriptArray globSync(object? pattern);

    /// <summary>
    /// Node.js signature: <c>fs.globSync(pattern[, options])</c>.
    /// </summary>
    [NodeModuleMember("globSync")]
    global::JavaScriptRuntime.IJavaScriptArray globSync(object? pattern, object? options);

    /// <summary>
    /// Node.js signature: <c>fs.lchmodSync(path, mode)</c>.
    /// </summary>
    [global::System.Obsolete("Deprecated by Node.js since v0.4.7.")]
    [NodeModuleMember("lchmodSync")]
    void lchmodSync(object? path, double mode);

    /// <summary>
    /// Node.js signature: <c>fs.lchownSync(path, uid, gid)</c>.
    /// </summary>
    [NodeModuleMember("lchownSync")]
    void lchownSync(object? path, double uid, double gid);

    /// <summary>
    /// Node.js signature: <c>fs.lutimesSync(path, atime, mtime)</c>.
    /// </summary>
    [NodeModuleMember("lutimesSync")]
    void lutimesSync(object? path, object? atime, object? mtime);

    /// <summary>
    /// Node.js signature: <c>fs.linkSync(existingPath, newPath)</c>.
    /// </summary>
    [NodeModuleMember("linkSync")]
    void linkSync(object? existingPath, object? newPath);

    /// <summary>
    /// Node.js signature: <c>fs.lstatSync(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("lstatSync")]
    object? lstatSync(object? path);

    /// <summary>
    /// Node.js signature: <c>fs.lstatSync(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("lstatSync")]
    object? lstatSync(object? path, object? options);

    /// <summary>
    /// Node.js signature: <c>fs.mkdirSync(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("mkdirSync")]
    object? mkdirSync(object? path);

    /// <summary>
    /// Node.js signature: <c>fs.mkdirSync(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("mkdirSync")]
    object? mkdirSync(object? path, object? options);

    /// <summary>
    /// Node.js signature: <c>fs.mkdtempSync(prefix[, options])</c>.
    /// </summary>
    [NodeModuleMember("mkdtempSync")]
    string mkdtempSync(object? prefix);

    /// <summary>
    /// Node.js signature: <c>fs.mkdtempSync(prefix[, options])</c>.
    /// </summary>
    [NodeModuleMember("mkdtempSync")]
    string mkdtempSync(object? prefix, object? options);

    /// <summary>
    /// Node.js signature: <c>fs.mkdtempDisposableSync(prefix[, options])</c>.
    /// </summary>
    [NodeModuleMember("mkdtempDisposableSync")]
    object? mkdtempDisposableSync(object? prefix);

    /// <summary>
    /// Node.js signature: <c>fs.mkdtempDisposableSync(prefix[, options])</c>.
    /// </summary>
    [NodeModuleMember("mkdtempDisposableSync")]
    object? mkdtempDisposableSync(object? prefix, object? options);

    /// <summary>
    /// Node.js signature: <c>fs.opendirSync(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("opendirSync")]
    object? opendirSync(object? path);

    /// <summary>
    /// Node.js signature: <c>fs.opendirSync(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("opendirSync")]
    object? opendirSync(object? path, object? options);

    /// <summary>
    /// Node.js signature: <c>fs.openSync(path[, flags[, mode]])</c>.
    /// </summary>
    [NodeModuleMember("openSync")]
    double openSync(object? path);

    /// <summary>
    /// Node.js signature: <c>fs.openSync(path[, flags[, mode]])</c>.
    /// </summary>
    [NodeModuleMember("openSync")]
    double openSync(object? path, object? flags);

    /// <summary>
    /// Node.js signature: <c>fs.openSync(path[, flags[, mode]])</c>.
    /// </summary>
    [NodeModuleMember("openSync")]
    double openSync(object? path, object? flags, object? mode);

    /// <summary>
    /// Node.js signature: <c>fs.readdirSync(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("readdirSync")]
    global::JavaScriptRuntime.IJavaScriptArray readdirSync(object? path);

    /// <summary>
    /// Node.js signature: <c>fs.readdirSync(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("readdirSync")]
    global::JavaScriptRuntime.IJavaScriptArray readdirSync(object? path, object? options);

    /// <summary>
    /// Node.js signature: <c>fs.readFileSync(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("readFileSync")]
    object? readFileSync(object? path);

    /// <summary>
    /// Node.js signature: <c>fs.readFileSync(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("readFileSync")]
    object? readFileSync(object? path, object? options);

    /// <summary>
    /// Node.js signature: <c>fs.readlinkSync(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("readlinkSync")]
    object? readlinkSync(object? path);

    /// <summary>
    /// Node.js signature: <c>fs.readlinkSync(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("readlinkSync")]
    object? readlinkSync(object? path, object? options);

    /// <summary>
    /// Node.js signature: <c>fs.readSync(fd, buffer, offset, length[, position])</c>.
    /// </summary>
    [NodeModuleMember("readSync")]
    double readSync(double fd, object? buffer, double offset, double length);

    /// <summary>
    /// Node.js signature: <c>fs.readSync(fd, buffer, offset, length[, position])</c>.
    /// </summary>
    [NodeModuleMember("readSync")]
    double readSync(double fd, object? buffer, double offset, double length, object? position);

    /// <summary>
    /// Node.js signature: <c>fs.readSync(fd, buffer[, options])</c>.
    /// </summary>
    [NodeModuleMember("readSync")]
    double readSync(double fd, object? buffer);

    /// <summary>
    /// Node.js signature: <c>fs.readSync(fd, buffer[, options])</c>.
    /// </summary>
    [NodeModuleMember("readSync")]
    double readSync(double fd, object? buffer, object? options);

    /// <summary>
    /// Node.js signature: <c>fs.readvSync(fd, buffers[, position])</c>.
    /// </summary>
    [NodeModuleMember("readvSync")]
    double readvSync(double fd, global::JavaScriptRuntime.IJavaScriptArray buffers);

    /// <summary>
    /// Node.js signature: <c>fs.readvSync(fd, buffers[, position])</c>.
    /// </summary>
    [NodeModuleMember("readvSync")]
    double readvSync(double fd, global::JavaScriptRuntime.IJavaScriptArray buffers, object? position);

    /// <summary>
    /// Node.js signature: <c>fs.realpathSync(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("realpathSync")]
    object? realpathSync(object? path);

    /// <summary>
    /// Node.js signature: <c>fs.realpathSync(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("realpathSync")]
    object? realpathSync(object? path, object? options);

    /// <summary>
    /// Node.js signature: <c>fs.realpathSync.native(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("realpathSync.native")]
    object? realpathSyncNative(object? path);

    /// <summary>
    /// Node.js signature: <c>fs.realpathSync.native(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("realpathSync.native")]
    object? realpathSyncNative(object? path, object? options);

    /// <summary>
    /// Node.js signature: <c>fs.renameSync(oldPath, newPath)</c>.
    /// </summary>
    [NodeModuleMember("renameSync")]
    void renameSync(object? oldPath, object? newPath);

    /// <summary>
    /// Node.js signature: <c>fs.rmdirSync(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("rmdirSync")]
    void rmdirSync(object? path);

    /// <summary>
    /// Node.js signature: <c>fs.rmdirSync(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("rmdirSync")]
    void rmdirSync(object? path, object? options);

    /// <summary>
    /// Node.js signature: <c>fs.rmSync(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("rmSync")]
    void rmSync(object? path);

    /// <summary>
    /// Node.js signature: <c>fs.rmSync(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("rmSync")]
    void rmSync(object? path, object? options);

    /// <summary>
    /// Node.js signature: <c>fs.statSync(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("statSync")]
    object? statSync(object? path);

    /// <summary>
    /// Node.js signature: <c>fs.statSync(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("statSync")]
    object? statSync(object? path, object? options);

    /// <summary>
    /// Node.js signature: <c>fs.statfsSync(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("statfsSync")]
    object? statfsSync(object? path);

    /// <summary>
    /// Node.js signature: <c>fs.statfsSync(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("statfsSync")]
    object? statfsSync(object? path, object? options);

    /// <summary>
    /// Node.js signature: <c>fs.symlinkSync(target, path[, type])</c>.
    /// </summary>
    [NodeModuleMember("symlinkSync")]
    void symlinkSync(object? target, object? path);

    /// <summary>
    /// Node.js signature: <c>fs.symlinkSync(target, path[, type])</c>.
    /// </summary>
    [NodeModuleMember("symlinkSync")]
    void symlinkSync(object? target, object? path, object? type);

    /// <summary>
    /// Node.js signature: <c>fs.truncateSync(path[, len])</c>.
    /// </summary>
    [NodeModuleMember("truncateSync")]
    void truncateSync(object? path);

    /// <summary>
    /// Node.js signature: <c>fs.truncateSync(path[, len])</c>.
    /// </summary>
    [NodeModuleMember("truncateSync")]
    void truncateSync(object? path, object? len);

    /// <summary>
    /// Node.js signature: <c>fs.unlinkSync(path)</c>.
    /// </summary>
    [NodeModuleMember("unlinkSync")]
    void unlinkSync(object? path);

    /// <summary>
    /// Node.js signature: <c>fs.utimesSync(path, atime, mtime)</c>.
    /// </summary>
    [NodeModuleMember("utimesSync")]
    void utimesSync(object? path, object? atime, object? mtime);

    /// <summary>
    /// Node.js signature: <c>fs.writeFileSync(file, data[, options])</c>.
    /// </summary>
    [NodeModuleMember("writeFileSync")]
    void writeFileSync(object? file, object? data);

    /// <summary>
    /// Node.js signature: <c>fs.writeFileSync(file, data[, options])</c>.
    /// </summary>
    [NodeModuleMember("writeFileSync")]
    void writeFileSync(object? file, object? data, object? options);

    /// <summary>
    /// Node.js signature: <c>fs.writeSync(fd, buffer, offset[, length[, position]])</c>.
    /// </summary>
    [NodeModuleMember("writeSync")]
    double writeSync(double fd, object? buffer, double offset);

    /// <summary>
    /// Node.js signature: <c>fs.writeSync(fd, buffer, offset[, length[, position]])</c>.
    /// </summary>
    [NodeModuleMember("writeSync")]
    double writeSync(double fd, object? buffer, double offset, object? length);

    /// <summary>
    /// Node.js signature: <c>fs.writeSync(fd, buffer, offset[, length[, position]])</c>.
    /// </summary>
    [NodeModuleMember("writeSync")]
    double writeSync(double fd, object? buffer, double offset, object? length, object? position);

    /// <summary>
    /// Node.js signature: <c>fs.writeSync(fd, buffer[, options])</c>.
    /// </summary>
    [NodeModuleMember("writeSync")]
    double writeSync(double fd, object? buffer);

    /// <summary>
    /// Node.js signature: <c>fs.writeSync(fd, buffer[, options])</c>.
    /// </summary>
    [NodeModuleMember("writeSync")]
    double writeSync(double fd, object? buffer, object? options);

    /// <summary>
    /// Node.js signature: <c>fs.writeSync(fd, string[, position[, encoding]])</c>.
    /// </summary>
    [NodeModuleMember("writeSync")]
    double writeSync(double fd, string @string);

    /// <summary>
    /// Node.js signature: <c>fs.writeSync(fd, string[, position[, encoding]])</c>.
    /// </summary>
    [NodeModuleMember("writeSync")]
    double writeSync(double fd, string @string, object? position);

    /// <summary>
    /// Node.js signature: <c>fs.writeSync(fd, string[, position[, encoding]])</c>.
    /// </summary>
    [NodeModuleMember("writeSync")]
    double writeSync(double fd, string @string, object? position, object? encoding);

    /// <summary>
    /// Node.js signature: <c>fs.writevSync(fd, buffers[, position])</c>.
    /// </summary>
    [NodeModuleMember("writevSync")]
    double writevSync(double fd, global::JavaScriptRuntime.IJavaScriptArray buffers);

    /// <summary>
    /// Node.js signature: <c>fs.writevSync(fd, buffers[, position])</c>.
    /// </summary>
    [NodeModuleMember("writevSync")]
    double writevSync(double fd, global::JavaScriptRuntime.IJavaScriptArray buffers, object? position);

}
