// <auto-generated />
// Generated from the official Node.js 24.18.1 fs API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/fs.json
// SHA-256: 3145e3751afc28b868f9b481788a081fd87adf3215aa638f850fcb52d636ab6b

#nullable enable

namespace Jroc.Runtime.Node.Contracts;

/// <summary>
/// Defines the public top-level <c>node:fs/promises</c> module contract from Node.js 24.18.1.
/// </summary>
/// <remarks>
/// Nested option, result, and handle contracts intentionally remain dynamic in this proof of concept.
/// They will be strongly typed by the work tracked in GitHub issue #1660.
/// </remarks>
[global::System.CodeDom.Compiler.GeneratedCode("generateFsModuleInterface.js", "1.0.0")]
[NodeModuleInterface("fs/promises")]
public interface IFsPromisesModule
{
    /// <summary>
    /// Gets the file system constants object.
    /// </summary>
    [NodeModuleMember("constants")]
    object? constants { get; }

    // Promise API
    /// <summary>
    /// Node.js signature: <c>fsPromises.access(path[, mode])</c>.
    /// </summary>
    [NodeModuleMember("access")]
    global::JavaScriptRuntime.Promise access(object? path);

    /// <summary>
    /// Node.js signature: <c>fsPromises.access(path[, mode])</c>.
    /// </summary>
    [NodeModuleMember("access")]
    global::JavaScriptRuntime.Promise access(object? path, object? mode);

    /// <summary>
    /// Node.js signature: <c>fsPromises.appendFile(path, data[, options])</c>.
    /// </summary>
    [NodeModuleMember("appendFile")]
    global::JavaScriptRuntime.Promise appendFile(object? path, object? data);

    /// <summary>
    /// Node.js signature: <c>fsPromises.appendFile(path, data[, options])</c>.
    /// </summary>
    [NodeModuleMember("appendFile")]
    global::JavaScriptRuntime.Promise appendFile(object? path, object? data, object? options);

    /// <summary>
    /// Node.js signature: <c>fsPromises.chmod(path, mode)</c>.
    /// </summary>
    [NodeModuleMember("chmod")]
    global::JavaScriptRuntime.Promise chmod(object? path, object? mode);

    /// <summary>
    /// Node.js signature: <c>fsPromises.chown(path, uid, gid)</c>.
    /// </summary>
    [NodeModuleMember("chown")]
    global::JavaScriptRuntime.Promise chown(object? path, double uid, double gid);

    /// <summary>
    /// Node.js signature: <c>fsPromises.copyFile(src, dest[, mode])</c>.
    /// </summary>
    [NodeModuleMember("copyFile")]
    global::JavaScriptRuntime.Promise copyFile(object? src, object? dest);

    /// <summary>
    /// Node.js signature: <c>fsPromises.copyFile(src, dest[, mode])</c>.
    /// </summary>
    [NodeModuleMember("copyFile")]
    global::JavaScriptRuntime.Promise copyFile(object? src, object? dest, object? mode);

    /// <summary>
    /// Node.js signature: <c>fsPromises.cp(src, dest[, options])</c>.
    /// </summary>
    [NodeModuleMember("cp")]
    global::JavaScriptRuntime.Promise cp(object? src, object? dest);

    /// <summary>
    /// Node.js signature: <c>fsPromises.cp(src, dest[, options])</c>.
    /// </summary>
    [NodeModuleMember("cp")]
    global::JavaScriptRuntime.Promise cp(object? src, object? dest, object? options);

    /// <summary>
    /// Node.js signature: <c>fsPromises.glob(pattern[, options])</c>.
    /// </summary>
    [NodeModuleMember("glob")]
    global::JavaScriptRuntime.IJavaScriptAsyncIterator glob(object? pattern);

    /// <summary>
    /// Node.js signature: <c>fsPromises.glob(pattern[, options])</c>.
    /// </summary>
    [NodeModuleMember("glob")]
    global::JavaScriptRuntime.IJavaScriptAsyncIterator glob(object? pattern, object? options);

    /// <summary>
    /// Node.js signature: <c>fsPromises.lchmod(path, mode)</c>.
    /// </summary>
    [global::System.Obsolete("Deprecated by Node.js since v10.0.0.")]
    [NodeModuleMember("lchmod")]
    global::JavaScriptRuntime.Promise lchmod(object? path, double mode);

    /// <summary>
    /// Node.js signature: <c>fsPromises.lchown(path, uid, gid)</c>.
    /// </summary>
    [NodeModuleMember("lchown")]
    global::JavaScriptRuntime.Promise lchown(object? path, double uid, double gid);

    /// <summary>
    /// Node.js signature: <c>fsPromises.lutimes(path, atime, mtime)</c>.
    /// </summary>
    [NodeModuleMember("lutimes")]
    global::JavaScriptRuntime.Promise lutimes(object? path, object? atime, object? mtime);

    /// <summary>
    /// Node.js signature: <c>fsPromises.link(existingPath, newPath)</c>.
    /// </summary>
    [NodeModuleMember("link")]
    global::JavaScriptRuntime.Promise link(object? existingPath, object? newPath);

    /// <summary>
    /// Node.js signature: <c>fsPromises.lstat(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("lstat")]
    global::JavaScriptRuntime.Promise lstat(object? path);

    /// <summary>
    /// Node.js signature: <c>fsPromises.lstat(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("lstat")]
    global::JavaScriptRuntime.Promise lstat(object? path, object? options);

    /// <summary>
    /// Node.js signature: <c>fsPromises.mkdir(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("mkdir")]
    global::JavaScriptRuntime.Promise mkdir(object? path);

    /// <summary>
    /// Node.js signature: <c>fsPromises.mkdir(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("mkdir")]
    global::JavaScriptRuntime.Promise mkdir(object? path, object? options);

    /// <summary>
    /// Node.js signature: <c>fsPromises.mkdtemp(prefix[, options])</c>.
    /// </summary>
    [NodeModuleMember("mkdtemp")]
    global::JavaScriptRuntime.Promise mkdtemp(object? prefix);

    /// <summary>
    /// Node.js signature: <c>fsPromises.mkdtemp(prefix[, options])</c>.
    /// </summary>
    [NodeModuleMember("mkdtemp")]
    global::JavaScriptRuntime.Promise mkdtemp(object? prefix, object? options);

    /// <summary>
    /// Node.js signature: <c>fsPromises.mkdtempDisposable(prefix[, options])</c>.
    /// </summary>
    [NodeModuleMember("mkdtempDisposable")]
    global::JavaScriptRuntime.Promise mkdtempDisposable(object? prefix);

    /// <summary>
    /// Node.js signature: <c>fsPromises.mkdtempDisposable(prefix[, options])</c>.
    /// </summary>
    [NodeModuleMember("mkdtempDisposable")]
    global::JavaScriptRuntime.Promise mkdtempDisposable(object? prefix, object? options);

    /// <summary>
    /// Node.js signature: <c>fsPromises.open(path, flags[, mode])</c>.
    /// </summary>
    [NodeModuleMember("open")]
    global::JavaScriptRuntime.Promise open(object? path, object? flags);

    /// <summary>
    /// Node.js signature: <c>fsPromises.open(path, flags[, mode])</c>.
    /// </summary>
    [NodeModuleMember("open")]
    global::JavaScriptRuntime.Promise open(object? path, object? flags, object? mode);

    /// <summary>
    /// Node.js signature: <c>fsPromises.opendir(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("opendir")]
    global::JavaScriptRuntime.Promise opendir(object? path);

    /// <summary>
    /// Node.js signature: <c>fsPromises.opendir(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("opendir")]
    global::JavaScriptRuntime.Promise opendir(object? path, object? options);

    /// <summary>
    /// Node.js signature: <c>fsPromises.readdir(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("readdir")]
    global::JavaScriptRuntime.Promise readdir(object? path);

    /// <summary>
    /// Node.js signature: <c>fsPromises.readdir(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("readdir")]
    global::JavaScriptRuntime.Promise readdir(object? path, object? options);

    /// <summary>
    /// Node.js signature: <c>fsPromises.readFile(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("readFile")]
    global::JavaScriptRuntime.Promise readFile(object? path);

    /// <summary>
    /// Node.js signature: <c>fsPromises.readFile(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("readFile")]
    global::JavaScriptRuntime.Promise readFile(object? path, object? options);

    /// <summary>
    /// Node.js signature: <c>fsPromises.readlink(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("readlink")]
    global::JavaScriptRuntime.Promise readlink(object? path);

    /// <summary>
    /// Node.js signature: <c>fsPromises.readlink(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("readlink")]
    global::JavaScriptRuntime.Promise readlink(object? path, object? options);

    /// <summary>
    /// Node.js signature: <c>fsPromises.realpath(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("realpath")]
    global::JavaScriptRuntime.Promise realpath(object? path);

    /// <summary>
    /// Node.js signature: <c>fsPromises.realpath(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("realpath")]
    global::JavaScriptRuntime.Promise realpath(object? path, object? options);

    /// <summary>
    /// Node.js signature: <c>fsPromises.rename(oldPath, newPath)</c>.
    /// </summary>
    [NodeModuleMember("rename")]
    global::JavaScriptRuntime.Promise rename(object? oldPath, object? newPath);

    /// <summary>
    /// Node.js signature: <c>fsPromises.rmdir(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("rmdir")]
    global::JavaScriptRuntime.Promise rmdir(object? path);

    /// <summary>
    /// Node.js signature: <c>fsPromises.rmdir(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("rmdir")]
    global::JavaScriptRuntime.Promise rmdir(object? path, object? options);

    /// <summary>
    /// Node.js signature: <c>fsPromises.rm(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("rm")]
    global::JavaScriptRuntime.Promise rm(object? path);

    /// <summary>
    /// Node.js signature: <c>fsPromises.rm(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("rm")]
    global::JavaScriptRuntime.Promise rm(object? path, object? options);

    /// <summary>
    /// Node.js signature: <c>fsPromises.stat(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("stat")]
    global::JavaScriptRuntime.Promise stat(object? path);

    /// <summary>
    /// Node.js signature: <c>fsPromises.stat(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("stat")]
    global::JavaScriptRuntime.Promise stat(object? path, object? options);

    /// <summary>
    /// Node.js signature: <c>fsPromises.statfs(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("statfs")]
    global::JavaScriptRuntime.Promise statfs(object? path);

    /// <summary>
    /// Node.js signature: <c>fsPromises.statfs(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("statfs")]
    global::JavaScriptRuntime.Promise statfs(object? path, object? options);

    /// <summary>
    /// Node.js signature: <c>fsPromises.symlink(target, path[, type])</c>.
    /// </summary>
    [NodeModuleMember("symlink")]
    global::JavaScriptRuntime.Promise symlink(object? target, object? path);

    /// <summary>
    /// Node.js signature: <c>fsPromises.symlink(target, path[, type])</c>.
    /// </summary>
    [NodeModuleMember("symlink")]
    global::JavaScriptRuntime.Promise symlink(object? target, object? path, object? type);

    /// <summary>
    /// Node.js signature: <c>fsPromises.truncate(path[, len])</c>.
    /// </summary>
    [NodeModuleMember("truncate")]
    global::JavaScriptRuntime.Promise truncate(object? path);

    /// <summary>
    /// Node.js signature: <c>fsPromises.truncate(path[, len])</c>.
    /// </summary>
    [NodeModuleMember("truncate")]
    global::JavaScriptRuntime.Promise truncate(object? path, object? len);

    /// <summary>
    /// Node.js signature: <c>fsPromises.unlink(path)</c>.
    /// </summary>
    [NodeModuleMember("unlink")]
    global::JavaScriptRuntime.Promise unlink(object? path);

    /// <summary>
    /// Node.js signature: <c>fsPromises.utimes(path, atime, mtime)</c>.
    /// </summary>
    [NodeModuleMember("utimes")]
    global::JavaScriptRuntime.Promise utimes(object? path, object? atime, object? mtime);

    /// <summary>
    /// Node.js signature: <c>fsPromises.watch(filename[, options])</c>.
    /// </summary>
    [NodeModuleMember("watch")]
    global::JavaScriptRuntime.IJavaScriptAsyncIterator watch(object? filename);

    /// <summary>
    /// Node.js signature: <c>fsPromises.watch(filename[, options])</c>.
    /// </summary>
    [NodeModuleMember("watch")]
    global::JavaScriptRuntime.IJavaScriptAsyncIterator watch(object? filename, object? options);

    /// <summary>
    /// Node.js signature: <c>fsPromises.writeFile(file, data[, options])</c>.
    /// </summary>
    [NodeModuleMember("writeFile")]
    global::JavaScriptRuntime.Promise writeFile(object? file, object? data);

    /// <summary>
    /// Node.js signature: <c>fsPromises.writeFile(file, data[, options])</c>.
    /// </summary>
    [NodeModuleMember("writeFile")]
    global::JavaScriptRuntime.Promise writeFile(object? file, object? data, object? options);

}
