// <auto-generated />
// Generated from the official Node.js 24.18.1 fs API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/fs.json
// SHA-256: 3145e3751afc28b868f9b481788a081fd87adf3215aa638f850fcb52d636ab6b

#nullable enable

namespace Jroc.Runtime.Node.Contracts;

/// <summary>
/// Defines the public top-level <c>node:fs/promises</c> module contract from Node.js 24.18.1.
/// </summary>
/// <remarks>
/// Nested option, result, and handle contracts intentionally remain dynamic in this proof of concept.
/// They will be strongly typed by the work tracked in GitHub issue #1660.
/// </remarks>
[global::System.CodeDom.Compiler.GeneratedCode("generateNodeModuleInterface.js", "sha256:2ee91195254f30219699ff139d0ec64ba35ff4bb612ec3ef4e5eaf613990c638")]
[NodeModuleInterface("fs/promises")]
public interface IFsPromisesModule
{
    /// <summary>
    /// Gets the file system constants object.
    /// </summary>
    [NodeModuleMember("constants")]
    object? constants { get; }

    // Promise API
    /// <summary>
    /// Node.js signature: <c>fsPromises.access(path[, mode])</c>.
    /// </summary>
    [NodeModuleMember("access")]
    global::JavaScriptRuntime.IJavaScriptPromise access(object? path);

    /// <summary>
    /// Node.js signature: <c>fsPromises.access(path[, mode])</c>.
    /// </summary>
    [NodeModuleMember("access")]
    global::JavaScriptRuntime.IJavaScriptPromise access(object? path, object? mode);

    /// <summary>
    /// Node.js signature: <c>fsPromises.appendFile(path, data[, options])</c>.
    /// </summary>
    [NodeModuleMember("appendFile")]
    global::JavaScriptRuntime.IJavaScriptPromise appendFile(object? path, object? data);

    /// <summary>
    /// Node.js signature: <c>fsPromises.appendFile(path, data[, options])</c>.
    /// </summary>
    [NodeModuleMember("appendFile")]
    global::JavaScriptRuntime.IJavaScriptPromise appendFile(object? path, object? data, object? options);

    /// <summary>
    /// Node.js signature: <c>fsPromises.chmod(path, mode)</c>.
    /// </summary>
    [NodeModuleMember("chmod")]
    global::JavaScriptRuntime.IJavaScriptPromise chmod(object? path, object? mode);

    /// <summary>
    /// Node.js signature: <c>fsPromises.chown(path, uid, gid)</c>.
    /// </summary>
    [NodeModuleMember("chown")]
    global::JavaScriptRuntime.IJavaScriptPromise chown(object? path, double uid, double gid);

    /// <summary>
    /// Node.js signature: <c>fsPromises.copyFile(src, dest[, mode])</c>.
    /// </summary>
    [NodeModuleMember("copyFile")]
    global::JavaScriptRuntime.IJavaScriptPromise copyFile(object? src, object? dest);

    /// <summary>
    /// Node.js signature: <c>fsPromises.copyFile(src, dest[, mode])</c>.
    /// </summary>
    [NodeModuleMember("copyFile")]
    global::JavaScriptRuntime.IJavaScriptPromise copyFile(object? src, object? dest, object? mode);

    /// <summary>
    /// Node.js signature: <c>fsPromises.cp(src, dest[, options])</c>.
    /// </summary>
    [NodeModuleMember("cp")]
    global::JavaScriptRuntime.IJavaScriptPromise cp(object? src, object? dest);

    /// <summary>
    /// Node.js signature: <c>fsPromises.cp(src, dest[, options])</c>.
    /// </summary>
    [NodeModuleMember("cp")]
    global::JavaScriptRuntime.IJavaScriptPromise cp(object? src, object? dest, object? options);

    /// <summary>
    /// Node.js signature: <c>fsPromises.glob(pattern[, options])</c>.
    /// </summary>
    [NodeModuleMember("glob")]
    global::JavaScriptRuntime.IJavaScriptAsyncIterator glob(object? pattern);

    /// <summary>
    /// Node.js signature: <c>fsPromises.glob(pattern[, options])</c>.
    /// </summary>
    [NodeModuleMember("glob")]
    global::JavaScriptRuntime.IJavaScriptAsyncIterator glob(object? pattern, object? options);

    /// <summary>
    /// Node.js signature: <c>fsPromises.lchmod(path, mode)</c>.
    /// </summary>
    [global::System.Obsolete("Deprecated by Node.js since v10.0.0.")]
    [NodeModuleMember("lchmod")]
    global::JavaScriptRuntime.IJavaScriptPromise lchmod(object? path, double mode);

    /// <summary>
    /// Node.js signature: <c>fsPromises.lchown(path, uid, gid)</c>.
    /// </summary>
    [NodeModuleMember("lchown")]
    global::JavaScriptRuntime.IJavaScriptPromise lchown(object? path, double uid, double gid);

    /// <summary>
    /// Node.js signature: <c>fsPromises.lutimes(path, atime, mtime)</c>.
    /// </summary>
    [NodeModuleMember("lutimes")]
    global::JavaScriptRuntime.IJavaScriptPromise lutimes(object? path, object? atime, object? mtime);

    /// <summary>
    /// Node.js signature: <c>fsPromises.link(existingPath, newPath)</c>.
    /// </summary>
    [NodeModuleMember("link")]
    global::JavaScriptRuntime.IJavaScriptPromise link(object? existingPath, object? newPath);

    /// <summary>
    /// Node.js signature: <c>fsPromises.lstat(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("lstat")]
    global::JavaScriptRuntime.IJavaScriptPromise lstat(object? path);

    /// <summary>
    /// Node.js signature: <c>fsPromises.lstat(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("lstat")]
    global::JavaScriptRuntime.IJavaScriptPromise lstat(object? path, object? options);

    /// <summary>
    /// Node.js signature: <c>fsPromises.mkdir(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("mkdir")]
    global::JavaScriptRuntime.IJavaScriptPromise mkdir(object? path);

    /// <summary>
    /// Node.js signature: <c>fsPromises.mkdir(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("mkdir")]
    global::JavaScriptRuntime.IJavaScriptPromise mkdir(object? path, object? options);

    /// <summary>
    /// Node.js signature: <c>fsPromises.mkdtemp(prefix[, options])</c>.
    /// </summary>
    [NodeModuleMember("mkdtemp")]
    global::JavaScriptRuntime.IJavaScriptPromise mkdtemp(object? prefix);

    /// <summary>
    /// Node.js signature: <c>fsPromises.mkdtemp(prefix[, options])</c>.
    /// </summary>
    [NodeModuleMember("mkdtemp")]
    global::JavaScriptRuntime.IJavaScriptPromise mkdtemp(object? prefix, object? options);

    /// <summary>
    /// Node.js signature: <c>fsPromises.mkdtempDisposable(prefix[, options])</c>.
    /// </summary>
    [NodeModuleMember("mkdtempDisposable")]
    global::JavaScriptRuntime.IJavaScriptPromise mkdtempDisposable(object? prefix);

    /// <summary>
    /// Node.js signature: <c>fsPromises.mkdtempDisposable(prefix[, options])</c>.
    /// </summary>
    [NodeModuleMember("mkdtempDisposable")]
    global::JavaScriptRuntime.IJavaScriptPromise mkdtempDisposable(object? prefix, object? options);

    /// <summary>
    /// Node.js signature: <c>fsPromises.open(path, flags[, mode])</c>.
    /// </summary>
    [NodeModuleMember("open")]
    global::JavaScriptRuntime.IJavaScriptPromise open(object? path, object? flags);

    /// <summary>
    /// Node.js signature: <c>fsPromises.open(path, flags[, mode])</c>.
    /// </summary>
    [NodeModuleMember("open")]
    global::JavaScriptRuntime.IJavaScriptPromise open(object? path, object? flags, object? mode);

    /// <summary>
    /// Node.js signature: <c>fsPromises.opendir(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("opendir")]
    global::JavaScriptRuntime.IJavaScriptPromise opendir(object? path);

    /// <summary>
    /// Node.js signature: <c>fsPromises.opendir(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("opendir")]
    global::JavaScriptRuntime.IJavaScriptPromise opendir(object? path, object? options);

    /// <summary>
    /// Node.js signature: <c>fsPromises.readdir(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("readdir")]
    global::JavaScriptRuntime.IJavaScriptPromise readdir(object? path);

    /// <summary>
    /// Node.js signature: <c>fsPromises.readdir(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("readdir")]
    global::JavaScriptRuntime.IJavaScriptPromise readdir(object? path, object? options);

    /// <summary>
    /// Node.js signature: <c>fsPromises.readFile(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("readFile")]
    global::JavaScriptRuntime.IJavaScriptPromise readFile(object? path);

    /// <summary>
    /// Node.js signature: <c>fsPromises.readFile(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("readFile")]
    global::JavaScriptRuntime.IJavaScriptPromise readFile(object? path, object? options);

    /// <summary>
    /// Node.js signature: <c>fsPromises.readlink(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("readlink")]
    global::JavaScriptRuntime.IJavaScriptPromise readlink(object? path);

    /// <summary>
    /// Node.js signature: <c>fsPromises.readlink(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("readlink")]
    global::JavaScriptRuntime.IJavaScriptPromise readlink(object? path, object? options);

    /// <summary>
    /// Node.js signature: <c>fsPromises.realpath(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("realpath")]
    global::JavaScriptRuntime.IJavaScriptPromise realpath(object? path);

    /// <summary>
    /// Node.js signature: <c>fsPromises.realpath(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("realpath")]
    global::JavaScriptRuntime.IJavaScriptPromise realpath(object? path, object? options);

    /// <summary>
    /// Node.js signature: <c>fsPromises.rename(oldPath, newPath)</c>.
    /// </summary>
    [NodeModuleMember("rename")]
    global::JavaScriptRuntime.IJavaScriptPromise rename(object? oldPath, object? newPath);

    /// <summary>
    /// Node.js signature: <c>fsPromises.rmdir(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("rmdir")]
    global::JavaScriptRuntime.IJavaScriptPromise rmdir(object? path);

    /// <summary>
    /// Node.js signature: <c>fsPromises.rmdir(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("rmdir")]
    global::JavaScriptRuntime.IJavaScriptPromise rmdir(object? path, object? options);

    /// <summary>
    /// Node.js signature: <c>fsPromises.rm(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("rm")]
    global::JavaScriptRuntime.IJavaScriptPromise rm(object? path);

    /// <summary>
    /// Node.js signature: <c>fsPromises.rm(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("rm")]
    global::JavaScriptRuntime.IJavaScriptPromise rm(object? path, object? options);

    /// <summary>
    /// Node.js signature: <c>fsPromises.stat(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("stat")]
    global::JavaScriptRuntime.IJavaScriptPromise stat(object? path);

    /// <summary>
    /// Node.js signature: <c>fsPromises.stat(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("stat")]
    global::JavaScriptRuntime.IJavaScriptPromise stat(object? path, object? options);

    /// <summary>
    /// Node.js signature: <c>fsPromises.statfs(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("statfs")]
    global::JavaScriptRuntime.IJavaScriptPromise statfs(object? path);

    /// <summary>
    /// Node.js signature: <c>fsPromises.statfs(path[, options])</c>.
    /// </summary>
    [NodeModuleMember("statfs")]
    global::JavaScriptRuntime.IJavaScriptPromise statfs(object? path, object? options);

    /// <summary>
    /// Node.js signature: <c>fsPromises.symlink(target, path[, type])</c>.
    /// </summary>
    [NodeModuleMember("symlink")]
    global::JavaScriptRuntime.IJavaScriptPromise symlink(object? target, object? path);

    /// <summary>
    /// Node.js signature: <c>fsPromises.symlink(target, path[, type])</c>.
    /// </summary>
    [NodeModuleMember("symlink")]
    global::JavaScriptRuntime.IJavaScriptPromise symlink(object? target, object? path, object? type);

    /// <summary>
    /// Node.js signature: <c>fsPromises.truncate(path[, len])</c>.
    /// </summary>
    [NodeModuleMember("truncate")]
    global::JavaScriptRuntime.IJavaScriptPromise truncate(object? path);

    /// <summary>
    /// Node.js signature: <c>fsPromises.truncate(path[, len])</c>.
    /// </summary>
    [NodeModuleMember("truncate")]
    global::JavaScriptRuntime.IJavaScriptPromise truncate(object? path, object? len);

    /// <summary>
    /// Node.js signature: <c>fsPromises.unlink(path)</c>.
    /// </summary>
    [NodeModuleMember("unlink")]
    global::JavaScriptRuntime.IJavaScriptPromise unlink(object? path);

    /// <summary>
    /// Node.js signature: <c>fsPromises.utimes(path, atime, mtime)</c>.
    /// </summary>
    [NodeModuleMember("utimes")]
    global::JavaScriptRuntime.IJavaScriptPromise utimes(object? path, object? atime, object? mtime);

    /// <summary>
    /// Node.js signature: <c>fsPromises.watch(filename[, options])</c>.
    /// </summary>
    [NodeModuleMember("watch")]
    global::JavaScriptRuntime.IJavaScriptAsyncIterator watch(object? filename);

    /// <summary>
    /// Node.js signature: <c>fsPromises.watch(filename[, options])</c>.
    /// </summary>
    [NodeModuleMember("watch")]
    global::JavaScriptRuntime.IJavaScriptAsyncIterator watch(object? filename, object? options);

    /// <summary>
    /// Node.js signature: <c>fsPromises.writeFile(file, data[, options])</c>.
    /// </summary>
    [NodeModuleMember("writeFile")]
    global::JavaScriptRuntime.IJavaScriptPromise writeFile(object? file, object? data);

    /// <summary>
    /// Node.js signature: <c>fsPromises.writeFile(file, data[, options])</c>.
    /// </summary>
    [NodeModuleMember("writeFile")]
    global::JavaScriptRuntime.IJavaScriptPromise writeFile(object? file, object? data, object? options);

}
