// <auto-generated />
// Generated from the official Node.js 24.18.1 fs API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/fs.json
// SHA-256: 3145e3751afc28b868f9b481788a081fd87adf3215aa638f850fcb52d636ab6b

#nullable enable

namespace Jroc.Runtime.Node.Contracts;

/// <summary>
/// Defines the documented <c>node:fs.ReadFileOptions</c> contract.
/// </summary>
/// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/fs.html#fsreadfilepath-options-callback</c>.</remarks>
[global::System.CodeDom.Compiler.GeneratedCode("generateNodeModuleInterface.js", "sha256:de7d46c347d581581a76dc391aa1fcd75d184d772e05ee622c88f4c5b6aa96ad")]
[NodeModuleType("fs", "ReadFileOptions")]
public interface IFsReadFileOptions : IJavaScriptValueHost
{
    /// <summary>
    /// Gets <c>encoding</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/fs.html#fsreadfilepath-options-callback</c>.</remarks>
    [NodeModuleMember("encoding")]
    object? encoding { get; }

    /// <summary>
    /// Gets <c>flag</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/fs.html#fsreadfilepath-options-callback</c>.</remarks>
    [NodeModuleMember("flag")]
    object? flag { get; }

}
