// <auto-generated />
// Generated from the official Node.js 24.18.1 fs API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/fs.json
// SHA-256: 3145e3751afc28b868f9b481788a081fd87adf3215aa638f850fcb52d636ab6b

#nullable enable

namespace Jroc.Runtime.Node.Contracts;

/// <summary>
/// Defines the documented <c>node:fs.WriteFileOptions</c> contract.
/// </summary>
/// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/fs.html#fswritefilefile-data-options-callback</c>.</remarks>
[global::System.CodeDom.Compiler.GeneratedCode("generateNodeModuleInterface.js", "sha256:9126c7db48fedfbf7645d8b0f91f5cd9ce18f98db5f0ed246b9e0b8eee2b872d")]
[NodeModuleType("fs", "WriteFileOptions")]
public interface IFsWriteFileOptions : IJavaScriptValueHost
{
    /// <summary>
    /// Gets <c>encoding</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/fs.html#fswritefilefile-data-options-callback</c>.</remarks>
    [NodeModuleMember("encoding")]
    object? encoding { get; }

    /// <summary>
    /// Gets <c>mode</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/fs.html#fswritefilefile-data-options-callback</c>.</remarks>
    [NodeModuleMember("mode")]
    object? mode { get; }

    /// <summary>
    /// Gets <c>flag</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/fs.html#fswritefilefile-data-options-callback</c>.</remarks>
    [NodeModuleMember("flag")]
    object? flag { get; }

    /// <summary>
    /// Gets <c>flush</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/fs.html#fswritefilefile-data-options-callback</c>.</remarks>
    [NodeModuleMember("flush")]
    bool flush { get; }

}
