// <auto-generated />
// Generated from the official Node.js 24.18.1 http API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/http.json
// SHA-256: 25994076a4ed8a903b743eab54b9b9f7509497fd2f0a49bf00eee291145a8a1b

#nullable enable

namespace Jroc.Runtime.Node.Contracts;

/// <summary>
/// Defines the public top-level <c>node:http</c> module contract from Node.js 24.18.1.
/// </summary>
/// <remarks>
/// Nested option, result, and handle contracts intentionally remain dynamic in this proof of concept.
/// They will be strongly typed by the work tracked in GitHub issue #1660.
/// </remarks>
[global::System.CodeDom.Compiler.GeneratedCode("generateNodeModuleInterface.js", "sha256:e0d88d11483936ce8b947360e0bac6d198acd445d3e7638f60398a795de2bba7")]
[NodeModuleInterface("http")]
public interface IHttpModule
{
    /// <summary>
    /// Gets the exported <c>http.METHODS</c> member.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/http.html#httpmethods</c>.</remarks>
    [NodeModuleMember("METHODS")]
    global::JavaScriptRuntime.IJavaScriptArray METHODS { get; }

    /// <summary>
    /// Gets the exported <c>http.STATUS_CODES</c> member.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/http.html#httpstatus_codes</c>.</remarks>
    [NodeModuleMember("STATUS_CODES")]
    object? STATUS_CODES { get; }

    /// <summary>
    /// Gets the exported <c>http.globalAgent</c> member.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/http.html#httpglobalagent</c>.</remarks>
    [NodeModuleMember("globalAgent")]
    object? globalAgent { get; set; }

    /// <summary>
    /// Gets the exported <c>http.maxHeaderSize</c> member.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/http.html#httpmaxheadersize</c>.</remarks>
    [NodeModuleMember("maxHeaderSize")]
    double maxHeaderSize { get; }

    /// <summary>
    /// Gets the exported <c>http.Agent</c> member.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/http.html#class-httpagent</c>.</remarks>
    [NodeModuleMember("Agent")]
    object? Agent { get; }

    /// <summary>
    /// Gets the exported <c>http.ClientRequest</c> member.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/http.html#class-httpclientrequest</c>.</remarks>
    [NodeModuleMember("ClientRequest")]
    object? ClientRequest { get; }

    /// <summary>
    /// Gets the exported <c>http.IncomingMessage</c> member.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/http.html#class-httpincomingmessage</c>.</remarks>
    [NodeModuleMember("IncomingMessage")]
    object? IncomingMessage { get; }

    /// <summary>
    /// Gets the exported <c>http.OutgoingMessage</c> member.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/http.html#class-httpoutgoingmessage</c>.</remarks>
    [NodeModuleMember("OutgoingMessage")]
    object? OutgoingMessage { get; }

    /// <summary>
    /// Gets the exported <c>http.Server</c> member.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/http.html#class-httpserver</c>.</remarks>
    [NodeModuleMember("Server")]
    object? Server { get; }

    /// <summary>
    /// Gets the exported <c>http.ServerResponse</c> member.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/http.html#class-httpserverresponse</c>.</remarks>
    [NodeModuleMember("ServerResponse")]
    object? ServerResponse { get; }

    /// <summary>
    /// Gets the exported <c>http.WebSocket</c> member.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/http.html#class-websocket</c>.</remarks>
    [NodeModuleMember("WebSocket")]
    object? WebSocket { get; }

    // node:http methods
    /// <summary>
    /// Node.js signature: <c>http.createServer([options][, requestListener])</c>.
    /// </summary>
    [NodeModuleMember("createServer")]
    object? createServer();

    /// <summary>
    /// Node.js signature: <c>http.createServer([options][, requestListener])</c>.
    /// </summary>
    [NodeModuleMember("createServer")]
    object? createServer(object? requestListener);

    /// <summary>
    /// Node.js signature: <c>http.createServer([options][, requestListener])</c>.
    /// </summary>
    [NodeModuleMember("createServer")]
    object? createServer(object? options, object? requestListener);

    /// <summary>
    /// Node.js signature: <c>http.validateHeaderName(name[, label])</c>.
    /// </summary>
    [NodeModuleMember("validateHeaderName")]
    void validateHeaderName(string name);

    /// <summary>
    /// Node.js signature: <c>http.validateHeaderName(name[, label])</c>.
    /// </summary>
    [NodeModuleMember("validateHeaderName")]
    void validateHeaderName(string name, object? label);

    /// <summary>
    /// Node.js signature: <c>http.validateHeaderValue(name, value)</c>.
    /// </summary>
    [NodeModuleMember("validateHeaderValue")]
    void validateHeaderValue(string name, object? value);

    /// <summary>
    /// Node.js signature: <c>http.setMaxIdleHTTPParsers(max)</c>.
    /// </summary>
    [NodeModuleMember("setMaxIdleHTTPParsers")]
    void setMaxIdleHTTPParsers(double max);

    /// <summary>
    /// Node.js signature: <c>http.setGlobalProxyFromEnv([proxyEnv])</c>.
    /// </summary>
    [NodeModuleMember("setGlobalProxyFromEnv")]
    global::System.Delegate setGlobalProxyFromEnv();

    /// <summary>
    /// Node.js signature: <c>http.setGlobalProxyFromEnv([proxyEnv])</c>.
    /// </summary>
    [NodeModuleMember("setGlobalProxyFromEnv")]
    global::System.Delegate setGlobalProxyFromEnv(object? proxyEnv);

    /// <summary>
    /// Node.js signatures: <c>http.get(options[, callback])</c>, <c>http.get(url[, options][, callback])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/http.html#httpget</c>.</remarks>
    [NodeModuleMember("get")]
    object? get(object? optionsOrUrl);

    /// <summary>
    /// Node.js signatures: <c>http.get(options[, callback])</c>, <c>http.get(url[, options][, callback])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/http.html#httpget</c>.</remarks>
    [NodeModuleMember("get")]
    object? get(object? optionsOrUrl, global::System.Delegate callback);

    /// <summary>
    /// Node.js signatures: <c>http.get(options[, callback])</c>, <c>http.get(url[, options][, callback])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/http.html#httpget</c>.</remarks>
    [NodeModuleMember("get")]
    object? get(object? url, object? options);

    /// <summary>
    /// Node.js signatures: <c>http.get(options[, callback])</c>, <c>http.get(url[, options][, callback])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/http.html#httpget</c>.</remarks>
    [NodeModuleMember("get")]
    object? get(object? url, object? options, global::System.Delegate callback);

    /// <summary>
    /// Node.js signatures: <c>http.request(options[, callback])</c>, <c>http.request(url[, options][, callback])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/http.html#httprequest</c>.</remarks>
    [NodeModuleMember("request")]
    object? request(object? optionsOrUrl);

    /// <summary>
    /// Node.js signatures: <c>http.request(options[, callback])</c>, <c>http.request(url[, options][, callback])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/http.html#httprequest</c>.</remarks>
    [NodeModuleMember("request")]
    object? request(object? optionsOrUrl, global::System.Delegate callback);

    /// <summary>
    /// Node.js signatures: <c>http.request(options[, callback])</c>, <c>http.request(url[, options][, callback])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/http.html#httprequest</c>.</remarks>
    [NodeModuleMember("request")]
    object? request(object? url, object? options);

    /// <summary>
    /// Node.js signatures: <c>http.request(options[, callback])</c>, <c>http.request(url[, options][, callback])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/http.html#httprequest</c>.</remarks>
    [NodeModuleMember("request")]
    object? request(object? url, object? options, global::System.Delegate callback);

}
