// <auto-generated />
// Generated from the official Node.js 24.18.1 https API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/https.json
// SHA-256: 01cd27f75bfd46f819893ef3d1de923603f97dfe368ef792858e5a745c7fe016

#nullable enable

namespace Jroc.Runtime.Node.Contracts;

/// <summary>
/// Defines the public top-level <c>node:https</c> module contract from Node.js 24.18.1.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCode("generateNodeModuleInterface.js", "sha256:13ea61f00a6a5629ba94c535a3f32f6ddcc06ed57c5bde2aa5bdbf56d257d242")]
[NodeModuleInterface("https")]
public interface IHttpsModule
{
    /// <summary>
    /// Gets the exported <c>https.globalAgent</c> member.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/https.html#httpsglobalagent</c>.</remarks>
    [NodeModuleMember("globalAgent")]
    object? globalAgent { get; set; }

    /// <summary>
    /// Gets the exported <c>https.Agent</c> member.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/https.html#class-httpsagent</c>.</remarks>
    [NodeModuleMember("Agent")]
    object? Agent { get; }

    /// <summary>
    /// Gets the exported <c>https.Server</c> member.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/https.html#class-httpsserver</c>.</remarks>
    [NodeModuleMember("Server")]
    object? Server { get; }

    // node:https methods
    /// <summary>
    /// Node.js signature: <c>https.createServer([options][, requestListener])</c>.
    /// </summary>
    [NodeModuleMember("createServer")]
    object? createServer();

    /// <summary>
    /// Node.js signature: <c>https.createServer([options][, requestListener])</c>.
    /// </summary>
    [NodeModuleMember("createServer")]
    object? createServer(object? requestListener);

    /// <summary>
    /// Node.js signature: <c>https.createServer([options][, requestListener])</c>.
    /// </summary>
    [NodeModuleMember("createServer")]
    object? createServer(object? options, object? requestListener);

    /// <summary>
    /// Node.js signatures: <c>https.get(options[, callback])</c>, <c>https.get(url[, options][, callback])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/https.html#httpsget</c>.</remarks>
    [NodeModuleMember("get")]
    object? get(object? optionsOrUrl);

    /// <summary>
    /// Node.js signatures: <c>https.get(options[, callback])</c>, <c>https.get(url[, options][, callback])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/https.html#httpsget</c>.</remarks>
    [NodeModuleMember("get")]
    object? get(object? optionsOrUrl, global::System.Delegate callback);

    /// <summary>
    /// Node.js signatures: <c>https.get(options[, callback])</c>, <c>https.get(url[, options][, callback])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/https.html#httpsget</c>.</remarks>
    [NodeModuleMember("get")]
    object? get(object? url, object? options);

    /// <summary>
    /// Node.js signatures: <c>https.get(options[, callback])</c>, <c>https.get(url[, options][, callback])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/https.html#httpsget</c>.</remarks>
    [NodeModuleMember("get")]
    object? get(object? url, object? options, global::System.Delegate callback);

    /// <summary>
    /// Node.js signatures: <c>https.request(options[, callback])</c>, <c>https.request(url[, options][, callback])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/https.html#httpsrequest</c>.</remarks>
    [NodeModuleMember("request")]
    object? request(object? optionsOrUrl);

    /// <summary>
    /// Node.js signatures: <c>https.request(options[, callback])</c>, <c>https.request(url[, options][, callback])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/https.html#httpsrequest</c>.</remarks>
    [NodeModuleMember("request")]
    object? request(object? optionsOrUrl, global::System.Delegate callback);

    /// <summary>
    /// Node.js signatures: <c>https.request(options[, callback])</c>, <c>https.request(url[, options][, callback])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/https.html#httpsrequest</c>.</remarks>
    [NodeModuleMember("request")]
    object? request(object? url, object? options);

    /// <summary>
    /// Node.js signatures: <c>https.request(options[, callback])</c>, <c>https.request(url[, options][, callback])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/https.html#httpsrequest</c>.</remarks>
    [NodeModuleMember("request")]
    object? request(object? url, object? options, global::System.Delegate callback);

}
