// <auto-generated />
// Generated from the official Node.js 24.18.1 net API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/net.json
// SHA-256: 2d33daee78e804a2eab914dde4bb3a70fd1fa8b48a8e7bb0563f26b473be7d27

#nullable enable

namespace Jroc.Runtime.Node.Contracts;

/// <summary>
/// Defines the public top-level <c>node:net</c> module contract from Node.js 24.18.1.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCode("generateNodeModuleInterface.js", "sha256:9126c7db48fedfbf7645d8b0f91f5cd9ce18f98db5f0ed246b9e0b8eee2b872d")]
[NodeModuleInterface("net")]
public interface INetModule
{
    /// <summary>
    /// Gets the exported <c>net.BlockList</c> member.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/net.html#class-netblocklist</c>.</remarks>
    [NodeModuleMember("BlockList")]
    object? BlockList { get; }

    /// <summary>
    /// Gets the exported <c>net.SocketAddress</c> member.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/net.html#class-netsocketaddress</c>.</remarks>
    [NodeModuleMember("SocketAddress")]
    object? SocketAddress { get; }

    /// <summary>
    /// Gets the exported <c>net.Server</c> member.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/net.html#class-netserver</c>.</remarks>
    [NodeModuleMember("Server")]
    object? Server { get; }

    /// <summary>
    /// Gets the exported <c>net.Socket</c> member.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/net.html#class-netsocket</c>.</remarks>
    [NodeModuleMember("Socket")]
    object? Socket { get; }

    // node:net methods
    /// <summary>
    /// Node.js signatures: <c>net.connect(options[, connectListener])</c>, <c>net.connect(path[, connectListener])</c>, <c>net.connect(port[, host][, connectListener])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/net.html#netconnect</c>.</remarks>
    [NodeModuleMember("connect")]
    object? connect(object? options);

    /// <summary>
    /// Node.js signatures: <c>net.connect(options[, connectListener])</c>, <c>net.connect(path[, connectListener])</c>, <c>net.connect(port[, host][, connectListener])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/net.html#netconnect</c>.</remarks>
    [NodeModuleMember("connect")]
    object? connect(object? options, global::System.Delegate connectListener);

    /// <summary>
    /// Node.js signatures: <c>net.connect(options[, connectListener])</c>, <c>net.connect(path[, connectListener])</c>, <c>net.connect(port[, host][, connectListener])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/net.html#netconnect</c>.</remarks>
    [NodeModuleMember("connect")]
    object? connect(string path);

    /// <summary>
    /// Node.js signatures: <c>net.connect(options[, connectListener])</c>, <c>net.connect(path[, connectListener])</c>, <c>net.connect(port[, host][, connectListener])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/net.html#netconnect</c>.</remarks>
    [NodeModuleMember("connect")]
    object? connect(string path, global::System.Delegate connectListener);

    /// <summary>
    /// Node.js signatures: <c>net.connect(options[, connectListener])</c>, <c>net.connect(path[, connectListener])</c>, <c>net.connect(port[, host][, connectListener])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/net.html#netconnect</c>.</remarks>
    [NodeModuleMember("connect")]
    object? connect(double port);

    /// <summary>
    /// Node.js signatures: <c>net.connect(options[, connectListener])</c>, <c>net.connect(path[, connectListener])</c>, <c>net.connect(port[, host][, connectListener])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/net.html#netconnect</c>.</remarks>
    [NodeModuleMember("connect")]
    object? connect(double port, string host);

    /// <summary>
    /// Node.js signatures: <c>net.connect(options[, connectListener])</c>, <c>net.connect(path[, connectListener])</c>, <c>net.connect(port[, host][, connectListener])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/net.html#netconnect</c>.</remarks>
    [NodeModuleMember("connect")]
    object? connect(double port, global::System.Delegate connectListener);

    /// <summary>
    /// Node.js signatures: <c>net.connect(options[, connectListener])</c>, <c>net.connect(path[, connectListener])</c>, <c>net.connect(port[, host][, connectListener])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/net.html#netconnect</c>.</remarks>
    [NodeModuleMember("connect")]
    object? connect(double port, string host, global::System.Delegate connectListener);

    /// <summary>
    /// Node.js signatures: <c>net.createConnection(options[, connectListener])</c>, <c>net.createConnection(path[, connectListener])</c>, <c>net.createConnection(port[, host][, connectListener])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/net.html#netcreateconnection</c>.</remarks>
    [NodeModuleMember("createConnection")]
    object? createConnection(object? options);

    /// <summary>
    /// Node.js signatures: <c>net.createConnection(options[, connectListener])</c>, <c>net.createConnection(path[, connectListener])</c>, <c>net.createConnection(port[, host][, connectListener])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/net.html#netcreateconnection</c>.</remarks>
    [NodeModuleMember("createConnection")]
    object? createConnection(object? options, global::System.Delegate connectListener);

    /// <summary>
    /// Node.js signatures: <c>net.createConnection(options[, connectListener])</c>, <c>net.createConnection(path[, connectListener])</c>, <c>net.createConnection(port[, host][, connectListener])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/net.html#netcreateconnection</c>.</remarks>
    [NodeModuleMember("createConnection")]
    object? createConnection(string path);

    /// <summary>
    /// Node.js signatures: <c>net.createConnection(options[, connectListener])</c>, <c>net.createConnection(path[, connectListener])</c>, <c>net.createConnection(port[, host][, connectListener])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/net.html#netcreateconnection</c>.</remarks>
    [NodeModuleMember("createConnection")]
    object? createConnection(string path, global::System.Delegate connectListener);

    /// <summary>
    /// Node.js signatures: <c>net.createConnection(options[, connectListener])</c>, <c>net.createConnection(path[, connectListener])</c>, <c>net.createConnection(port[, host][, connectListener])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/net.html#netcreateconnection</c>.</remarks>
    [NodeModuleMember("createConnection")]
    object? createConnection(double port);

    /// <summary>
    /// Node.js signatures: <c>net.createConnection(options[, connectListener])</c>, <c>net.createConnection(path[, connectListener])</c>, <c>net.createConnection(port[, host][, connectListener])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/net.html#netcreateconnection</c>.</remarks>
    [NodeModuleMember("createConnection")]
    object? createConnection(double port, string host);

    /// <summary>
    /// Node.js signatures: <c>net.createConnection(options[, connectListener])</c>, <c>net.createConnection(path[, connectListener])</c>, <c>net.createConnection(port[, host][, connectListener])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/net.html#netcreateconnection</c>.</remarks>
    [NodeModuleMember("createConnection")]
    object? createConnection(double port, global::System.Delegate connectListener);

    /// <summary>
    /// Node.js signatures: <c>net.createConnection(options[, connectListener])</c>, <c>net.createConnection(path[, connectListener])</c>, <c>net.createConnection(port[, host][, connectListener])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/net.html#netcreateconnection</c>.</remarks>
    [NodeModuleMember("createConnection")]
    object? createConnection(double port, string host, global::System.Delegate connectListener);

    /// <summary>
    /// Node.js signature: <c>net.createServer([options][, connectionListener])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/net.html#netcreateserveroptions-connectionlistener</c>.</remarks>
    [NodeModuleMember("createServer")]
    object? createServer();

    /// <summary>
    /// Node.js signature: <c>net.createServer([options][, connectionListener])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/net.html#netcreateserveroptions-connectionlistener</c>.</remarks>
    [NodeModuleMember("createServer")]
    object? createServer(object? options);

    /// <summary>
    /// Node.js signature: <c>net.createServer([options][, connectionListener])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/net.html#netcreateserveroptions-connectionlistener</c>.</remarks>
    [NodeModuleMember("createServer")]
    object? createServer(global::System.Delegate connectionListener);

    /// <summary>
    /// Node.js signature: <c>net.createServer([options][, connectionListener])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/net.html#netcreateserveroptions-connectionlistener</c>.</remarks>
    [NodeModuleMember("createServer")]
    object? createServer(object? options, global::System.Delegate connectionListener);

    /// <summary>
    /// Node.js signature: <c>net.getDefaultAutoSelectFamily()</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/net.html#netgetdefaultautoselectfamily</c>.</remarks>
    [NodeModuleMember("getDefaultAutoSelectFamily")]
    bool getDefaultAutoSelectFamily();

    /// <summary>
    /// Node.js signature: <c>net.setDefaultAutoSelectFamily(value)</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/net.html#netsetdefaultautoselectfamilyvalue</c>.</remarks>
    [NodeModuleMember("setDefaultAutoSelectFamily")]
    void setDefaultAutoSelectFamily(bool value);

    /// <summary>
    /// Node.js signature: <c>net.getDefaultAutoSelectFamilyAttemptTimeout()</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/net.html#netgetdefaultautoselectfamilyattempttimeout</c>.</remarks>
    [NodeModuleMember("getDefaultAutoSelectFamilyAttemptTimeout")]
    double getDefaultAutoSelectFamilyAttemptTimeout();

    /// <summary>
    /// Node.js signature: <c>net.setDefaultAutoSelectFamilyAttemptTimeout(value)</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/net.html#netsetdefaultautoselectfamilyattempttimeoutvalue</c>.</remarks>
    [NodeModuleMember("setDefaultAutoSelectFamilyAttemptTimeout")]
    void setDefaultAutoSelectFamilyAttemptTimeout(double value);

    /// <summary>
    /// Node.js signature: <c>net.isIP(input)</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/net.html#netisipinput</c>.</remarks>
    [NodeModuleMember("isIP")]
    double isIP(string input);

    /// <summary>
    /// Node.js signature: <c>net.isIPv4(input)</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/net.html#netisipv4input</c>.</remarks>
    [NodeModuleMember("isIPv4")]
    bool isIPv4(string input);

    /// <summary>
    /// Node.js signature: <c>net.isIPv6(input)</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/net.html#netisipv6input</c>.</remarks>
    [NodeModuleMember("isIPv6")]
    bool isIPv6(string input);

}
