// <auto-generated />
// Generated from the official Node.js 24.18.1 path API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/path.json
// SHA-256: 9f93050a3383e78ffb2ac7f14f5c2addf1f030488481e8508e9c3097ba62a296

#nullable enable

namespace Jroc.Runtime.Node.Contracts;

/// <summary>
/// Defines the public top-level <c>node:path</c> module contract from Node.js 24.18.1.
/// </summary>
/// <remarks>
/// Nested option, result, and handle contracts intentionally remain dynamic in this proof of concept.
/// They will be strongly typed by the work tracked in GitHub issue #1660.
/// </remarks>
[global::System.CodeDom.Compiler.GeneratedCode("generateNodeModuleInterface.js", "sha256:6fe985f5ad468d3c30e514e91fe24149b71ecea13c7f0c442a919937f14d07f2")]
[NodeModuleInterface("path")]
public interface IPathModule
{
    /// <summary>
    /// Node.js property: <c>`delimiter` Type: {string}</c>.
    /// </summary>
    [NodeModuleMember("delimiter")]
    string delimiter { get; }

    /// <summary>
    /// Node.js property: <c>`posix` Type: {Object}</c>.
    /// </summary>
    [NodeModuleMember("posix")]
    object? posix { get; }

    /// <summary>
    /// Node.js property: <c>`sep` Type: {string}</c>.
    /// </summary>
    [NodeModuleMember("sep")]
    string sep { get; }

    /// <summary>
    /// Node.js property: <c>`win32` Type: {Object}</c>.
    /// </summary>
    [NodeModuleMember("win32")]
    object? win32 { get; }

    // Path methods
    /// <summary>
    /// Node.js signature: <c>path.basename(path[, suffix])</c>.
    /// </summary>
    [NodeModuleMember("basename")]
    string basename(string path);

    /// <summary>
    /// Node.js signature: <c>path.basename(path[, suffix])</c>.
    /// </summary>
    [NodeModuleMember("basename")]
    string basename(string path, object? suffix);

    /// <summary>
    /// Node.js signature: <c>path.dirname(path)</c>.
    /// </summary>
    [NodeModuleMember("dirname")]
    string dirname(string path);

    /// <summary>
    /// Node.js signature: <c>path.extname(path)</c>.
    /// </summary>
    [NodeModuleMember("extname")]
    string extname(string path);

    /// <summary>
    /// Node.js signature: <c>path.format(pathObject)</c>.
    /// </summary>
    [NodeModuleMember("format")]
    string format(object? pathObject);

    /// <summary>
    /// Node.js signature: <c>path.matchesGlob(path, pattern)</c>.
    /// </summary>
    [NodeModuleMember("matchesGlob")]
    bool matchesGlob(string path, string pattern);

    /// <summary>
    /// Node.js signature: <c>path.isAbsolute(path)</c>.
    /// </summary>
    [NodeModuleMember("isAbsolute")]
    bool isAbsolute(string path);

    /// <summary>
    /// Node.js signature: <c>path.join([...paths])</c>.
    /// </summary>
    [NodeModuleMember("join")]
    string join(params object?[] paths);

    /// <summary>
    /// Node.js signature: <c>path.normalize(path)</c>.
    /// </summary>
    [NodeModuleMember("normalize")]
    string normalize(string path);

    /// <summary>
    /// Node.js signature: <c>path.parse(path)</c>.
    /// </summary>
    [NodeModuleMember("parse")]
    object? parse(string path);

    /// <summary>
    /// Node.js signature: <c>path.relative(from, to)</c>.
    /// </summary>
    [NodeModuleMember("relative")]
    string relative(string from, string to);

    /// <summary>
    /// Node.js signature: <c>path.resolve([...paths])</c>.
    /// </summary>
    [NodeModuleMember("resolve")]
    string resolve(params object?[] paths);

    /// <summary>
    /// Node.js signature: <c>path.toNamespacedPath(path)</c>.
    /// </summary>
    [NodeModuleMember("toNamespacedPath")]
    string toNamespacedPath(string path);

}
