// <auto-generated />
// Generated from the official Node.js 24.18.1 perf_hooks API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/perf_hooks.json
// SHA-256: f01887a857d70a430f9d13b13b5e98641f1d6d12b1259dea0baaa74a996ab4b7

#nullable enable

namespace Jroc.Runtime.Node.Contracts;

/// <summary>
/// Defines the documented <c>node:perf_hooks.Performance</c> contract.
/// </summary>
/// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/perf_hooks.html#perf_hooksperformance</c>.</remarks>
[global::System.CodeDom.Compiler.GeneratedCode("generateNodeModuleInterface.js", "sha256:de7d46c347d581581a76dc391aa1fcd75d184d772e05ee622c88f4c5b6aa96ad")]
[NodeModuleType("perf_hooks", "Performance")]
public interface IPerfHooksPerformance : IJavaScriptValueHost
{
    /// <summary>
    /// Node.js signature: <c>performance.now()</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/perf_hooks.html#performancenow</c>.</remarks>
    [NodeModuleMember("now")]
    double now();

}
