// <auto-generated />
// Generated from the official Node.js 24.18.1 perf_hooks API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/perf_hooks.json
// SHA-256: f01887a857d70a430f9d13b13b5e98641f1d6d12b1259dea0baaa74a996ab4b7

#nullable enable

namespace Jroc.Runtime.Node.Contracts;

/// <summary>
/// Defines the public top-level <c>node:perf_hooks</c> module contract from Node.js 24.18.1.
/// </summary>
/// <remarks>
/// Nested option, result, and handle contracts intentionally remain dynamic in this proof of concept.
/// They will be strongly typed by the work tracked in GitHub issue #1660.
/// </remarks>
[global::System.CodeDom.Compiler.GeneratedCode("generateNodeModuleInterface.js", "sha256:be6e78d5530a6d86fe34cd3cb26bca862717703f0617ff439ff5d5caa18b8c25")]
[NodeModuleInterface("perf_hooks")]
public interface IPerfHooksModule
{
    /// <summary>
    /// Gets the exported <c>Performance</c> constructor.
    /// </summary>
    /// <remarks>Source: <c>https://github.com/nodejs/node/blob/v24.18.1/lib/perf_hooks.js</c>.</remarks>
    [NodeModuleMember("Performance")]
    object? Performance { get; }

    /// <summary>
    /// Gets the exported <c>PerformanceEntry</c> constructor.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/perf_hooks.html#class-performanceentry</c>.</remarks>
    [NodeModuleMember("PerformanceEntry")]
    object? PerformanceEntry { get; }

    /// <summary>
    /// Gets the exported <c>PerformanceMark</c> constructor.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/perf_hooks.html#class-performancemark</c>.</remarks>
    [NodeModuleMember("PerformanceMark")]
    object? PerformanceMark { get; }

    /// <summary>
    /// Gets the exported <c>PerformanceMeasure</c> constructor.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/perf_hooks.html#class-performancemeasure</c>.</remarks>
    [NodeModuleMember("PerformanceMeasure")]
    object? PerformanceMeasure { get; }

    /// <summary>
    /// Gets the exported <c>PerformanceObserver</c> constructor.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/perf_hooks.html#class-performanceobserver</c>.</remarks>
    [NodeModuleMember("PerformanceObserver")]
    object? PerformanceObserver { get; }

    /// <summary>
    /// Gets the exported <c>PerformanceObserverEntryList</c> constructor.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/perf_hooks.html#class-performanceobserverentrylist</c>.</remarks>
    [NodeModuleMember("PerformanceObserverEntryList")]
    object? PerformanceObserverEntryList { get; }

    /// <summary>
    /// Gets the exported <c>PerformanceResourceTiming</c> constructor.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/perf_hooks.html#class-performanceresourcetiming</c>.</remarks>
    [NodeModuleMember("PerformanceResourceTiming")]
    object? PerformanceResourceTiming { get; }

    /// <summary>
    /// Gets the exported performance constants object.
    /// </summary>
    /// <remarks>Source: <c>https://github.com/nodejs/node/blob/v24.18.1/lib/perf_hooks.js</c>.</remarks>
    [NodeModuleMember("constants")]
    object? constants { get; }

    /// <summary>
    /// Gets the shared performance measurement object.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/perf_hooks.html#perf_hooksperformance</c>.</remarks>
    [NodeModuleMember("performance")]
    object? performance { get; }

    // Performance hooks methods
    /// <summary>
    /// Node.js signature: <c>perf_hooks.createHistogram([options])</c>.
    /// </summary>
    [NodeModuleMember("createHistogram")]
    object? createHistogram();

    /// <summary>
    /// Node.js signature: <c>perf_hooks.createHistogram([options])</c>.
    /// </summary>
    [NodeModuleMember("createHistogram")]
    object? createHistogram(object? options);

    /// <summary>
    /// Node.js signature: <c>perf_hooks.eventLoopUtilization([utilization1[, utilization2]])</c>.
    /// </summary>
    [NodeModuleMember("eventLoopUtilization")]
    object? eventLoopUtilization();

    /// <summary>
    /// Node.js signature: <c>perf_hooks.eventLoopUtilization([utilization1[, utilization2]])</c>.
    /// </summary>
    [NodeModuleMember("eventLoopUtilization")]
    object? eventLoopUtilization(object? utilization1);

    /// <summary>
    /// Node.js signature: <c>perf_hooks.eventLoopUtilization([utilization1[, utilization2]])</c>.
    /// </summary>
    [NodeModuleMember("eventLoopUtilization")]
    object? eventLoopUtilization(object? utilization1, object? utilization2);

    /// <summary>
    /// Node.js signature: <c>perf_hooks.monitorEventLoopDelay([options])</c>.
    /// </summary>
    [NodeModuleMember("monitorEventLoopDelay")]
    object? monitorEventLoopDelay();

    /// <summary>
    /// Node.js signature: <c>perf_hooks.monitorEventLoopDelay([options])</c>.
    /// </summary>
    [NodeModuleMember("monitorEventLoopDelay")]
    object? monitorEventLoopDelay(object? options);

    /// <summary>
    /// Node.js signature: <c>perf_hooks.timerify(fn[, options])</c>.
    /// </summary>
    [NodeModuleMember("timerify")]
    global::System.Delegate timerify(global::System.Delegate fn);

    /// <summary>
    /// Node.js signature: <c>perf_hooks.timerify(fn[, options])</c>.
    /// </summary>
    [NodeModuleMember("timerify")]
    global::System.Delegate timerify(global::System.Delegate fn, object? options);

}
