// <auto-generated />
// Generated from the official Node.js 24.18.1 process API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/process.json
// SHA-256: 94d9d129a68172f7f6d4c3f46f09861c720e7f8498ab8321dfe0cc8886155640

#nullable enable

namespace Jroc.Runtime.Node.Contracts;

/// <summary>
/// Defines the public top-level <c>node:process</c> module contract from Node.js 24.18.1.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCode("generateNodeModuleInterface.js", "sha256:2e1877a88a0be5be6f1ce68d6801f81345518c2272d2b70984df61b7ca02aca0")]
[NodeModuleInterface("process")]
public interface IProcessModule
{
    /// <summary>
    /// Node.js property: <c>`allowedNodeEnvironmentFlags` Type: {Set}</c>.
    /// </summary>
    [NodeModuleMember("allowedNodeEnvironmentFlags")]
    object? allowedNodeEnvironmentFlags { get; }

    /// <summary>
    /// Node.js property: <c>`arch` Type: {string}</c>.
    /// </summary>
    [NodeModuleMember("arch")]
    string arch { get; }

    /// <summary>
    /// Node.js property: <c>`argv` Type: {string\[]}</c>.
    /// </summary>
    [NodeModuleMember("argv")]
    global::JavaScriptRuntime.IJavaScriptArray argv { get; set; }

    /// <summary>
    /// Node.js property: <c>`argv0` Type: {string}</c>.
    /// </summary>
    [NodeModuleMember("argv0")]
    string argv0 { get; }

    /// <summary>
    /// Node.js property: <c>`channel` Type: {Object}</c>.
    /// </summary>
    [NodeModuleMember("channel")]
    object? channel { get; }

    /// <summary>
    /// Node.js property: <c>`config` Type: {Object}</c>.
    /// </summary>
    [NodeModuleMember("config")]
    object? config { get; }

    /// <summary>
    /// Node.js property: <c>`connected` Type: {boolean}</c>.
    /// </summary>
    [NodeModuleMember("connected")]
    bool connected { get; }

    /// <summary>
    /// Node.js property: <c>`debugPort` Type: {number}</c>.
    /// </summary>
    [NodeModuleMember("debugPort")]
    double debugPort { get; set; }

    /// <summary>
    /// Node.js property: <c>`env` Type: {Object}</c>.
    /// </summary>
    [NodeModuleMember("env")]
    object? env { get; set; }

    /// <summary>
    /// Node.js property: <c>`execArgv` Type: {string\[]}</c>.
    /// </summary>
    [NodeModuleMember("execArgv")]
    global::JavaScriptRuntime.IJavaScriptArray execArgv { get; set; }

    /// <summary>
    /// Node.js property: <c>`execPath` Type: {string}</c>.
    /// </summary>
    [NodeModuleMember("execPath")]
    string execPath { get; set; }

    /// <summary>
    /// Node.js property: <c>`exitCode` Type: {integer|string|null|undefined} The exit code. For string type, only integer strings (e.g.,'1') are allowed. **Default:** `undefined`.</c>.
    /// </summary>
    [NodeModuleMember("exitCode")]
    object? exitCode { get; set; }

    /// <summary>
    /// Node.js property: <c>`mainModule` Type: {Object}</c>.
    /// </summary>
    [global::System.Obsolete("Deprecated by Node.js since v14.0.0.")]
    [NodeModuleMember("mainModule")]
    object? mainModule { get; }

    /// <summary>
    /// Node.js property: <c>`noDeprecation` Type: {boolean}</c>.
    /// </summary>
    [NodeModuleMember("noDeprecation")]
    bool noDeprecation { get; set; }

    /// <summary>
    /// Node.js property: <c>`permission` Type: {Object}</c>.
    /// </summary>
    [NodeModuleMember("permission")]
    object? permission { get; }

    /// <summary>
    /// Node.js property: <c>`pid` Type: {integer}</c>.
    /// </summary>
    [NodeModuleMember("pid")]
    double pid { get; }

    /// <summary>
    /// Node.js property: <c>`platform` Type: {string}</c>.
    /// </summary>
    [NodeModuleMember("platform")]
    string platform { get; }

    /// <summary>
    /// Node.js property: <c>`ppid` Type: {integer}</c>.
    /// </summary>
    [NodeModuleMember("ppid")]
    double ppid { get; }

    /// <summary>
    /// Node.js property: <c>`release` Type: {Object}</c>.
    /// </summary>
    [NodeModuleMember("release")]
    object? release { get; }

    /// <summary>
    /// Node.js property: <c>`report` Type: {Object}</c>.
    /// </summary>
    [NodeModuleMember("report")]
    object? report { get; }

    /// <summary>
    /// Node.js property: <c>`sourceMapsEnabled` Type: {boolean}</c>.
    /// </summary>
    [NodeModuleMember("sourceMapsEnabled")]
    bool sourceMapsEnabled { get; }

    /// <summary>
    /// Node.js property: <c>`stderr` Type: {Stream}</c>.
    /// </summary>
    [NodeModuleMember("stderr")]
    object? stderr { get; }

    /// <summary>
    /// Node.js property: <c>`stdin` Type: {Stream}</c>.
    /// </summary>
    [NodeModuleMember("stdin")]
    object? stdin { get; }

    /// <summary>
    /// Node.js property: <c>`stdout` Type: {Stream}</c>.
    /// </summary>
    [NodeModuleMember("stdout")]
    object? stdout { get; }

    /// <summary>
    /// Node.js property: <c>`throwDeprecation` Type: {boolean}</c>.
    /// </summary>
    [NodeModuleMember("throwDeprecation")]
    bool throwDeprecation { get; set; }

    /// <summary>
    /// Node.js property: <c>`title` Type: {string}</c>.
    /// </summary>
    [NodeModuleMember("title")]
    string title { get; set; }

    /// <summary>
    /// Node.js property: <c>`traceDeprecation` Type: {boolean}</c>.
    /// </summary>
    [NodeModuleMember("traceDeprecation")]
    bool traceDeprecation { get; set; }

    /// <summary>
    /// Node.js property: <c>`traceProcessWarnings` {boolean}</c>.
    /// </summary>
    [NodeModuleMember("traceProcessWarnings")]
    bool traceProcessWarnings { get; set; }

    /// <summary>
    /// Node.js property: <c>`version` Type: {string}</c>.
    /// </summary>
    [NodeModuleMember("version")]
    string version { get; }

    /// <summary>
    /// Node.js property: <c>`versions` Type: {Object}</c>.
    /// </summary>
    [NodeModuleMember("versions")]
    object? versions { get; }

    /// <summary>
    /// Gets the object describing features compiled into the current Node.js binary.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/process.html#processfeatures</c>.</remarks>
    [NodeModuleMember("features")]
    object? features { get; }

    /// <summary>
    /// Gets the process finalization registration API.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/process.html#processfinalizationregisterref-callback</c>.</remarks>
    [NodeModuleMember("finalization")]
    object? finalization { get; }

    // Process methods
    /// <summary>
    /// Node.js signature: <c>process.abort()</c>.
    /// </summary>
    [NodeModuleMember("abort")]
    void abort();

    /// <summary>
    /// Node.js signature: <c>process.availableMemory()</c>.
    /// </summary>
    [NodeModuleMember("availableMemory")]
    double availableMemory();

    /// <summary>
    /// Node.js signature: <c>process.chdir(directory)</c>.
    /// </summary>
    [NodeModuleMember("chdir")]
    void chdir(string directory);

    /// <summary>
    /// Node.js signature: <c>process.constrainedMemory()</c>.
    /// </summary>
    [NodeModuleMember("constrainedMemory")]
    double constrainedMemory();

    /// <summary>
    /// Node.js signature: <c>process.cpuUsage([previousValue])</c>.
    /// </summary>
    [NodeModuleMember("cpuUsage")]
    object? cpuUsage();

    /// <summary>
    /// Node.js signature: <c>process.cpuUsage([previousValue])</c>.
    /// </summary>
    [NodeModuleMember("cpuUsage")]
    object? cpuUsage(object? previousValue);

    /// <summary>
    /// Node.js signature: <c>process.cwd()</c>.
    /// </summary>
    [NodeModuleMember("cwd")]
    string cwd();

    /// <summary>
    /// Node.js signature: <c>process.disconnect()</c>.
    /// </summary>
    [NodeModuleMember("disconnect")]
    void disconnect();

    /// <summary>
    /// Node.js signature: <c>process.dlopen(module, filename[, flags])</c>.
    /// </summary>
    [NodeModuleMember("dlopen")]
    void dlopen(object? module, string filename);

    /// <summary>
    /// Node.js signature: <c>process.dlopen(module, filename[, flags])</c>.
    /// </summary>
    [NodeModuleMember("dlopen")]
    void dlopen(object? module, string filename, object? flags);

    /// <summary>
    /// Node.js signature: <c>process.emitWarning(warning[, options])</c>.
    /// </summary>
    [NodeModuleMember("emitWarning")]
    void emitWarning(object? warning);

    /// <summary>
    /// Node.js signature: <c>process.emitWarning(warning[, options])</c>.
    /// </summary>
    [NodeModuleMember("emitWarning")]
    void emitWarning(object? warning, object? options);

    /// <summary>
    /// Node.js signature: <c>process.emitWarning(warning[, type[, code]][, ctor])</c>.
    /// </summary>
    [NodeModuleMember("emitWarning")]
    void emitWarning(object? warning, object? type, object? code);

    /// <summary>
    /// Node.js signature: <c>process.emitWarning(warning[, type[, code]][, ctor])</c>.
    /// </summary>
    [NodeModuleMember("emitWarning")]
    void emitWarning(object? warning, object? type, object? code, object? ctor);

    /// <summary>
    /// Node.js signature: <c>process.execve(file[, args[, env]])</c>.
    /// </summary>
    [NodeModuleMember("execve")]
    void execve(string file);

    /// <summary>
    /// Node.js signature: <c>process.execve(file[, args[, env]])</c>.
    /// </summary>
    [NodeModuleMember("execve")]
    void execve(string file, object? args);

    /// <summary>
    /// Node.js signature: <c>process.execve(file[, args[, env]])</c>.
    /// </summary>
    [NodeModuleMember("execve")]
    void execve(string file, object? args, object? env);

    /// <summary>
    /// Node.js signature: <c>process.exit([code])</c>.
    /// </summary>
    [NodeModuleMember("exit")]
    void exit();

    /// <summary>
    /// Node.js signature: <c>process.exit([code])</c>.
    /// </summary>
    [NodeModuleMember("exit")]
    void exit(object? code);

    /// <summary>
    /// Node.js signature: <c>process.getActiveResourcesInfo()</c>.
    /// </summary>
    [NodeModuleMember("getActiveResourcesInfo")]
    global::JavaScriptRuntime.IJavaScriptArray getActiveResourcesInfo();

    /// <summary>
    /// Node.js signature: <c>process.getBuiltinModule(id)</c>.
    /// </summary>
    [NodeModuleMember("getBuiltinModule")]
    object? getBuiltinModule(string id);

    /// <summary>
    /// Node.js signature: <c>process.getegid()</c>.
    /// </summary>
    [NodeModuleMember("getegid")]
    double getegid();

    /// <summary>
    /// Node.js signature: <c>process.geteuid()</c>.
    /// </summary>
    [NodeModuleMember("geteuid")]
    double geteuid();

    /// <summary>
    /// Node.js signature: <c>process.getgid()</c>.
    /// </summary>
    [NodeModuleMember("getgid")]
    double getgid();

    /// <summary>
    /// Node.js signature: <c>process.getgroups()</c>.
    /// </summary>
    [NodeModuleMember("getgroups")]
    global::JavaScriptRuntime.IJavaScriptArray getgroups();

    /// <summary>
    /// Node.js signature: <c>process.getuid()</c>.
    /// </summary>
    [NodeModuleMember("getuid")]
    double getuid();

    /// <summary>
    /// Node.js signature: <c>process.hasUncaughtExceptionCaptureCallback()</c>.
    /// </summary>
    [NodeModuleMember("hasUncaughtExceptionCaptureCallback")]
    bool hasUncaughtExceptionCaptureCallback();

    /// <summary>
    /// Node.js signature: <c>process.hrtime([time])</c>.
    /// </summary>
    [NodeModuleMember("hrtime")]
    global::JavaScriptRuntime.IJavaScriptArray hrtime();

    /// <summary>
    /// Node.js signature: <c>process.hrtime([time])</c>.
    /// </summary>
    [NodeModuleMember("hrtime")]
    global::JavaScriptRuntime.IJavaScriptArray hrtime(object? time);

    /// <summary>
    /// Node.js signature: <c>process.initgroups(user, extraGroup)</c>.
    /// </summary>
    [NodeModuleMember("initgroups")]
    void initgroups(object? user, object? extraGroup);

    /// <summary>
    /// Node.js signature: <c>process.kill(pid[, signal])</c>.
    /// </summary>
    [NodeModuleMember("kill")]
    bool kill(double pid);

    /// <summary>
    /// Node.js signature: <c>process.kill(pid[, signal])</c>.
    /// </summary>
    [NodeModuleMember("kill")]
    bool kill(double pid, object? signal);

    /// <summary>
    /// Node.js signature: <c>process.loadEnvFile(path)</c>.
    /// </summary>
    [NodeModuleMember("loadEnvFile")]
    void loadEnvFile();

    /// <summary>
    /// Node.js signature: <c>process.loadEnvFile(path)</c>.
    /// </summary>
    [NodeModuleMember("loadEnvFile")]
    void loadEnvFile(object? path);

    /// <summary>
    /// Node.js signature: <c>process.memoryUsage()</c>.
    /// </summary>
    [NodeModuleMember("memoryUsage")]
    object? memoryUsage();

    /// <summary>
    /// Node.js signature: <c>process.nextTick(callback[, ...args])</c>.
    /// </summary>
    [NodeModuleMember("nextTick")]
    void nextTick(global::System.Delegate callback, params object?[] args);

    /// <summary>
    /// Node.js signature: <c>process.ref(maybeRefable)</c>.
    /// </summary>
    [NodeModuleMember("ref")]
    void @ref(object? maybeRefable);

    /// <summary>
    /// Node.js signature: <c>process.resourceUsage()</c>.
    /// </summary>
    [NodeModuleMember("resourceUsage")]
    object? resourceUsage();

    /// <summary>
    /// Node.js signature: <c>process.send(message[, sendHandle[, options]][, callback])</c>.
    /// </summary>
    [NodeModuleMember("send")]
    bool send(object? message);

    /// <summary>
    /// Node.js signature: <c>process.send(message[, sendHandle[, options]][, callback])</c>.
    /// </summary>
    [NodeModuleMember("send")]
    bool send(object? message, object? sendHandle);

    /// <summary>
    /// Node.js signature: <c>process.send(message[, sendHandle[, options]][, callback])</c>.
    /// </summary>
    [NodeModuleMember("send")]
    bool send(object? message, object? sendHandle, object? options);

    /// <summary>
    /// Node.js signature: <c>process.send(message[, sendHandle[, options]][, callback])</c>.
    /// </summary>
    [NodeModuleMember("send")]
    bool send(object? message, object? sendHandle, object? options, object? callback);

    /// <summary>
    /// Node.js signature: <c>process.setegid(id)</c>.
    /// </summary>
    [NodeModuleMember("setegid")]
    void setegid(object? id);

    /// <summary>
    /// Node.js signature: <c>process.seteuid(id)</c>.
    /// </summary>
    [NodeModuleMember("seteuid")]
    void seteuid(object? id);

    /// <summary>
    /// Node.js signature: <c>process.setgid(id)</c>.
    /// </summary>
    [NodeModuleMember("setgid")]
    void setgid(object? id);

    /// <summary>
    /// Node.js signature: <c>process.setgroups(groups)</c>.
    /// </summary>
    [NodeModuleMember("setgroups")]
    void setgroups(global::JavaScriptRuntime.IJavaScriptArray groups);

    /// <summary>
    /// Node.js signature: <c>process.setuid(id)</c>.
    /// </summary>
    [NodeModuleMember("setuid")]
    void setuid(object? id);

    /// <summary>
    /// Node.js signature: <c>process.setSourceMapsEnabled(val)</c>.
    /// </summary>
    [NodeModuleMember("setSourceMapsEnabled")]
    void setSourceMapsEnabled(bool val);

    /// <summary>
    /// Node.js signature: <c>process.setUncaughtExceptionCaptureCallback(fn)</c>.
    /// </summary>
    [NodeModuleMember("setUncaughtExceptionCaptureCallback")]
    void setUncaughtExceptionCaptureCallback(object? fn);

    /// <summary>
    /// Node.js signature: <c>process.threadCpuUsage([previousValue])</c>.
    /// </summary>
    [NodeModuleMember("threadCpuUsage")]
    object? threadCpuUsage();

    /// <summary>
    /// Node.js signature: <c>process.threadCpuUsage([previousValue])</c>.
    /// </summary>
    [NodeModuleMember("threadCpuUsage")]
    object? threadCpuUsage(object? previousValue);

    /// <summary>
    /// Node.js signature: <c>process.umask()</c>.
    /// </summary>
    [NodeModuleMember("umask")]
    double umask();

    /// <summary>
    /// Node.js signature: <c>process.umask(mask)</c>.
    /// </summary>
    [NodeModuleMember("umask")]
    double umask(object? mask);

    /// <summary>
    /// Node.js signature: <c>process.unref(maybeRefable)</c>.
    /// </summary>
    [NodeModuleMember("unref")]
    void unref(object? maybeRefable);

    /// <summary>
    /// Node.js signature: <c>process.uptime()</c>.
    /// </summary>
    [NodeModuleMember("uptime")]
    double uptime();

}
