// <auto-generated />
// Generated from the official Node.js 24.18.1 querystring API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/querystring.json
// SHA-256: d042a799ccc565df8352cd62b3e57f50b609b08291fcaa28a9cb9d3da5641023

#nullable enable

namespace Jroc.Runtime.Node.Contracts;

/// <summary>
/// Defines the public top-level <c>node:querystring</c> module contract from Node.js 24.18.1.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCode("generateNodeModuleInterface.js", "sha256:93229019781b96b99bbb9db54e0ac5ddb7af9b085a482cbaa081b3cf230b4aea")]
[NodeModuleInterface("querystring")]
public interface IQueryStringModule
{
    // node:querystring methods
    /// <summary>
    /// Node.js signature: <c>querystring.decode()</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/querystring.html#querystringdecode</c>.</remarks>
    [NodeModuleMember("decode")]
    object? decode(string str);

    /// <summary>
    /// Node.js signature: <c>querystring.decode()</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/querystring.html#querystringdecode</c>.</remarks>
    [NodeModuleMember("decode")]
    object? decode(string str, string sep);

    /// <summary>
    /// Node.js signature: <c>querystring.decode()</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/querystring.html#querystringdecode</c>.</remarks>
    [NodeModuleMember("decode")]
    object? decode(string str, string sep, string eq);

    /// <summary>
    /// Node.js signature: <c>querystring.decode()</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/querystring.html#querystringdecode</c>.</remarks>
    [NodeModuleMember("decode")]
    object? decode(string str, string sep, string eq, object? options);

    /// <summary>
    /// Node.js signature: <c>querystring.encode()</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/querystring.html#querystringencode</c>.</remarks>
    [NodeModuleMember("encode")]
    string encode(object? obj);

    /// <summary>
    /// Node.js signature: <c>querystring.encode()</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/querystring.html#querystringencode</c>.</remarks>
    [NodeModuleMember("encode")]
    string encode(object? obj, string sep);

    /// <summary>
    /// Node.js signature: <c>querystring.encode()</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/querystring.html#querystringencode</c>.</remarks>
    [NodeModuleMember("encode")]
    string encode(object? obj, string sep, string eq);

    /// <summary>
    /// Node.js signature: <c>querystring.encode()</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/querystring.html#querystringencode</c>.</remarks>
    [NodeModuleMember("encode")]
    string encode(object? obj, string sep, string eq, object? options);

    /// <summary>
    /// Node.js signature: <c>querystring.escape(str)</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/querystring.html#querystringescapestr</c>.</remarks>
    [NodeModuleMember("escape")]
    string escape(string str);

    /// <summary>
    /// Node.js signature: <c>querystring.parse(str[, sep[, eq[, options]]])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/querystring.html#querystringparsestr-sep-eq-options</c>.</remarks>
    [NodeModuleMember("parse")]
    object? parse(string str);

    /// <summary>
    /// Node.js signature: <c>querystring.parse(str[, sep[, eq[, options]]])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/querystring.html#querystringparsestr-sep-eq-options</c>.</remarks>
    [NodeModuleMember("parse")]
    object? parse(string str, string sep);

    /// <summary>
    /// Node.js signature: <c>querystring.parse(str[, sep[, eq[, options]]])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/querystring.html#querystringparsestr-sep-eq-options</c>.</remarks>
    [NodeModuleMember("parse")]
    object? parse(string str, string sep, string eq);

    /// <summary>
    /// Node.js signature: <c>querystring.parse(str[, sep[, eq[, options]]])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/querystring.html#querystringparsestr-sep-eq-options</c>.</remarks>
    [NodeModuleMember("parse")]
    object? parse(string str, string sep, string eq, object? options);

    /// <summary>
    /// Node.js signature: <c>querystring.stringify(obj[, sep[, eq[, options]]])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/querystring.html#querystringstringifyobj-sep-eq-options</c>.</remarks>
    [NodeModuleMember("stringify")]
    string stringify(object? obj);

    /// <summary>
    /// Node.js signature: <c>querystring.stringify(obj[, sep[, eq[, options]]])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/querystring.html#querystringstringifyobj-sep-eq-options</c>.</remarks>
    [NodeModuleMember("stringify")]
    string stringify(object? obj, string sep);

    /// <summary>
    /// Node.js signature: <c>querystring.stringify(obj[, sep[, eq[, options]]])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/querystring.html#querystringstringifyobj-sep-eq-options</c>.</remarks>
    [NodeModuleMember("stringify")]
    string stringify(object? obj, string sep, string eq);

    /// <summary>
    /// Node.js signature: <c>querystring.stringify(obj[, sep[, eq[, options]]])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/querystring.html#querystringstringifyobj-sep-eq-options</c>.</remarks>
    [NodeModuleMember("stringify")]
    string stringify(object? obj, string sep, string eq, object? options);

    /// <summary>
    /// Node.js signature: <c>querystring.unescape(str)</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/querystring.html#querystringunescapestr</c>.</remarks>
    [NodeModuleMember("unescape")]
    string unescape(string str);

}
