// <auto-generated />
// Generated from the official Node.js 24.18.1 stream API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/stream.json
// SHA-256: d60aeb160a21b7ec143de394320e97dc8751777325c698eb1fcc36c82da5e06e

#nullable enable

namespace Jroc.Runtime.Node.Contracts;

/// <summary>
/// Defines the public top-level <c>node:stream/promises</c> module contract from Node.js 24.18.1.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCode("generateNodeModuleInterface.js", "sha256:de7d46c347d581581a76dc391aa1fcd75d184d772e05ee622c88f4c5b6aa96ad")]
[NodeModuleInterface("stream/promises")]
public interface IStreamPromisesModule
{
    // Stream promise methods
    /// <summary>
    /// Node.js signature: <c>stream.finished(stream[, options])</c>.
    /// </summary>
    [NodeModuleMember("finished")]
    global::JavaScriptRuntime.IJavaScriptPromise finished(object? stream);

    /// <summary>
    /// Node.js signature: <c>stream.finished(stream[, options])</c>.
    /// </summary>
    [NodeModuleMember("finished")]
    global::JavaScriptRuntime.IJavaScriptPromise finished(object? stream, object? options);

    /// <summary>
    /// Node.js signatures: <c>stream.pipeline(streams[, options])</c>, <c>stream.pipeline(source[, ...transforms], destination[, options])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/stream.html#streampipelinesource-transforms-destination-options</c>.</remarks>
    [NodeModuleMember("pipeline")]
    global::JavaScriptRuntime.IJavaScriptPromise pipeline(params object?[] args);

}
