// <auto-generated />
// Generated from the official Node.js 24.18.1 stream API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/stream.json
// SHA-256: d60aeb160a21b7ec143de394320e97dc8751777325c698eb1fcc36c82da5e06e

#nullable enable

namespace Jroc.Runtime.Node.Contracts;

/// <summary>
/// Defines the public top-level <c>node:stream</c> module contract from Node.js 24.18.1.
/// </summary>
/// <remarks>
/// Nested option, result, and handle contracts intentionally remain dynamic in this proof of concept.
/// They will be strongly typed by the work tracked in GitHub issue #1660.
/// </remarks>
[global::System.CodeDom.Compiler.GeneratedCode("generateNodeModuleInterface.js", "sha256:6fe985f5ad468d3c30e514e91fe24149b71ecea13c7f0c442a919937f14d07f2")]
[NodeModuleInterface("stream")]
public interface IStreamModule
{
    /// <summary>
    /// Gets the exported Readable constructor.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/stream.html#class-streamreadable</c>.</remarks>
    [NodeModuleMember("Readable")]
    object? Readable { get; }

    /// <summary>
    /// Gets the exported Writable constructor.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/stream.html#class-streamwritable</c>.</remarks>
    [NodeModuleMember("Writable")]
    object? Writable { get; }

    /// <summary>
    /// Gets the exported Duplex constructor.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/stream.html#class-streamduplex</c>.</remarks>
    [NodeModuleMember("Duplex")]
    object? Duplex { get; }

    /// <summary>
    /// Gets the exported Transform constructor.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/stream.html#class-streamtransform</c>.</remarks>
    [NodeModuleMember("Transform")]
    object? Transform { get; }

    /// <summary>
    /// Gets the exported PassThrough constructor.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/stream.html#class-streampassthrough</c>.</remarks>
    [NodeModuleMember("PassThrough")]
    object? PassThrough { get; }

    /// <summary>
    /// Gets the promise-based stream API.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/stream.html#streams-promises-api</c>.</remarks>
    [NodeModuleMember("promises")]
    object? promises { get; }

    // Stream methods
    /// <summary>
    /// Node.js signature: <c>stream.finished(stream[, options], callback)</c>.
    /// </summary>
    [NodeModuleMember("finished")]
    global::System.Delegate finished(object? stream, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>stream.finished(stream[, options], callback)</c>.
    /// </summary>
    [NodeModuleMember("finished")]
    global::System.Delegate finished(object? stream, object? options, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>stream.isErrored(stream)</c>.
    /// </summary>
    [NodeModuleMember("isErrored")]
    bool isErrored(object? stream);

    /// <summary>
    /// Node.js signature: <c>stream.isReadable(stream)</c>.
    /// </summary>
    [NodeModuleMember("isReadable")]
    object? isReadable(object? stream);

    /// <summary>
    /// Node.js signature: <c>stream.isWritable(stream)</c>.
    /// </summary>
    [NodeModuleMember("isWritable")]
    object? isWritable(object? stream);

    /// <summary>
    /// Node.js signature: <c>stream.addAbortSignal(signal, stream)</c>.
    /// </summary>
    [NodeModuleMember("addAbortSignal")]
    object? addAbortSignal(object? signal, object? stream);

    /// <summary>
    /// Node.js signature: <c>stream.getDefaultHighWaterMark(objectMode)</c>.
    /// </summary>
    [NodeModuleMember("getDefaultHighWaterMark")]
    double getDefaultHighWaterMark(bool objectMode);

    /// <summary>
    /// Node.js signature: <c>stream.setDefaultHighWaterMark(objectMode, value)</c>.
    /// </summary>
    [NodeModuleMember("setDefaultHighWaterMark")]
    void setDefaultHighWaterMark(bool objectMode, double value);

    /// <summary>
    /// Node.js signature: <c>stream.duplexPair([options])</c>.
    /// </summary>
    [NodeModuleMember("duplexPair")]
    global::JavaScriptRuntime.IJavaScriptArray duplexPair();

    /// <summary>
    /// Node.js signature: <c>stream.duplexPair([options])</c>.
    /// </summary>
    [NodeModuleMember("duplexPair")]
    global::JavaScriptRuntime.IJavaScriptArray duplexPair(object? options);

    /// <summary>
    /// Node.js signatures: <c>stream.pipeline(source[, ...transforms], destination, callback)</c>, <c>stream.pipeline(streams, callback)</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/stream.html#streampipelinesource-transforms-destination-callback</c>.</remarks>
    [NodeModuleMember("pipeline")]
    object? pipeline(params object?[] args);

    /// <summary>
    /// Node.js signature: <c>stream.compose(...streams)</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/stream.html#streamcomposestreams</c>.</remarks>
    [NodeModuleMember("compose")]
    object? compose(params object?[] streams);

}
