// <auto-generated />
// Generated from the official Node.js 24.18.1 string_decoder API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/string_decoder.json
// SHA-256: 5a9d34a9cf17624c5379f87a90111c8885b2ca2d5e686bdc4c36b7b5a807991b

#nullable enable

namespace Jroc.Runtime.Node.Contracts;

/// <summary>
/// Defines the public top-level <c>node:string_decoder</c> module contract from Node.js 24.18.1.
/// </summary>
/// <remarks>
/// Nested option, result, and handle contracts intentionally remain dynamic in this proof of concept.
/// They will be strongly typed by the work tracked in GitHub issue #1660.
/// </remarks>
[global::System.CodeDom.Compiler.GeneratedCode("generateNodeModuleInterface.js", "sha256:e0d88d11483936ce8b947360e0bac6d198acd445d3e7638f60398a795de2bba7")]
[NodeModuleInterface("string_decoder")]
public interface IStringDecoderModule
{
    /// <summary>
    /// Gets the exported StringDecoder constructor.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/string_decoder.html#class-stringdecoder</c>.</remarks>
    [NodeModuleMember("StringDecoder")]
    object? StringDecoder { get; }

    // String decoder module methods
}
