// <auto-generated />
// Generated from the official Node.js 24.18.1 string_decoder API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/string_decoder.json
// SHA-256: 5a9d34a9cf17624c5379f87a90111c8885b2ca2d5e686bdc4c36b7b5a807991b

#nullable enable

namespace Jroc.Runtime.Node.Contracts;

/// <summary>
/// Defines the public top-level <c>node:string_decoder</c> module contract from Node.js 24.18.1.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCode("generateNodeModuleInterface.js", "sha256:13ea61f00a6a5629ba94c535a3f32f6ddcc06ed57c5bde2aa5bdbf56d257d242")]
[NodeModuleInterface("string_decoder")]
public interface IStringDecoderModule
{
    /// <summary>
    /// Gets the exported StringDecoder constructor.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/string_decoder.html#class-stringdecoder</c>.</remarks>
    [NodeModuleMember("StringDecoder")]
    object? StringDecoder { get; }

    // String decoder module methods
}
