// <auto-generated />
// Generated from the official Node.js 24.18.1 timers API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/timers.json
// SHA-256: afefa0e658b42192562c9ae47445d09be5e686c8575acb28eef9cf1d77d8d8e9

#nullable enable

namespace Jroc.Runtime.Node.Contracts;

/// <summary>
/// Defines the public top-level <c>node:timers/promises</c> module contract from Node.js 24.18.1.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCode("generateNodeModuleInterface.js", "sha256:2e1877a88a0be5be6f1ce68d6801f81345518c2272d2b70984df61b7ca02aca0")]
[NodeModuleInterface("timers/promises")]
public interface ITimersPromisesModule
{
    /// <summary>
    /// Gets the experimental Scheduling API object.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/timers.html#timers-promises-api</c>.</remarks>
    [NodeModuleMember("scheduler")]
    object? scheduler { get; }

    // Promise timer methods
    /// <summary>
    /// Node.js signature: <c>timersPromises.setTimeout([delay[, value[, options]]])</c>.
    /// </summary>
    [NodeModuleMember("setTimeout")]
    global::JavaScriptRuntime.IJavaScriptPromise setTimeout();

    /// <summary>
    /// Node.js signature: <c>timersPromises.setTimeout([delay[, value[, options]]])</c>.
    /// </summary>
    [NodeModuleMember("setTimeout")]
    global::JavaScriptRuntime.IJavaScriptPromise setTimeout(object? delay);

    /// <summary>
    /// Node.js signature: <c>timersPromises.setTimeout([delay[, value[, options]]])</c>.
    /// </summary>
    [NodeModuleMember("setTimeout")]
    global::JavaScriptRuntime.IJavaScriptPromise setTimeout(object? delay, object? value);

    /// <summary>
    /// Node.js signature: <c>timersPromises.setTimeout([delay[, value[, options]]])</c>.
    /// </summary>
    [NodeModuleMember("setTimeout")]
    global::JavaScriptRuntime.IJavaScriptPromise setTimeout(object? delay, object? value, object? options);

    /// <summary>
    /// Node.js signature: <c>timersPromises.setImmediate([value[, options]])</c>.
    /// </summary>
    [NodeModuleMember("setImmediate")]
    global::JavaScriptRuntime.IJavaScriptPromise setImmediate();

    /// <summary>
    /// Node.js signature: <c>timersPromises.setImmediate([value[, options]])</c>.
    /// </summary>
    [NodeModuleMember("setImmediate")]
    global::JavaScriptRuntime.IJavaScriptPromise setImmediate(object? value);

    /// <summary>
    /// Node.js signature: <c>timersPromises.setImmediate([value[, options]])</c>.
    /// </summary>
    [NodeModuleMember("setImmediate")]
    global::JavaScriptRuntime.IJavaScriptPromise setImmediate(object? value, object? options);

    /// <summary>
    /// Node.js signature: <c>timersPromises.setInterval([delay[, value[, options]]])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/timers.html#timerspromisessetintervaldelay-value-options</c>.</remarks>
    [NodeModuleMember("setInterval")]
    global::JavaScriptRuntime.IJavaScriptAsyncIterator setInterval();

    /// <summary>
    /// Node.js signature: <c>timersPromises.setInterval([delay[, value[, options]]])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/timers.html#timerspromisessetintervaldelay-value-options</c>.</remarks>
    [NodeModuleMember("setInterval")]
    global::JavaScriptRuntime.IJavaScriptAsyncIterator setInterval(object? delay);

    /// <summary>
    /// Node.js signature: <c>timersPromises.setInterval([delay[, value[, options]]])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/timers.html#timerspromisessetintervaldelay-value-options</c>.</remarks>
    [NodeModuleMember("setInterval")]
    global::JavaScriptRuntime.IJavaScriptAsyncIterator setInterval(object? delay, object? value);

    /// <summary>
    /// Node.js signature: <c>timersPromises.setInterval([delay[, value[, options]]])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/timers.html#timerspromisessetintervaldelay-value-options</c>.</remarks>
    [NodeModuleMember("setInterval")]
    global::JavaScriptRuntime.IJavaScriptAsyncIterator setInterval(object? delay, object? value, object? options);

}
