// <auto-generated />
// Generated from the official Node.js 24.18.1 timers API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/timers.json
// SHA-256: afefa0e658b42192562c9ae47445d09be5e686c8575acb28eef9cf1d77d8d8e9

#nullable enable

namespace Jroc.Runtime.Node.Contracts;

/// <summary>
/// Defines the public top-level <c>node:timers</c> module contract from Node.js 24.18.1.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCode("generateNodeModuleInterface.js", "sha256:2e1877a88a0be5be6f1ce68d6801f81345518c2272d2b70984df61b7ca02aca0")]
[NodeModuleInterface("timers")]
public interface ITimersModule
{
    // Scheduling timers
    /// <summary>
    /// Node.js signature: <c>setImmediate(callback[, ...args])</c>.
    /// </summary>
    [NodeModuleMember("setImmediate")]
    object? setImmediate(global::System.Delegate callback, params object?[] args);

    /// <summary>
    /// Node.js signature: <c>setInterval(callback[, delay[, ...args]])</c>.
    /// </summary>
    [NodeModuleMember("setInterval")]
    object? setInterval(global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>setInterval(callback[, delay[, ...args]])</c>.
    /// </summary>
    [NodeModuleMember("setInterval")]
    object? setInterval(global::System.Delegate callback, object? delay, params object?[] args);

    /// <summary>
    /// Node.js signature: <c>setTimeout(callback[, delay[, ...args]])</c>.
    /// </summary>
    [NodeModuleMember("setTimeout")]
    object? setTimeout(global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>setTimeout(callback[, delay[, ...args]])</c>.
    /// </summary>
    [NodeModuleMember("setTimeout")]
    object? setTimeout(global::System.Delegate callback, object? delay, params object?[] args);

    // Cancelling timers
    /// <summary>
    /// Node.js signature: <c>clearImmediate(immediate)</c>.
    /// </summary>
    [NodeModuleMember("clearImmediate")]
    void clearImmediate(object? immediate);

    /// <summary>
    /// Node.js signature: <c>clearInterval(timeout)</c>.
    /// </summary>
    [NodeModuleMember("clearInterval")]
    void clearInterval(object? timeout);

    /// <summary>
    /// Node.js signature: <c>clearTimeout(timeout)</c>.
    /// </summary>
    [NodeModuleMember("clearTimeout")]
    void clearTimeout(object? timeout);

}
