// <auto-generated />
// Generated from the official Node.js 24.18.1 tls API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/tls.json
// SHA-256: 3f8071ce06e3bd3a699389237241cde54458b5fe92edb9f868c036c3c408ac8f

#nullable enable

namespace Jroc.Runtime.Node.Contracts;

/// <summary>
/// Defines the public top-level <c>node:tls</c> module contract from Node.js 24.18.1.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCode("generateNodeModuleInterface.js", "sha256:13ea61f00a6a5629ba94c535a3f32f6ddcc06ed57c5bde2aa5bdbf56d257d242")]
[NodeModuleInterface("tls")]
public interface ITlsModule
{
    /// <summary>
    /// Gets the exported <c>tls.rootCertificates</c> member.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/tls.html#tlsrootcertificates</c>.</remarks>
    [NodeModuleMember("rootCertificates")]
    global::JavaScriptRuntime.IJavaScriptArray rootCertificates { get; }

    /// <summary>
    /// Gets the exported <c>tls.DEFAULT_ECDH_CURVE</c> member.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/tls.html#tlsdefault_ecdh_curve</c>.</remarks>
    [NodeModuleMember("DEFAULT_ECDH_CURVE")]
    string DEFAULT_ECDH_CURVE { get; set; }

    /// <summary>
    /// Gets the exported <c>tls.DEFAULT_MAX_VERSION</c> member.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/tls.html#tlsdefault_max_version</c>.</remarks>
    [NodeModuleMember("DEFAULT_MAX_VERSION")]
    string DEFAULT_MAX_VERSION { get; set; }

    /// <summary>
    /// Gets the exported <c>tls.DEFAULT_MIN_VERSION</c> member.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/tls.html#tlsdefault_min_version</c>.</remarks>
    [NodeModuleMember("DEFAULT_MIN_VERSION")]
    string DEFAULT_MIN_VERSION { get; set; }

    /// <summary>
    /// Gets the exported <c>tls.DEFAULT_CIPHERS</c> member.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/tls.html#tlsdefault_ciphers</c>.</remarks>
    [NodeModuleMember("DEFAULT_CIPHERS")]
    string DEFAULT_CIPHERS { get; set; }

    /// <summary>
    /// Gets the exported <c>tls.TLSSocket</c> member.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/tls.html#class-tlstlssocket</c>.</remarks>
    [NodeModuleMember("TLSSocket")]
    object? TLSSocket { get; }

    /// <summary>
    /// Gets the exported <c>tls.Server</c> member.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/tls.html#class-tlsserver</c>.</remarks>
    [NodeModuleMember("Server")]
    object? Server { get; }

    // node:tls methods
    /// <summary>
    /// Node.js signature: <c>tls.checkServerIdentity(hostname, cert)</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/tls.html#tlscheckserveridentityhostname-cert</c>.</remarks>
    [NodeModuleMember("checkServerIdentity")]
    object? checkServerIdentity(string hostname, object? cert);

    /// <summary>
    /// Node.js signatures: <c>tls.connect(options[, callback])</c>, <c>tls.connect(path[, options][, callback])</c>, <c>tls.connect(port[, host][, options][, callback])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/tls.html#tlsconnect</c>.</remarks>
    [NodeModuleMember("connect")]
    object? connect(object? options);

    /// <summary>
    /// Node.js signatures: <c>tls.connect(options[, callback])</c>, <c>tls.connect(path[, options][, callback])</c>, <c>tls.connect(port[, host][, options][, callback])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/tls.html#tlsconnect</c>.</remarks>
    [NodeModuleMember("connect")]
    object? connect(object? options, global::System.Delegate callback);

    /// <summary>
    /// Node.js signatures: <c>tls.connect(options[, callback])</c>, <c>tls.connect(path[, options][, callback])</c>, <c>tls.connect(port[, host][, options][, callback])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/tls.html#tlsconnect</c>.</remarks>
    [NodeModuleMember("connect")]
    object? connect(string path);

    /// <summary>
    /// Node.js signatures: <c>tls.connect(options[, callback])</c>, <c>tls.connect(path[, options][, callback])</c>, <c>tls.connect(port[, host][, options][, callback])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/tls.html#tlsconnect</c>.</remarks>
    [NodeModuleMember("connect")]
    object? connect(string path, object? options);

    /// <summary>
    /// Node.js signatures: <c>tls.connect(options[, callback])</c>, <c>tls.connect(path[, options][, callback])</c>, <c>tls.connect(port[, host][, options][, callback])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/tls.html#tlsconnect</c>.</remarks>
    [NodeModuleMember("connect")]
    object? connect(string path, global::System.Delegate callback);

    /// <summary>
    /// Node.js signatures: <c>tls.connect(options[, callback])</c>, <c>tls.connect(path[, options][, callback])</c>, <c>tls.connect(port[, host][, options][, callback])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/tls.html#tlsconnect</c>.</remarks>
    [NodeModuleMember("connect")]
    object? connect(string path, object? options, global::System.Delegate callback);

    /// <summary>
    /// Node.js signatures: <c>tls.connect(options[, callback])</c>, <c>tls.connect(path[, options][, callback])</c>, <c>tls.connect(port[, host][, options][, callback])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/tls.html#tlsconnect</c>.</remarks>
    [NodeModuleMember("connect")]
    object? connect(double port);

    /// <summary>
    /// Node.js signatures: <c>tls.connect(options[, callback])</c>, <c>tls.connect(path[, options][, callback])</c>, <c>tls.connect(port[, host][, options][, callback])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/tls.html#tlsconnect</c>.</remarks>
    [NodeModuleMember("connect")]
    object? connect(double port, string host);

    /// <summary>
    /// Node.js signatures: <c>tls.connect(options[, callback])</c>, <c>tls.connect(path[, options][, callback])</c>, <c>tls.connect(port[, host][, options][, callback])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/tls.html#tlsconnect</c>.</remarks>
    [NodeModuleMember("connect")]
    object? connect(double port, object? options);

    /// <summary>
    /// Node.js signatures: <c>tls.connect(options[, callback])</c>, <c>tls.connect(path[, options][, callback])</c>, <c>tls.connect(port[, host][, options][, callback])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/tls.html#tlsconnect</c>.</remarks>
    [NodeModuleMember("connect")]
    object? connect(double port, global::System.Delegate callback);

    /// <summary>
    /// Node.js signatures: <c>tls.connect(options[, callback])</c>, <c>tls.connect(path[, options][, callback])</c>, <c>tls.connect(port[, host][, options][, callback])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/tls.html#tlsconnect</c>.</remarks>
    [NodeModuleMember("connect")]
    object? connect(double port, string host, object? options);

    /// <summary>
    /// Node.js signatures: <c>tls.connect(options[, callback])</c>, <c>tls.connect(path[, options][, callback])</c>, <c>tls.connect(port[, host][, options][, callback])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/tls.html#tlsconnect</c>.</remarks>
    [NodeModuleMember("connect")]
    object? connect(double port, string host, global::System.Delegate callback);

    /// <summary>
    /// Node.js signatures: <c>tls.connect(options[, callback])</c>, <c>tls.connect(path[, options][, callback])</c>, <c>tls.connect(port[, host][, options][, callback])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/tls.html#tlsconnect</c>.</remarks>
    [NodeModuleMember("connect")]
    object? connect(double port, object? options, global::System.Delegate callback);

    /// <summary>
    /// Node.js signatures: <c>tls.connect(options[, callback])</c>, <c>tls.connect(path[, options][, callback])</c>, <c>tls.connect(port[, host][, options][, callback])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/tls.html#tlsconnect</c>.</remarks>
    [NodeModuleMember("connect")]
    object? connect(double port, string host, object? options, global::System.Delegate callback);

    /// <summary>
    /// Node.js signature: <c>tls.createSecureContext([options])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/tls.html#tlscreatesecurecontextoptions</c>.</remarks>
    [NodeModuleMember("createSecureContext")]
    object? createSecureContext();

    /// <summary>
    /// Node.js signature: <c>tls.createSecureContext([options])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/tls.html#tlscreatesecurecontextoptions</c>.</remarks>
    [NodeModuleMember("createSecureContext")]
    object? createSecureContext(object? options);

    /// <summary>
    /// Node.js signature: <c>tls.createServer([options][, secureConnectionListener])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/tls.html#tlscreateserveroptions-secureconnectionlistener</c>.</remarks>
    [NodeModuleMember("createServer")]
    object? createServer();

    /// <summary>
    /// Node.js signature: <c>tls.createServer([options][, secureConnectionListener])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/tls.html#tlscreateserveroptions-secureconnectionlistener</c>.</remarks>
    [NodeModuleMember("createServer")]
    object? createServer(object? options);

    /// <summary>
    /// Node.js signature: <c>tls.createServer([options][, secureConnectionListener])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/tls.html#tlscreateserveroptions-secureconnectionlistener</c>.</remarks>
    [NodeModuleMember("createServer")]
    object? createServer(global::System.Delegate secureConnectionListener);

    /// <summary>
    /// Node.js signature: <c>tls.createServer([options][, secureConnectionListener])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/tls.html#tlscreateserveroptions-secureconnectionlistener</c>.</remarks>
    [NodeModuleMember("createServer")]
    object? createServer(object? options, global::System.Delegate secureConnectionListener);

    /// <summary>
    /// Node.js signature: <c>tls.setDefaultCACertificates(certs)</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/tls.html#tlssetdefaultcacertificatescerts</c>.</remarks>
    [NodeModuleMember("setDefaultCACertificates")]
    void setDefaultCACertificates(global::JavaScriptRuntime.IJavaScriptArray certs);

    /// <summary>
    /// Node.js signature: <c>tls.getCACertificates([type])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/tls.html#tlsgetcacertificatestype</c>.</remarks>
    [NodeModuleMember("getCACertificates")]
    global::JavaScriptRuntime.IJavaScriptArray getCACertificates();

    /// <summary>
    /// Node.js signature: <c>tls.getCACertificates([type])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/tls.html#tlsgetcacertificatestype</c>.</remarks>
    [NodeModuleMember("getCACertificates")]
    global::JavaScriptRuntime.IJavaScriptArray getCACertificates(string type);

    /// <summary>
    /// Node.js signature: <c>tls.getCiphers()</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/tls.html#tlsgetciphers</c>.</remarks>
    [NodeModuleMember("getCiphers")]
    global::JavaScriptRuntime.IJavaScriptArray getCiphers();

}
