// <auto-generated />
// Generated from the official Node.js 24.18.1 util API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/util.json
// SHA-256: c5b022671190286c09675cae44732369d3ad0b25a4dd040e158dcc101ff26183

#nullable enable

namespace Jroc.Runtime.Node.Contracts;

/// <summary>
/// Defines the public top-level <c>node:util</c> module contract from Node.js 24.18.1.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCode("generateNodeModuleInterface.js", "sha256:93229019781b96b99bbb9db54e0ac5ddb7af9b085a482cbaa081b3cf230b4aea")]
[NodeModuleInterface("util")]
public interface IUtilModule
{
    /// <summary>
    /// Gets the type predicate API also exported by node:util/types.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/util.html#utiltypes</c>.</remarks>
    [NodeModuleMember("types")]
    object? types { get; }

    /// <summary>
    /// Gets the exported MIMEType constructor.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/util.html#class-utilmimetype</c>.</remarks>
    [NodeModuleMember("MIMEType")]
    object? MIMEType { get; }

    /// <summary>
    /// Gets the exported MIMEParams constructor.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/util.html#class-utilmimeparams</c>.</remarks>
    [NodeModuleMember("MIMEParams")]
    object? MIMEParams { get; }

    /// <summary>
    /// Gets the exported TextDecoder constructor.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/util.html#class-utiltextdecoder</c>.</remarks>
    [NodeModuleMember("TextDecoder")]
    object? TextDecoder { get; }

    /// <summary>
    /// Gets the exported TextEncoder constructor.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/util.html#class-utiltextencoder</c>.</remarks>
    [NodeModuleMember("TextEncoder")]
    object? TextEncoder { get; }

    // Utility methods
    /// <summary>
    /// Node.js signature: <c>util.callbackify(original)</c>.
    /// </summary>
    [NodeModuleMember("callbackify")]
    global::System.Delegate callbackify(global::System.Delegate original);

    /// <summary>
    /// Node.js signature: <c>util.convertProcessSignalToExitCode(signal)</c>.
    /// </summary>
    [NodeModuleMember("convertProcessSignalToExitCode")]
    double convertProcessSignalToExitCode(string signal);

    /// <summary>
    /// Node.js signature: <c>util.debuglog(section[, callback])</c>.
    /// </summary>
    [NodeModuleMember("debuglog")]
    global::System.Delegate debuglog(string section);

    /// <summary>
    /// Node.js signature: <c>util.debuglog(section[, callback])</c>.
    /// </summary>
    [NodeModuleMember("debuglog")]
    global::System.Delegate debuglog(string section, object? callback);

    /// <summary>
    /// Node.js signature: <c>util.deprecate(fn, msg[, code[, options]])</c>.
    /// </summary>
    [NodeModuleMember("deprecate")]
    global::System.Delegate deprecate(global::System.Delegate fn, string msg);

    /// <summary>
    /// Node.js signature: <c>util.deprecate(fn, msg[, code[, options]])</c>.
    /// </summary>
    [NodeModuleMember("deprecate")]
    global::System.Delegate deprecate(global::System.Delegate fn, string msg, object? code);

    /// <summary>
    /// Node.js signature: <c>util.deprecate(fn, msg[, code[, options]])</c>.
    /// </summary>
    [NodeModuleMember("deprecate")]
    global::System.Delegate deprecate(global::System.Delegate fn, string msg, object? code, object? options);

    /// <summary>
    /// Node.js signature: <c>util.diff(actual, expected)</c>.
    /// </summary>
    [NodeModuleMember("diff")]
    global::JavaScriptRuntime.IJavaScriptArray diff(object? actual, object? expected);

    /// <summary>
    /// Node.js signature: <c>util.getCallSites([frameCount][, options])</c>.
    /// </summary>
    [NodeModuleMember("getCallSites")]
    global::JavaScriptRuntime.IJavaScriptArray getCallSites();

    /// <summary>
    /// Node.js signature: <c>util.getCallSites([frameCount][, options])</c>.
    /// </summary>
    [NodeModuleMember("getCallSites")]
    global::JavaScriptRuntime.IJavaScriptArray getCallSites(object? options);

    /// <summary>
    /// Node.js signature: <c>util.getCallSites([frameCount][, options])</c>.
    /// </summary>
    [NodeModuleMember("getCallSites")]
    global::JavaScriptRuntime.IJavaScriptArray getCallSites(object? frameCount, object? options);

    /// <summary>
    /// Node.js signature: <c>util.getSystemErrorName(err)</c>.
    /// </summary>
    [NodeModuleMember("getSystemErrorName")]
    string getSystemErrorName(double err);

    /// <summary>
    /// Node.js signature: <c>util.getSystemErrorMap()</c>.
    /// </summary>
    [NodeModuleMember("getSystemErrorMap")]
    object? getSystemErrorMap();

    /// <summary>
    /// Node.js signature: <c>util.getSystemErrorMessage(err)</c>.
    /// </summary>
    [NodeModuleMember("getSystemErrorMessage")]
    string getSystemErrorMessage(double err);

    /// <summary>
    /// Node.js signature: <c>util.setTraceSigInt(enable)</c>.
    /// </summary>
    [NodeModuleMember("setTraceSigInt")]
    void setTraceSigInt(bool enable);

    /// <summary>
    /// Node.js signature: <c>util.inherits(constructor, superConstructor)</c>.
    /// </summary>
    [NodeModuleMember("inherits")]
    void inherits(global::System.Delegate constructor, global::System.Delegate superConstructor);

    /// <summary>
    /// Node.js signature: <c>util.parseArgs([config])</c>.
    /// </summary>
    [NodeModuleMember("parseArgs")]
    object? parseArgs();

    /// <summary>
    /// Node.js signature: <c>util.parseArgs([config])</c>.
    /// </summary>
    [NodeModuleMember("parseArgs")]
    object? parseArgs(object? config);

    /// <summary>
    /// Node.js signature: <c>util.parseEnv(content)</c>.
    /// </summary>
    [NodeModuleMember("parseEnv")]
    object? parseEnv(string content);

    /// <summary>
    /// Node.js signature: <c>util.promisify(original)</c>.
    /// </summary>
    [NodeModuleMember("promisify")]
    global::System.Delegate promisify(global::System.Delegate original);

    /// <summary>
    /// Node.js signature: <c>util.stripVTControlCharacters(str)</c>.
    /// </summary>
    [NodeModuleMember("stripVTControlCharacters")]
    string stripVTControlCharacters(string str);

    /// <summary>
    /// Node.js signature: <c>util.styleText(format, text[, options])</c>.
    /// </summary>
    [NodeModuleMember("styleText")]
    string styleText(object? format, string text);

    /// <summary>
    /// Node.js signature: <c>util.styleText(format, text[, options])</c>.
    /// </summary>
    [NodeModuleMember("styleText")]
    string styleText(object? format, string text, object? options);

    /// <summary>
    /// Node.js signature: <c>util.toUSVString(string)</c>.
    /// </summary>
    [NodeModuleMember("toUSVString")]
    string toUSVString(string @string);

    /// <summary>
    /// Node.js signature: <c>util.transferableAbortController()</c>.
    /// </summary>
    [NodeModuleMember("transferableAbortController")]
    object? transferableAbortController();

    /// <summary>
    /// Node.js signature: <c>util.transferableAbortSignal(signal)</c>.
    /// </summary>
    [NodeModuleMember("transferableAbortSignal")]
    object? transferableAbortSignal(object? signal);

    /// <summary>
    /// Node.js signature: <c>util.aborted(signal, resource)</c>.
    /// </summary>
    [NodeModuleMember("aborted")]
    global::JavaScriptRuntime.IJavaScriptPromise aborted(object? signal, object? resource);

    /// <summary>
    /// Node.js signature: <c>util.debug(section)</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/util.html#utildebugsection</c>.</remarks>
    [global::System.Obsolete("Deprecated by Node.js since v14.9.0.")]
    [NodeModuleMember("debug")]
    global::System.Delegate debug(string section);

    /// <summary>
    /// Node.js signature: <c>util.format(format[, ...args])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/util.html#utilformatformat-args</c>.</remarks>
    [NodeModuleMember("format")]
    string format(string format, params object?[] args);

    /// <summary>
    /// Node.js signature: <c>util.formatWithOptions(inspectOptions, format[, ...args])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/util.html#utilformatwithoptionsinspectoptions-format-args</c>.</remarks>
    [NodeModuleMember("formatWithOptions")]
    string formatWithOptions(object? inspectOptions, string format, params object?[] args);

    /// <summary>
    /// Node.js signatures: <c>util.inspect(object[, options])</c>, <c>util.inspect(object[, showHidden[, depth[, colors]]])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/util.html#utilinspectobject-options</c>.</remarks>
    [NodeModuleMember("inspect")]
    string inspect(object? value);

    /// <summary>
    /// Node.js signatures: <c>util.inspect(object[, options])</c>, <c>util.inspect(object[, showHidden[, depth[, colors]]])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/util.html#utilinspectobject-options</c>.</remarks>
    [NodeModuleMember("inspect")]
    string inspect(object? value, object? optionsOrShowHidden);

    /// <summary>
    /// Node.js signature: <c>util.inspect(object[, showHidden[, depth[, colors]]])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/util.html#utilinspectobject-showhidden-depth-colors</c>.</remarks>
    [NodeModuleMember("inspect")]
    string inspect(object? value, object? showHidden, object? depth);

    /// <summary>
    /// Node.js signature: <c>util.inspect(object[, showHidden[, depth[, colors]]])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/util.html#utilinspectobject-showhidden-depth-colors</c>.</remarks>
    [NodeModuleMember("inspect")]
    string inspect(object? value, object? showHidden, object? depth, object? colors);

    /// <summary>
    /// Node.js signature: <c>util.isDeepStrictEqual(val1, val2[, options])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/util.html#utilisdeepstrictequalval1-val2-options</c>.</remarks>
    [NodeModuleMember("isDeepStrictEqual")]
    bool isDeepStrictEqual(object? val1, object? val2);

    /// <summary>
    /// Node.js signature: <c>util.isDeepStrictEqual(val1, val2[, options])</c>.
    /// </summary>
    /// <remarks>Source: <c>https://nodejs.org/docs/v24.18.1/api/util.html#utilisdeepstrictequalval1-val2-options</c>.</remarks>
    [NodeModuleMember("isDeepStrictEqual")]
    bool isDeepStrictEqual(object? val1, object? val2, object? options);

    // Deprecated utility methods
    /// <summary>
    /// Node.js signature: <c>util._extend(target, source)</c>.
    /// </summary>
    [global::System.Obsolete("Deprecated by Node.js since v6.0.0.")]
    [NodeModuleMember("_extend")]
    object? _extend(object? target, object? source);

    /// <summary>
    /// Node.js signature: <c>util.isArray(object)</c>.
    /// </summary>
    [global::System.Obsolete("Deprecated by Node.js since v4.0.0.")]
    [NodeModuleMember("isArray")]
    bool isArray(object? @object);

}
