// <auto-generated />
// Generated from the official Node.js 24.18.1 util API documentation.
// Source: https://nodejs.org/docs/v24.18.1/api/util.json
// SHA-256: c5b022671190286c09675cae44732369d3ad0b25a4dd040e158dcc101ff26183

#nullable enable

namespace Jroc.Runtime.Node.Contracts;

/// <summary>
/// Defines the public top-level <c>node:util/types</c> module contract from Node.js 24.18.1.
/// </summary>
/// <remarks>
/// Nested option, result, and handle contracts intentionally remain dynamic in this proof of concept.
/// They will be strongly typed by the work tracked in GitHub issue #1660.
/// </remarks>
[global::System.CodeDom.Compiler.GeneratedCode("generateNodeModuleInterface.js", "sha256:be6e78d5530a6d86fe34cd3cb26bca862717703f0617ff439ff5d5caa18b8c25")]
[NodeModuleInterface("util/types")]
public interface IUtilTypesModule
{
    // Type predicates
    /// <summary>
    /// Node.js signature: <c>util.types.isAnyArrayBuffer(value)</c>.
    /// </summary>
    [NodeModuleMember("isAnyArrayBuffer")]
    bool isAnyArrayBuffer(object? value);

    /// <summary>
    /// Node.js signature: <c>util.types.isArrayBufferView(value)</c>.
    /// </summary>
    [NodeModuleMember("isArrayBufferView")]
    bool isArrayBufferView(object? value);

    /// <summary>
    /// Node.js signature: <c>util.types.isArgumentsObject(value)</c>.
    /// </summary>
    [NodeModuleMember("isArgumentsObject")]
    bool isArgumentsObject(object? value);

    /// <summary>
    /// Node.js signature: <c>util.types.isArrayBuffer(value)</c>.
    /// </summary>
    [NodeModuleMember("isArrayBuffer")]
    bool isArrayBuffer(object? value);

    /// <summary>
    /// Node.js signature: <c>util.types.isAsyncFunction(value)</c>.
    /// </summary>
    [NodeModuleMember("isAsyncFunction")]
    bool isAsyncFunction(object? value);

    /// <summary>
    /// Node.js signature: <c>util.types.isBigInt64Array(value)</c>.
    /// </summary>
    [NodeModuleMember("isBigInt64Array")]
    bool isBigInt64Array(object? value);

    /// <summary>
    /// Node.js signature: <c>util.types.isBigIntObject(value)</c>.
    /// </summary>
    [NodeModuleMember("isBigIntObject")]
    bool isBigIntObject(object? value);

    /// <summary>
    /// Node.js signature: <c>util.types.isBigUint64Array(value)</c>.
    /// </summary>
    [NodeModuleMember("isBigUint64Array")]
    bool isBigUint64Array(object? value);

    /// <summary>
    /// Node.js signature: <c>util.types.isBooleanObject(value)</c>.
    /// </summary>
    [NodeModuleMember("isBooleanObject")]
    bool isBooleanObject(object? value);

    /// <summary>
    /// Node.js signature: <c>util.types.isBoxedPrimitive(value)</c>.
    /// </summary>
    [NodeModuleMember("isBoxedPrimitive")]
    bool isBoxedPrimitive(object? value);

    /// <summary>
    /// Node.js signature: <c>util.types.isCryptoKey(value)</c>.
    /// </summary>
    [NodeModuleMember("isCryptoKey")]
    bool isCryptoKey(object? value);

    /// <summary>
    /// Node.js signature: <c>util.types.isDataView(value)</c>.
    /// </summary>
    [NodeModuleMember("isDataView")]
    bool isDataView(object? value);

    /// <summary>
    /// Node.js signature: <c>util.types.isDate(value)</c>.
    /// </summary>
    [NodeModuleMember("isDate")]
    bool isDate(object? value);

    /// <summary>
    /// Node.js signature: <c>util.types.isExternal(value)</c>.
    /// </summary>
    [NodeModuleMember("isExternal")]
    bool isExternal(object? value);

    /// <summary>
    /// Node.js signature: <c>util.types.isFloat16Array(value)</c>.
    /// </summary>
    [NodeModuleMember("isFloat16Array")]
    bool isFloat16Array(object? value);

    /// <summary>
    /// Node.js signature: <c>util.types.isFloat32Array(value)</c>.
    /// </summary>
    [NodeModuleMember("isFloat32Array")]
    bool isFloat32Array(object? value);

    /// <summary>
    /// Node.js signature: <c>util.types.isFloat64Array(value)</c>.
    /// </summary>
    [NodeModuleMember("isFloat64Array")]
    bool isFloat64Array(object? value);

    /// <summary>
    /// Node.js signature: <c>util.types.isGeneratorFunction(value)</c>.
    /// </summary>
    [NodeModuleMember("isGeneratorFunction")]
    bool isGeneratorFunction(object? value);

    /// <summary>
    /// Node.js signature: <c>util.types.isGeneratorObject(value)</c>.
    /// </summary>
    [NodeModuleMember("isGeneratorObject")]
    bool isGeneratorObject(object? value);

    /// <summary>
    /// Node.js signature: <c>util.types.isInt8Array(value)</c>.
    /// </summary>
    [NodeModuleMember("isInt8Array")]
    bool isInt8Array(object? value);

    /// <summary>
    /// Node.js signature: <c>util.types.isInt16Array(value)</c>.
    /// </summary>
    [NodeModuleMember("isInt16Array")]
    bool isInt16Array(object? value);

    /// <summary>
    /// Node.js signature: <c>util.types.isInt32Array(value)</c>.
    /// </summary>
    [NodeModuleMember("isInt32Array")]
    bool isInt32Array(object? value);

    /// <summary>
    /// Node.js signature: <c>util.types.isKeyObject(value)</c>.
    /// </summary>
    [NodeModuleMember("isKeyObject")]
    bool isKeyObject(object? value);

    /// <summary>
    /// Node.js signature: <c>util.types.isMap(value)</c>.
    /// </summary>
    [NodeModuleMember("isMap")]
    bool isMap(object? value);

    /// <summary>
    /// Node.js signature: <c>util.types.isMapIterator(value)</c>.
    /// </summary>
    [NodeModuleMember("isMapIterator")]
    bool isMapIterator(object? value);

    /// <summary>
    /// Node.js signature: <c>util.types.isModuleNamespaceObject(value)</c>.
    /// </summary>
    [NodeModuleMember("isModuleNamespaceObject")]
    bool isModuleNamespaceObject(object? value);

    /// <summary>
    /// Node.js signature: <c>util.types.isNativeError(value)</c>.
    /// </summary>
    [global::System.Obsolete("Deprecated by Node.js since v24.2.0.")]
    [NodeModuleMember("isNativeError")]
    bool isNativeError(object? value);

    /// <summary>
    /// Node.js signature: <c>util.types.isNumberObject(value)</c>.
    /// </summary>
    [NodeModuleMember("isNumberObject")]
    bool isNumberObject(object? value);

    /// <summary>
    /// Node.js signature: <c>util.types.isPromise(value)</c>.
    /// </summary>
    [NodeModuleMember("isPromise")]
    bool isPromise(object? value);

    /// <summary>
    /// Node.js signature: <c>util.types.isProxy(value)</c>.
    /// </summary>
    [NodeModuleMember("isProxy")]
    bool isProxy(object? value);

    /// <summary>
    /// Node.js signature: <c>util.types.isRegExp(value)</c>.
    /// </summary>
    [NodeModuleMember("isRegExp")]
    bool isRegExp(object? value);

    /// <summary>
    /// Node.js signature: <c>util.types.isSet(value)</c>.
    /// </summary>
    [NodeModuleMember("isSet")]
    bool isSet(object? value);

    /// <summary>
    /// Node.js signature: <c>util.types.isSetIterator(value)</c>.
    /// </summary>
    [NodeModuleMember("isSetIterator")]
    bool isSetIterator(object? value);

    /// <summary>
    /// Node.js signature: <c>util.types.isSharedArrayBuffer(value)</c>.
    /// </summary>
    [NodeModuleMember("isSharedArrayBuffer")]
    bool isSharedArrayBuffer(object? value);

    /// <summary>
    /// Node.js signature: <c>util.types.isStringObject(value)</c>.
    /// </summary>
    [NodeModuleMember("isStringObject")]
    bool isStringObject(object? value);

    /// <summary>
    /// Node.js signature: <c>util.types.isSymbolObject(value)</c>.
    /// </summary>
    [NodeModuleMember("isSymbolObject")]
    bool isSymbolObject(object? value);

    /// <summary>
    /// Node.js signature: <c>util.types.isTypedArray(value)</c>.
    /// </summary>
    [NodeModuleMember("isTypedArray")]
    bool isTypedArray(object? value);

    /// <summary>
    /// Node.js signature: <c>util.types.isUint8Array(value)</c>.
    /// </summary>
    [NodeModuleMember("isUint8Array")]
    bool isUint8Array(object? value);

    /// <summary>
    /// Node.js signature: <c>util.types.isUint8ClampedArray(value)</c>.
    /// </summary>
    [NodeModuleMember("isUint8ClampedArray")]
    bool isUint8ClampedArray(object? value);

    /// <summary>
    /// Node.js signature: <c>util.types.isUint16Array(value)</c>.
    /// </summary>
    [NodeModuleMember("isUint16Array")]
    bool isUint16Array(object? value);

    /// <summary>
    /// Node.js signature: <c>util.types.isUint32Array(value)</c>.
    /// </summary>
    [NodeModuleMember("isUint32Array")]
    bool isUint32Array(object? value);

    /// <summary>
    /// Node.js signature: <c>util.types.isWeakMap(value)</c>.
    /// </summary>
    [NodeModuleMember("isWeakMap")]
    bool isWeakMap(object? value);

    /// <summary>
    /// Node.js signature: <c>util.types.isWeakSet(value)</c>.
    /// </summary>
    [NodeModuleMember("isWeakSet")]
    bool isWeakSet(object? value);

}
