namespace Jroc.Test262.Tests.built_ins.String.prototype.split;

public partial class ExecutionTests
{
    [Fact(DisplayName = "arguments-are-new-reg-exp-and-undefined-and-instance-is-string-hello.js")]
    public Task arguments_are_new_reg_exp_and_undefined_and_instance_is_string_hello() => ExecutionTestFromFile("arguments-are-new-reg-exp-and-undefined-and-instance-is-string-hello");
    [Fact(DisplayName = "arguments-are-new-reg-exp-and-void-0-and-instance-is-string-hello.js")]
    public Task arguments_are_new_reg_exp_and_void_0_and_instance_is_string_hello() => ExecutionTestFromFile("arguments-are-new-reg-exp-and-void-0-and-instance-is-string-hello");
    [Fact(DisplayName = "arguments-are-regexp-l-and-0-and-instance-is-string-hello.js")]
    public Task arguments_are_regexp_l_and_0_and_instance_is_string_hello() => ExecutionTestFromFile("arguments-are-regexp-l-and-0-and-instance-is-string-hello");
    [Fact(DisplayName = "arguments-are-regexp-l-and-1-and-instance-is-string-hello.js")]
    public Task arguments_are_regexp_l_and_1_and_instance_is_string_hello() => ExecutionTestFromFile("arguments-are-regexp-l-and-1-and-instance-is-string-hello");
    [Fact(DisplayName = "arguments-are-regexp-l-and-2-and-instance-is-string-hello.js")]
    public Task arguments_are_regexp_l_and_2_and_instance_is_string_hello() => ExecutionTestFromFile("arguments-are-regexp-l-and-2-and-instance-is-string-hello");
    [Fact(DisplayName = "arguments-are-regexp-l-and-3-and-instance-is-string-hello.js")]
    public Task arguments_are_regexp_l_and_3_and_instance_is_string_hello() => ExecutionTestFromFile("arguments-are-regexp-l-and-3-and-instance-is-string-hello");
    [Fact(DisplayName = "arguments-are-regexp-l-and-4-and-instance-is-string-hello.js")]
    public Task arguments_are_regexp_l_and_4_and_instance_is_string_hello() => ExecutionTestFromFile("arguments-are-regexp-l-and-4-and-instance-is-string-hello");
    [Fact(DisplayName = "arguments-are-regexp-l-and-hi-and-instance-is-string-hello.js")]
    public Task arguments_are_regexp_l_and_hi_and_instance_is_string_hello() => ExecutionTestFromFile("arguments-are-regexp-l-and-hi-and-instance-is-string-hello");
    [Fact(DisplayName = "arguments-are-regexp-l-and-undefined-and-instance-is-string-hello.js")]
    public Task arguments_are_regexp_l_and_undefined_and_instance_is_string_hello() => ExecutionTestFromFile("arguments-are-regexp-l-and-undefined-and-instance-is-string-hello");
    [Fact(DisplayName = "arguments-are-regexp-l-and-void-0-and-instance-is-string-hello.js")]
    public Task arguments_are_regexp_l_and_void_0_and_instance_is_string_hello() => ExecutionTestFromFile("arguments-are-regexp-l-and-void-0-and-instance-is-string-hello");
    [Fact(DisplayName = "arguments-are-regexp-s-and-3-and-instance-is-string-a-b-c-de-f.js")]
    public Task arguments_are_regexp_s_and_3_and_instance_is_string_a_b_c_de_f() => ExecutionTestFromFile("arguments-are-regexp-s-and-3-and-instance-is-string-a-b-c-de-f");
    [Fact(DisplayName = "call-split-1-0-instance-is-number.js")]
    public Task call_split_1_0_instance_is_number() => ExecutionTestFromFile("call-split-1-0-instance-is-number");
    [Fact(DisplayName = "call-split-1-1-instance-is-number.js")]
    public Task call_split_1_1_instance_is_number() => ExecutionTestFromFile("call-split-1-1-instance-is-number");
    [Fact(DisplayName = "call-split-1-2-instance-is-number.js")]
    public Task call_split_1_2_instance_is_number() => ExecutionTestFromFile("call-split-1-2-instance-is-number");
    [Fact(DisplayName = "call-split-1-boo-instance-is-number.js")]
    public Task call_split_1_boo_instance_is_number() => ExecutionTestFromFile("call-split-1-boo-instance-is-number");
    [Fact(DisplayName = "call-split-1-math-pow-2-32-1-instance-is-number.js")]
    public Task call_split_1_math_pow_2_32_1_instance_is_number() => ExecutionTestFromFile("call-split-1-math-pow-2-32-1-instance-is-number");
    [Fact(DisplayName = "call-split-123-instance-is-this123is123a123string123object.js")]
    public Task call_split_123_instance_is_this123is123a123string123object() => ExecutionTestFromFile("call-split-123-instance-is-this123is123a123string123object");
    [Fact(DisplayName = "call-split-2-instance-is-string-one-two-three-four-five.js")]
    public Task call_split_2_instance_is_string_one_two_three_four_five() => ExecutionTestFromFile("call-split-2-instance-is-string-one-two-three-four-five");
    [Fact(DisplayName = "call-split-4-instance-is-string-one-1-two-2-four-4.js")]
    public Task call_split_4_instance_is_string_one_1_two_2_four_4() => ExecutionTestFromFile("call-split-4-instance-is-string-one-1-two-2-four-4");
    [Fact(DisplayName = "call-split-h-instance-is-string-hello.js")]
    public Task call_split_h_instance_is_string_hello() => ExecutionTestFromFile("call-split-h-instance-is-string-hello");
    [Fact(DisplayName = "call-split-hello-instance-is-string-hello.js")]
    public Task call_split_hello_instance_is_string_hello() => ExecutionTestFromFile("call-split-hello-instance-is-string-hello");
    [Fact(DisplayName = "call-split-hellothere-instance-is-string-hello.js")]
    public Task call_split_hellothere_instance_is_string_hello() => ExecutionTestFromFile("call-split-hellothere-instance-is-string-hello");
    [Fact(DisplayName = "call-split-instance-is-empty-string-object.js")]
    public Task call_split_instance_is_empty_string_object() => ExecutionTestFromFile("call-split-instance-is-empty-string-object");
    [Fact(DisplayName = "call-split-instance-is-string-one-1-two-2-four-4.js")]
    public Task call_split_instance_is_string_one_1_two_2_four_4() => ExecutionTestFromFile("call-split-instance-is-string-one-1-two-2-four-4");
    [Fact(DisplayName = "call-split-instance-is-string-one-two-three-four-five.js")]
    public Task call_split_instance_is_string_one_two_three_four_five() => ExecutionTestFromFile("call-split-instance-is-string-one-two-three-four-five");
    [Fact(DisplayName = "call-split-instance-is-string-one-two-three.js")]
    public Task call_split_instance_is_string_one_two_three() => ExecutionTestFromFile("call-split-instance-is-string-one-two-three");
    [Fact(DisplayName = "call-split-instance-is-string.js")]
    public Task call_split_instance_is_string() => ExecutionTestFromFile("call-split-instance-is-string");
    [Fact(DisplayName = "call-split-l-0-instance-is-string-hello.js")]
    public Task call_split_l_0_instance_is_string_hello() => ExecutionTestFromFile("call-split-l-0-instance-is-string-hello");
    [Fact(DisplayName = "call-split-l-1-instance-is-string-hello.js")]
    public Task call_split_l_1_instance_is_string_hello() => ExecutionTestFromFile("call-split-l-1-instance-is-string-hello");
    [Fact(DisplayName = "call-split-l-2-instance-is-string-hello.js")]
    public Task call_split_l_2_instance_is_string_hello() => ExecutionTestFromFile("call-split-l-2-instance-is-string-hello");
    [Fact(DisplayName = "call-split-l-3-instance-is-string-hello.js")]
    public Task call_split_l_3_instance_is_string_hello() => ExecutionTestFromFile("call-split-l-3-instance-is-string-hello");
    [Fact(DisplayName = "call-split-l-4-instance-is-string-hello.js")]
    public Task call_split_l_4_instance_is_string_hello() => ExecutionTestFromFile("call-split-l-4-instance-is-string-hello");
    [Fact(DisplayName = "call-split-l-instance-is-string-hello.js")]
    public Task call_split_l_instance_is_string_hello() => ExecutionTestFromFile("call-split-l-instance-is-string-hello");
    [Fact(DisplayName = "call-split-l-na-n-instance-is-string-hello.js")]
    public Task call_split_l_na_n_instance_is_string_hello() => ExecutionTestFromFile("call-split-l-na-n-instance-is-string-hello");
    [Fact(DisplayName = "call-split-ll-instance-is-string-hello.js")]
    public Task call_split_ll_instance_is_string_hello() => ExecutionTestFromFile("call-split-ll-instance-is-string-hello");
    [Fact(DisplayName = "call-split-new-reg-exp.js")]
    public Task call_split_new_reg_exp() => ExecutionTestFromFile("call-split-new-reg-exp");
    [Fact(DisplayName = "call-split-null-instance-is-thisnullisnullanullstringnullobject.js")]
    public Task call_split_null_instance_is_thisnullisnullanullstringnullobject() => ExecutionTestFromFile("call-split-null-instance-is-thisnullisnullanullstringnullobject");
    [Fact(DisplayName = "call-split-o-instance-is-string-hello.js")]
    public Task call_split_o_instance_is_string_hello() => ExecutionTestFromFile("call-split-o-instance-is-string-hello");
    [Fact(DisplayName = "call-split-on-instance-is-string-one-1-two-2-four-4.js")]
    public Task call_split_on_instance_is_string_one_1_two_2_four_4() => ExecutionTestFromFile("call-split-on-instance-is-string-one-1-two-2-four-4");
    [Fact(DisplayName = "call-split-r-42-instance-is-string-one-1-two-2-four-4.js")]
    public Task call_split_r_42_instance_is_string_one_1_two_2_four_4() => ExecutionTestFromFile("call-split-r-42-instance-is-string-one-1-two-2-four-4");
    [Fact(DisplayName = "call-split-true-instance-is-thistrueistrueatruestringtrueobject.js")]
    public Task call_split_true_instance_is_thistrueistrueatruestringtrueobject() => ExecutionTestFromFile("call-split-true-instance-is-thistrueistrueatruestringtrueobject");
    [Fact(DisplayName = "call-split-undefined-instance-is-string-hello.js")]
    public Task call_split_undefined_instance_is_string_hello() => ExecutionTestFromFile("call-split-undefined-instance-is-string-hello");
    [Fact(DisplayName = "call-split-void-0-instance-is-thisundefinedisundefinedaundefinedstringundefinedobject.js")]
    public Task call_split_void_0_instance_is_thisundefinedisundefinedaundefinedstringundefinedobject() => ExecutionTestFromFile("call-split-void-0-instance-is-thisundefinedisundefinedaundefinedstringundefinedobject");
    [Fact(DisplayName = "call-split-without-arguments-and-instance-is-empty-string.js")]
    public Task call_split_without_arguments_and_instance_is_empty_string() => ExecutionTestFromFile("call-split-without-arguments-and-instance-is-empty-string");
    [Fact(DisplayName = "call-split-x-instance-is-empty-string.js")]
    public Task call_split_x_instance_is_empty_string() => ExecutionTestFromFile("call-split-x-instance-is-empty-string");
    [Fact(DisplayName = "call-split-x-instance-is-string-hello.js")]
    public Task call_split_x_instance_is_string_hello() => ExecutionTestFromFile("call-split-x-instance-is-string-hello");
    [Fact(DisplayName = "checking-if-creating-the-string-prototype-split-object-fails.js")]
    public Task checking_if_creating_the_string_prototype_split_object_fails() => ExecutionTestFromFile("checking-if-creating-the-string-prototype-split-object-fails");
    [Fact(DisplayName = "checking-if-deleting-the-string-prototype-split-length-property-fails.js")]
    public Task checking_if_deleting_the_string_prototype_split_length_property_fails() => ExecutionTestFromFile("checking-if-deleting-the-string-prototype-split-length-property-fails");
    [Fact(DisplayName = "checking-if-enumerating-the-string-prototype-split-length-property-fails.js")]
    public Task checking_if_enumerating_the_string_prototype_split_length_property_fails() => ExecutionTestFromFile("checking-if-enumerating-the-string-prototype-split-length-property-fails");
    [Fact(DisplayName = "checking-if-varying-the-string-prototype-split-length-property-fails.js")]
    public Task checking_if_varying_the_string_prototype_split_length_property_fails() => ExecutionTestFromFile("checking-if-varying-the-string-prototype-split-length-property-fails");
    [Fact(DisplayName = "checking-string-prototype-split-length.js")]
    public Task checking_string_prototype_split_length() => ExecutionTestFromFile("checking-string-prototype-split-length");
    [Fact(DisplayName = "checking-string-prototype-split-prototype.js")]
    public Task checking_string_prototype_split_prototype() => ExecutionTestFromFile("checking-string-prototype-split-prototype");
    [Fact(DisplayName = "cstm-split-get-err.js")]
    public Task cstm_split_get_err() => ExecutionTestFromFile("cstm-split-get-err");
    [Fact(DisplayName = "cstm-split-is-null.js")]
    public Task cstm_split_is_null() => ExecutionTestFromFile("cstm-split-is-null");
    [Fact(DisplayName = "cstm-split-on-bigint-primitive.js")]
    public Task cstm_split_on_bigint_primitive() => ExecutionTestFromFile("cstm-split-on-bigint-primitive");
    [Fact(DisplayName = "cstm-split-on-boolean-primitive.js")]
    public Task cstm_split_on_boolean_primitive() => ExecutionTestFromFile("cstm-split-on-boolean-primitive");
    [Fact(DisplayName = "cstm-split-on-number-primitive.js")]
    public Task cstm_split_on_number_primitive() => ExecutionTestFromFile("cstm-split-on-number-primitive");
    [Fact(DisplayName = "cstm-split-on-string-primitive.js")]
    public Task cstm_split_on_string_primitive() => ExecutionTestFromFile("cstm-split-on-string-primitive");
    [Fact(DisplayName = "instance-is-array-1-2-3-4-5.js")]
    public Task instance_is_array_1_2_3_4_5() => ExecutionTestFromFile("instance-is-array-1-2-3-4-5");
    [Fact(DisplayName = "instance-is-boolean.js")]
    public Task instance_is_boolean() => ExecutionTestFromFile("instance-is-boolean");
    [Fact(DisplayName = "instance-is-function.js")]
    public Task instance_is_function() => ExecutionTestFromFile("instance-is-function");
    [Fact(DisplayName = "instance-is-math.js")]
    public Task instance_is_math() => ExecutionTestFromFile("instance-is-math");
    [Fact(DisplayName = "instance-is-new-string.js")]
    public Task instance_is_new_string() => ExecutionTestFromFile("instance-is-new-string");
    [Fact(DisplayName = "instance-is-number-1234567890.js")]
    public Task instance_is_number_1234567890() => ExecutionTestFromFile("instance-is-number-1234567890");
    [Fact(DisplayName = "instance-is-number-1e21.js")]
    public Task instance_is_number_1e21() => ExecutionTestFromFile("instance-is-number-1e21");
    [Fact(DisplayName = "instance-is-number-na-n.js")]
    public Task instance_is_number_na_n() => ExecutionTestFromFile("instance-is-number-na-n");
    [Fact(DisplayName = "instance-is-object.js")]
    public Task instance_is_object() => ExecutionTestFromFile("instance-is-object");
    [Fact(DisplayName = "instance-is-string-one-two-three-four-five.js")]
    public Task instance_is_string_one_two_three_four_five() => ExecutionTestFromFile("instance-is-string-one-two-three-four-five");
    [Fact(DisplayName = "instance-is-string.js")]
    public Task instance_is_string() => ExecutionTestFromFile("instance-is-string");
    [Fact(DisplayName = "limit-touint32-error.js")]
    public Task limit_touint32_error() => ExecutionTestFromFile("limit-touint32-error");
    [Fact(DisplayName = "name.js")]
    public Task name() => ExecutionTestFromFile("name");
    [Fact(DisplayName = "not-a-constructor.js")]
    public Task not_a_constructor() => ExecutionTestFromFile("not-a-constructor");
    [Fact(DisplayName = "separator-colon-instance-is-string-one-1-two-2-four-4.js")]
    public Task separator_colon_instance_is_string_one_1_two_2_four_4() => ExecutionTestFromFile("separator-colon-instance-is-string-one-1-two-2-four-4");
    [Fact(DisplayName = "separator-comma-instance-is-string-one-two-three-four-five.js")]
    public Task separator_comma_instance_is_string_one_two_three_four_five() => ExecutionTestFromFile("separator-comma-instance-is-string-one-two-three-four-five");
    [Fact(DisplayName = "separator-empty-string-instance-is-string.js")]
    public Task separator_empty_string_instance_is_string() => ExecutionTestFromFile("separator-empty-string-instance-is-string");
    [Fact(DisplayName = "separator-number-limit-math-pow-2-32-1-instance-is-number.js")]
    public Task separator_number_limit_math_pow_2_32_1_instance_is_number() => ExecutionTestFromFile("separator-number-limit-math-pow-2-32-1-instance-is-number");
    [Fact(DisplayName = "separator-override-tostring-limit-override-valueof-throws.js")]
    public Task separator_override_tostring_limit_override_valueof_throws() => ExecutionTestFromFile("separator-override-tostring-limit-override-valueof-throws");
    [Fact(DisplayName = "separator-override-tostring-limit-override-valueof-tostring-throws.js")]
    public Task separator_override_tostring_limit_override_valueof_tostring_throws() => ExecutionTestFromFile("separator-override-tostring-limit-override-valueof-tostring-throws");
    [Fact(DisplayName = "separator-override-tostring-limit-override-valueof-tostring.js")]
    public Task separator_override_tostring_limit_override_valueof_tostring() => ExecutionTestFromFile("separator-override-tostring-limit-override-valueof-tostring");
    [Fact(DisplayName = "separator-override-tostring-limit-override-valueof.js")]
    public Task separator_override_tostring_limit_override_valueof() => ExecutionTestFromFile("separator-override-tostring-limit-override-valueof");
    [Fact(DisplayName = "separator-override-tostring-throws-limit-override-valueof-throws.js")]
    public Task separator_override_tostring_throws_limit_override_valueof_throws() => ExecutionTestFromFile("separator-override-tostring-throws-limit-override-valueof-throws");
    [Fact(DisplayName = "separator-override-valueof.js")]
    public Task separator_override_valueof() => ExecutionTestFromFile("separator-override-valueof");
    [Fact(DisplayName = "separator-regexp-comma-instance-is-string-one-1-two-2-four-4.js")]
    public Task separator_regexp_comma_instance_is_string_one_1_two_2_four_4() => ExecutionTestFromFile("separator-regexp-comma-instance-is-string-one-1-two-2-four-4");
    [Fact(DisplayName = "separator-string-instance-is-empty-string-object.js")]
    public Task separator_string_instance_is_empty_string_object() => ExecutionTestFromFile("separator-string-instance-is-empty-string-object");
    [Fact(DisplayName = "separator-undef-limit-custom.js")]
    public Task separator_undef_limit_custom() => ExecutionTestFromFile("separator-undef-limit-custom");
    [Fact(DisplayName = "separator-undef-limit-zero.js")]
    public Task separator_undef_limit_zero() => ExecutionTestFromFile("separator-undef-limit-zero");
    [Fact(DisplayName = "separator-undef.js")]
    public Task separator_undef() => ExecutionTestFromFile("separator-undef");
    [Fact(DisplayName = "this-value-not-obj-coercible.js")]
    public Task this_value_not_obj_coercible() => ExecutionTestFromFile("this-value-not-obj-coercible");
    [Fact(DisplayName = "transferred-to-custom.js")]
    public Task transferred_to_custom() => ExecutionTestFromFile("transferred-to-custom");
    [Fact(DisplayName = "transferred-to-number-separator-override-tostring-returns-regexp.js")]
    public Task transferred_to_number_separator_override_tostring_returns_regexp() => ExecutionTestFromFile("transferred-to-number-separator-override-tostring-returns-regexp");
    [Fact(DisplayName = "valueOf-is-called-for-limit-argument.js")]
    public Task valueOf_is_called_for_limit_argument() => ExecutionTestFromFile("valueOf-is-called-for-limit-argument");
}
